src/thirdparty/CMakeLists.txt
Having include/fmt on your path caused problems with finding fmt's time.h before the system's <ctime> header.  This is bad so I fixed it.
=> remove bad fmt include

src/axom/mint/docs/sphinx/sections/fem.rst
Use LaTex "array" environment instead of "eqnarray", which
apparently cannot store more than 3 columns.
=> BUGFIX: fix sphinx doc latex/pdf failures

scripts/uberenv/packages/uberenv-axom/package.py, scripts/uberenv/packages/umpire/package.py
Looks like I merged my previous macos uberenv PR (#48) too soon...
This PR allows disabling openmp in our local umpire spack package for compilers that do not support it (e.g. the built-in clang on macos).  Umpire enables openmp by default, so we need to be able to explicitly disable it.
After this PR, I was able to configure uberenv with the default compiler using the following spec
```bash
--spec=%clang~openmp^conduit@master
```
Notes:
* I had to use a newer version of conduit due to an incompatibility between 32-bit and 64-bit int types with the current Axom and conduit version 0.3.1 on mac (#50)
* My laptop's Fortran compiler is currently not working, so my test build set the Fortran compiler to `None` and my spec also disabled mpi, e.g. ``--spec=%clang~openmp~mpi^conduit@master``
=> Adds openmp variant to Axom's local umpire spack package

.github/PULL_REQUEST_TEMPLATE.md
The PR will start using Github's pull-request template to support good developer communication and coordination.  This is a incremental feature added to our development process.  At our last project meeting (24 June 2019) we collectively thought it was a good idea, so here it is.
Axom developers, and our users, through encouraging developers to clearly state reasons for the change in a PR.
=> Add a Github PR template

src/thirdparty/CMakeLists.txt
Quiets a lot of warnings out of GNU 8.1+ due to our flag added to sparsehash
=> Quiet lots of warnings from compile flag

src/axom/spin/BVH.hpp, src/axom/spin/internal/linear_bvh/build_radix_tree.hpp
This PR improves the robustness of the BVH by:
* Using `std::stable_sort` on the CPU for sorting the BVH bins in a deterministic way
* Scaling the supplied bounding boxes by a scaling factor. The scaling factor can be set by the caller. If a scaling factor is not set, the default is set to `1.001`.
=> Improve BVH robustness

scripts/make_release_tarball.sh
This PR updates the release tarball script such that:
-  Axom/data is not included by default in the source release tarball. A different tarball can be optionally created to store the corresponding Axom/data by supplying the "--with-data" option to the script.
- Added a check to the script to ensure we are using GNU tar. The script makes use of the "--concatenate" flag, which only works with GNU tar. Notably, the script doesn't work with BSD tar, which is available by default on Macs. The script now checks the version and throws an error if GNU tar is not used.
=> Update release tarball script

RELEASE-NOTES.md, src/axom/mint/CMakeLists.txt, src/axom/mint/examples/CMakeLists.txt, src/axom/mint/examples/mint_su2_mesh.cpp, src/axom/mint/tests/CMakeLists.txt, src/axom/mint/tests/mint_su2_io.cpp, src/axom/mint/utils/su2_utils.cpp, src/axom/mint/utils/su2_utils.hpp
- This PR adds support for the [SU2 mesh file format](https://su2code.github.io/docs/Mesh-File/) in Mint. Both single cell topology and mixed cell topology unstructured mesh types are supported.
=> SU2 I/O support in Mint

src/axom/sidre/core/Group.cpp, src/axom/sidre/core/Group.hpp, src/axom/sidre/tests/sidre_group.cpp
- This PR is a small change
- Changes an error to a warning at the request of @kennyweiss
In the previous pull request #82, an attempt to import a conduit list resulted in a SLIC error, since Sidre Groups do not have an analogous concept.  @kennyweiss requested that this be changed to a warning, but I merged the pull request without addressing the comment.
Here the error is changed to a warning, and the import will still import all other parts of the condiut tree that it can import, while leaving out the lists and anything descending from lists.  A boolean return value is added, true if the full import is successful, false if there was a list that had to be left out.
=> Change error to warning when trying to import conduit lists into Sidre

RELEASE-NOTES.md, src/axom/config.hpp.in, src/axom/spin/internal/linear_bvh/build_radix_tree.hpp, src/cmake/AxomOptions.cmake
Allows to toggle use of CUB when Axom is compiled with CUDA.
By default CUB is disabled, but, it can be turned ON by setting
AXOM_USE_CUB, a CMake dependent option that is available when 
Axom is configured  with CUDA (i.e., ENABLE_CUDA=ON). 
This allows to disable CUB to circumvent issues encountered with
the device linker.
This PR resolves issue #88
=> Add option to Enable/Disable CUB when building with CUDA

RELEASE, src/axom/slam/OrderedSet.hpp, src/axom/slam/examples/HandleMesh.cpp
This PR is a bugfix for some warnings on the intel compiler in the slam component.
It also updates Axom's version number in the ``RELEASE`` file, which was unintentionally not updated during the last release.
Thanks @white238 for bringing them to my attention!
=> Fixes slam warnings on the intel compiler

src/axom/core/numerics/Matrix.hpp, src/axom/mint/tests/mint_fem_single_fe.cpp
This PR fixes a failing Mint test, `mint_fem_single_fe`. The test was failing due to a compiler bug, which is circumvented by the changes introduced in this PR. In addition, this PR introduces some minor stylistic changes to modernize some of the code in `mint_fem_single_fe` test to C++11.
This PR resolves #90
=> Fix failing Mint test with intel18 release build

src/axom/sidre/core/Group.cpp, src/axom/sidre/core/Group.hpp, src/axom/sidre/examples/sidre_createdatastore.cpp, src/axom/sidre/tests/sidre_attribute.cpp, src/axom/sidre/tests/sidre_group.cpp
- This PR changes the design of Group, such that load() no longer changes the group name, but instead returns the group name stored in the loaded file using an out-parameter.
- It also adds a convenience function loadChild() to load create a child Group, load it from the specified file, and name it the name stored in the file. 
- This PR comes from issues discussed at the Axom group meeting on 16 September 2019
- This PR addresses issue #99
=> Don't change a group's name when loading.

src/axom/sidre/core/DataStore.hpp, src/axom/sidre/core/Group.hpp, src/axom/sidre/docs/sphinx/buffer.rst, src/axom/sidre/docs/sphinx/datastore.rst, src/axom/sidre/docs/sphinx/group.rst, src/axom/sidre/docs/sphinx/view.rst
- This PR is a fix to documentation for Group::rename and sphinx docs' discussion of the name of the DataStore root Group.
- This addresses issue #98 .
=> Root group name documentation

host-configs/rzmanta-blueos_3_ppc64le_ib-clang@upstream_nvcc_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@upstream_xlf.cmake
- Modifies two host-config files to point directly to the XL Fortran compiler
- Fixes some recurring failures in the test suite.
=> Specified XL Fortran compiler

src/axom/lumberjack/MPIUtility.cpp, src/axom/lumberjack/Message.cpp, src/axom/lumberjack/Message.hpp, src/axom/lumberjack/TextEqualityCombiner.hpp, src/axom/lumberjack/docs/sphinx/combiner_class.rst, src/axom/lumberjack/docs/sphinx/core_concepts.rst, src/axom/lumberjack/docs/sphinx/message_class.rst, src/axom/lumberjack/docs/sphinx/quick_start.rst, src/axom/lumberjack/examples/basicExample.cpp, src/axom/lumberjack/tests/lumberjack_Lumberjack.cpp, src/axom/lumberjack/tests/lumberjack_Message.cpp, src/axom/lumberjack/tests/lumberjack_TextEqualityCombiner.cpp, src/axom/slic/streams/LumberjackStream.cpp, src/axom/slic/streams/LumberjackStream.hpp
* Fixes memory leak in lumberjack's MPI communication
* Clarifies message count is not just rank count
* Increases information out of LumberjackStream in regards to rank and message count
=> Lumberjack tweaks

host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.0_nvcc_xlf.cmake, src/axom/primal/CMakeLists.txt, src/axom/spin/examples/CMakeLists.txt
It seems that there was a conflict with setting the ``CUDA_SEPARABLE_COMPILATION``
flag on one of axom's libraries (primal) and compiling axom's libraries as object libraries.
This fixes the weird compiler bug that @bmhan12 reported:
```
ptxas /var/tmp/han12/tmpxft_00002929_00000000-5_intersect_impl.ptx, line 435; error   : Illegal operand type to instruction 'ld'
ptxas /var/tmp/han12/tmpxft_00002929_00000000-5_intersect_impl.ptx, line 435; error   : Unknown symbol '_param_0'
ptxas /var/tmp/han12/tmpxft_00002929_00000000-5_intersect_impl.ptx, line 531; error   : Illegal operand type to instruction 'ld'
ptxas /var/tmp/han12/tmpxft_00002929_00000000-5_intersect_impl.ptx, line 531; error   : Unknown symbol '_param_0'
ptxas fatal   : Ptx assembly aborted due to errors
```
Specifically, I was …
=> Sets CUDA_SEPARABLE_COMPILATION flag in blueos9 host-config

RELEASE-NOTES.md, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.0_nvcc_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@upstream_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@coral.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@upstream_nvcc_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@upstream_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-gcc@4.9.3.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@coral.cmake, scripts/uberenv/packages/uberenv-axom/package.py, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/compilers.yaml, scripts/uberenv/specs.json, src/axom/sidre/tests/sidre_group.cpp
* Update BLT
* Desperately attempt to sort out a usable solution to the MPI Fortran wrapper on blue_os
* Clean up unused variables in tests...
* Unify a bunch of blueos/blueos_p9 host-config generation logic
* Add CUDA_SEPARABLE_COMPILATION to cuda builds
=> Various Build Issues

host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0.cmake, src/axom/lumberjack/README.md, src/axom/mainpage.md, src/axom/mint/README.md, src/axom/mint/docs/sphinx/index.rst, src/axom/mint/docs/sphinx/sections/citations.rst, src/axom/mint/docs/sphinx/sections/synopsis.rst, src/axom/primal/README.md, src/axom/primal/docs/sphinx/index.rst, src/axom/quest/README.md, src/axom/sidre/README.md, src/axom/slam/README.md, src/axom/slam/docs/sphinx/index.rst, src/axom/slic/README.md, src/axom/slic/docs/sphinx/index.rst, src/axom/slic/docs/sphinx/sections/citations.rst, src/axom/slic/docs/sphinx/sections/synopsis.rst, src/axom/spin/README.md, src/conf.py, src/docs/doxygen/CMakeLists.txt, src/docs/doxygen/Doxyfile.in, src/docs/sphinx/coding_guide/references.rst, src/docs/sphinx/coding_guide/sec07_documentation.rst, src/docs/sphinx/dev_guide/component_org.rst, src/docs/sphinx/dev_guide/index.rst, src/docs/sphinx/dev_guide/pull_requests.rst, src/docs/sphinx/dev_guide/release.rst, src/docs/sphinx/quickstart_guide/config_build.rst, src/index.rst
- This PR gets ReadtheDocs to host doxygen documentation. 
You can view the doxygen by going to this branch's [ReadTheDocs](https://axom.readthedocs.io/en/docs-han12-doxygenonreadthedocs/) and clicking on one of the links under "Source Code Documentation" on the first page.
- I did a pass through and fixed any broken links I found in reStructuredText and README.md files (README's get pulled into the doxygen documentation).  There were a lot, so I probably did miss some… I also updated links in "References and Useful Resources": https://axom.readthedocs.io/en/docs-han12-doxygenonreadthedocs/docs/sphinx/coding_guide/references.html
so please let me know if they do not link to where they are supposed to.
- Added a path to sphinx-build (SPHINX_EXECUTABLE) in …
=> Host doxygen on ReadtheDocs

src/axom/spin/BVH.hpp, src/axom/spin/internal/linear_bvh/build_radix_tree.hpp, src/axom/spin/internal/linear_bvh/emit_bvh.hpp
This PR includes changes to the BVH::find() algorithm to use sum reduction variables in order to avoid GPU page faults and implicitly rely and enforce unified memory for storing the supplied `counts` and `offsets` arrays. This allows the calling application to supply device pointers for these arrays.
Resolves #131
=> Avoid GPU page faults in BVH::find()

scripts/uberenv/packages/uberenv-axom/package.py, src/axom/mint/tests/CMakeLists.txt, src/axom/sidre/examples/lulesh2/CMakeLists.txt, src/axom/sidre/examples/lulesh2/lulesh-init.cc, src/axom/sidre/examples/lulesh2/lulesh.cc, src/axom/sidre/tests/CMakeLists.txt, src/axom/slam/examples/lulesh2.0.3/CMakeLists.txt, src/axom/slam/examples/lulesh2.0.3/lulesh.cpp, src/axom/spin/tests/CMakeLists.txt
Adds a missing rpath needed for openmp when compiling with
clang + gfortran.
Resolves #141
=> Fix TPL build on LC TOSS machines

RELEASE-NOTES.md, src/axom/core/memory_management.hpp, src/axom/core/tests/core_execution_space.cpp, src/axom/core/tests/core_memory_management.cpp, src/axom/sidre/core/Buffer.hpp, src/axom/sidre/examples/lulesh2/CMakeLists.txt, src/axom/sidre/tests/sidre_buffer_unit.cpp, src/axom/sidre/tests/sidre_group.cpp, src/axom/sidre/tests/sidre_view.cpp, src/axom/spin/tests/CMakeLists.txt, src/axom/spin/tests/spin_bvh.cpp
- This PR modifies the semantics of ``axom::reallocate(_, 0)`` to always return a valid pointer
- This matches the semantics of ``Umpire``'s ``reallocate(_,0)`` function (after a bugfix in https://github.com/LLNL/Umpire/pull/292)
- This PR includes a workaround to achieve this new behavior with our existing version of Umpire. We can consider removing this workaround after we upgrade Umpire to a version later than v1.1.
- Also updates sidre's test to verify a ``Buffer`` or ``View`` is allocated after a zero-sized allocation is requested
- Note that there were no changes necessary to ``sidre``, only to our sidre tests related to zero-sized allocations.
- This change fixes a regression for Visualizing mesh blueprint files in a domain decomposed case where some domains did not have elements …
=> Modify semantics for zero-sized allocations in  `axom::reallocate()`

RELEASE-NOTES.md, src/axom/core/tests/core_memory_management.cpp, src/axom/sidre/tests/sidre_buffer.cpp, src/axom/sidre/tests/sidre_group.cpp, src/axom/sidre/tests/sidre_view.cpp, src/axom/slam/tests/slam_set_BitSet.cpp, src/axom/slam/tests/slam_set_IndirectionSet.cpp, src/axom/slam/tests/slam_set_Iterator.cpp, src/axom/spin/tests/spin_implicit_grid.cpp
Update BLT and fix new gtest warnings due to deprecated features.
#147
=> Update BLT to 0.3.0 and fix gtest warnings

RELEASE-NOTES.md, scripts/uberenv/packages/umpire/package.py, src/axom/core/memory_management.hpp
This PR updates Umpire to v2.0.0. In addition, `axom::reallocate()` is updated since umpire-v2.0.0 natively handles zero byte reallocations consistently.  The previously implemented workaround remains in place for backwards compatibility.
=> Update Umpire to v2.0.0

azure-pipelines.yml, host-configs/docker/docker-linux-ubuntu16.04-x86_64-clang@4.0.0.cmake, host-configs/docker/docker-linux-ubuntu16.04-x86_64-clang@5.0.0.cmake, host-configs/docker/docker-linux-ubuntu16.04-x86_64-clang@6.0.0.cmake, host-configs/docker/docker-linux-ubuntu16.04-x86_64-gcc@6.1.0.cmake, host-configs/docker/docker-linux-ubuntu16.04-x86_64-gcc@7.3.0.cmake, host-configs/docker/docker-linux-ubuntu16.04-x86_64-gcc@8.1.0.cmake, scripts/azure-pipelines/linux-build_and_test.sh, scripts/docker/README.md, scripts/docker/dockerfile_clang-4, scripts/docker/dockerfile_clang-5, scripts/docker/dockerfile_clang-6, scripts/docker/dockerfile_gcc-6, scripts/docker/dockerfile_gcc-7, scripts/docker/dockerfile_gcc-8, scripts/uberenv/spack_configs/docker/compilers.yaml, scripts/uberenv/spack_configs/docker/packages.yaml
- It adds support for CI testing of Axom using Azure Pipelines/Docker.
- Currently enables testing on Linux, Windows, and Mac.
- Linux testing uses following compilers: Clang 4,5,6 and GCC 6,7,8
- Dockerfiles located in axom/scripts/docker were used to generate docker images stored on Docker Hub.  See README.
=> Support for CI Testing using Azure Pipelines/Docker

RELEASE-NOTES.md, src/axom/mint/execution/internal/structured_exec.hpp
Raja changed the way cuda kernel launch bounds are calculated, which
was leading to a large number of threads being launched in the way
policies were defined previously. The large number of threads was
bloating the number of registers being used leading to a linking error
due max reg count violation. Fixed that by using Raja CudaKernelFixed
in conjuction with the "thread direct" policies.
=> Use CudaKernelFixed and tread_direct policies

scripts/azure-pipelines/linux-build_and_test.sh, src/axom/sidre/examples/lulesh2/CMakeLists.txt
Our azure job is failing the ``sidre_lulesh`` tests for ``gcc`` configurations.
Those tests use ``MPI`` and ``OpenMP``.
This is an attempt to fix it by reducing the number of threads.
=> Attempt to fix CI tests of sidre_lulesh by changing number of ctest threads

azure-pipelines.yml
Setting the option 'failTaskOnFailedTests' of the PublishTestResults task to true will cause that task to be marked as failed when any tests fail.  This addresses the confusion caused when all the Azure build and test tasks succeed (and show as green) even when one or more tests has failed.
- Fails the PublishTestResults task when test failures are detected (issue 162)
=> Set boolean option so job fails when tests fail

RELEASE-NOTES.md, src/axom/core/execution/internal/cuda_exec.hpp, src/axom/core/execution/internal/omp_exec.hpp, src/axom/core/execution/internal/seq_exec.hpp, src/axom/core/memory_management.hpp, src/axom/core/tests/core_execution_for_all.cpp, src/axom/core/tests/core_execution_space.cpp, src/axom/core/tests/core_memory_management.cpp, src/axom/mint/examples/user_guide/mint_getting_started.cpp, src/axom/mint/tests/mint_execution_cell_traversals.cpp, src/axom/mint/tests/mint_execution_face_traversals.cpp, src/axom/mint/tests/mint_execution_node_traversals.cpp, src/axom/sidre/core/Buffer.cpp, src/axom/sidre/core/Group.cpp, src/axom/sidre/core/Group.hpp, src/axom/sidre/tests/sidre_buffer.cpp, src/axom/sidre/tests/sidre_group.cpp, src/axom/sidre/tests/sidre_view.cpp, src/axom/spin/BVH.hpp, src/axom/spin/tests/spin_bvh.cpp, src/thirdparty/tests/raja_smoke.cpp
This PR changes the API of Axom's memory management routines to prevent leaking the use of `umpire::Allocator` objects in the public API. Instead, we use the corresponding integer IDs with the umpire allocators to specify an allocator. This streamlines the use of these routines in application code.
This PR resolves #175.
=> Axom Memory Management API Updates

azure-pipelines.yml
- This PR updates the ``macOS`` image in our Azure pipelines due to a recent error message
- This problem appears to be blocking #180 
- Resolves https://github.com/LLNL/axom/issues/181
=> Updates macOS host image on Azure from High Sierra to Mojave

src/axom/slic/internal/stacktrace.cpp
- It enables building with a pure clang compile using ``libc++``
- The calls to the ``gcc``'s nonstandard ``abi::__cxa_demangle`` have been protected against.
- Fixes #179
=> Don't use gcc's non-standandard abi::__cxa_demangle with clang's libc++

src/axom/core/Macros.hpp, src/axom/core/numerics/Determinants.hpp, src/axom/core/numerics/Matrix.hpp, src/axom/core/numerics/matvecops.hpp, src/axom/primal/CMakeLists.txt, src/axom/primal/geometry/NumericArray.hpp, src/axom/primal/geometry/Point.hpp, src/axom/primal/geometry/Triangle.hpp, src/axom/primal/geometry/Vector.hpp, src/axom/primal/operators/detail/intersect_impl.hpp, src/axom/primal/operators/intersect.hpp, src/axom/sidre/examples/lulesh2/CMakeLists.txt, src/axom/slic/interface/slic_macros.hpp, src/axom/slic/tests/slic_macros.cpp, src/tools/CMakeLists.txt, src/tools/mesh_tester.cpp
This PR adds a RAJA implementation of the naiveIntersectionAlgorithm in `mesh_tester.cpp`.
The naive algorithm tests each 3D triangle against each other triangle in a triangle mesh for intersection.
- `__host__ __device__` decorates (`AXOM_HOST_DEVICE`) the necessary functions to call `intersect_tri3D_tri3D` from the naïve algorithm.
- Disables the SLIC Check and Assert macros globally when using RAJA.
=> RAJA implementation of naive triangle intersection algorithm 

src/CMakeLists.txt, src/cmake/AxomMacros.cmake, src/docs/sphinx/dev_guide/component_org.rst, src/thirdparty/CMakeLists.txt
* Update to develop BLT
* Guard code checks and global options against including Axom as a subdirectory from another project
This is mainly because I want to play with clang-format (which i just added to BLT) in a few projects.
=> Small build system changes

host-configs/rzgenie-toss_3_x86_64_ib-clang@4.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@6.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@6.1.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@7.3.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.0.cmake, scripts/llnl_scripts/llnl_lc_build_tools.py, scripts/uberenv/spack_configs/toss_3_x86_64_ib/devtools/packages.yaml, scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml, scripts/uberenv/uberenv.py
* Uberenv had a python dictionary key error on the linux side of things
* Newer Spacks now add architecture optimization flags behind the scenes.. AVX2 is not compatible on all TOSS3 machines but AVX seems to be.
=> Fix uberenv, Lower Spack's architecture optimization from AVX2 to AVX

src/axom/sidre/examples/sidre_array.cpp, src/axom/sidre/examples/sidre_external_array.cpp
Add MPI barriers to synchronize all ranks after write() and read().
=> Fix Sidre Array examples

src/axom/sidre/examples/sidre_array.cpp, src/axom/sidre/examples/sidre_external_array.cpp, src/axom/sidre/spio/IOManager.cpp, src/axom/sidre/spio/IOManager.hpp
- This PR is a small bugfix.
- Fixes #203
- Adds MPI Barrier at the end of IOManager::write() to make sure all output files are complete before any further operation.
- Adds MPI Barrier at the beginning of IOManager::read() to make sure any previous operations that may be operating on the input files are complete before starting to read them.
=> Add MPI barriers and some documentation clarification in IOManager

RELEASE-NOTES.md, src/axom/spin/CMakeLists.txt
The internal header, bvh_traverse.hpp, was not
listed in CMakeLists and therefore, it was not
being installed in the specified install prefix.
Consequently, an application using
the BVH and pointing to an Axom install
prefix would result in a "cannot open include"
compiler error. Fixed that.
=> Fix missing bvh_traverse.hpp header from install prefix

config-build.py, scripts/uberenv/project.json, scripts/uberenv/uberenv.py, scripts/uberenv/vcpkg_ports/axom/CONTROL, scripts/uberenv/vcpkg_ports/axom/portfile.cmake, scripts/uberenv/vcpkg_ports/hdf5/xCONTROL, scripts/uberenv/vcpkg_ports/mfem/CONTROL, scripts/uberenv/vcpkg_ports/mfem/export-extern-vars.patch, scripts/uberenv/vcpkg_ports/mfem/portfile.cmake, src/axom/CMakeLists.txt, src/axom/quest/tests/CMakeLists.txt, src/cmake/AxomMacros.cmake, src/cmake/thirdparty/FindMFEM.cmake
- This PR improves support for `axom` builds on Windows through `uberenv`
- It adds `mfem` to the windows build. This includes a patch to label some `mfem` variables as `dllimport`/`dllexport`
- It also improves support for our `config-build` script on windows by handling paths to `CMake` that have spaces in them (e.g. ``C:\Program Files\cmake\...``)
=> Adds mfem to vcpkg uberenv build (Windows)

RELEASE-NOTES.md, src/axom/spin/internal/linear_bvh/build_radix_tree.hpp
This commit fixes an issue with the template specialization of the `custom_sort()` routine, used internally by the BVH to sort the AABBs, which would dispatch to the CPU sort(), when a CUDA async execution policy is used, i.e., `axom::CUDA_EXEC< BLOCKSIZE, axom::ASYNC >`. Now, the code will correctly dispatch to the GPU sort when a CUDA execution policy is specified irrespective of whether it is synchronous or asynchronous.
Resolves #230
=> Fix dispatch when using asynchronous CUDA execution policies with the BVH

host-configs/docker/docker-linux-ubuntu16.04-x86_64-gcc@8.1.0.cmake
Fix issue wherein linking nvToolsExt failed due to not
being able to find the nvToolsExt. This is now handled 
in BLT by passing the appropriate link flags, when the
BLT's registered cuda library is created.
=> Fix linking issue with nvToolsExt

host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@upstream_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@coral.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@nvcc.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@4.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@6.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@6.1.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@7.3.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.0.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@upstream_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-gcc@7.3.1.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@coral.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@nvcc.cmake, scripts/uberenv/packages/axom/package.py, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/devtools/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/devtools/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/packages.yaml, scripts/uberenv/spack_configs/config.yaml, scripts/uberenv/spack_configs/toss_3_x86_64_ib/devtools/packages.yaml, scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml
Updates to the system CMake which required the newest BLT. 
Host-config Status:
rzgenie - working
rzmanta - 3/5 working
rzansel -  3/5 working
spin_bvh fails on all 4 nvcc builds
=> WIP: Feature/white238/systemcmake

RELEASE-NOTES.md, src/axom/quest/interface/signed_distance.cpp, src/axom/quest/tests/quest_signed_distance.cpp, src/axom/quest/tests/quest_signed_distance_interface.cpp
Fixes an issue that prevents consecutive calls to Quest's Signed Distance query, when MPI-3 Shared memory is employed , due to not properly nullifying internal pointers when finalize() is
called.
This resolves #220
=> Fix issue with making consecutive calls to Quest's Signed Distance query when MPI-3 shared memory is employed

src/cmake/thirdparty/SetupAxomThirdParty.cmake, src/cmake/thirdparty/SetupHDF5.cmake
So apparently CMake policies are directory scoped and that's why BLT's setting of this policy didn't help.  I want the last hour of my life back.
Labels added just for kenny
=> Quiet CMP0074 and update SetupHDF5 to Conduit's behavoir

src/axom/core/Macros.hpp, src/axom/sidre/tests/sidre_native_layout.cpp
- This PR adds a Sidre test to verify that we can properly roundtrip to/from Conduit's native layout.
- Specifically, I wanted to verify that everything works properly when we have a zero-sized array View
- This came up while debugging an issue in a user code
- Sidre appears to have been working correctly: I did not have to change anything in Sidre.
=> Adds sidre test to verify proper importing of exported conduit data

src/axom/quest/tests/quest_signed_distance_interface.cpp, src/axom/spin/OctreeLevel.hpp
This PR fixes a compilation issue encountered when building Axom-v0.3.3 on rzansel using Clan9 and CUDA-10.2 toolchain.
=> Fix build issue with Clang9 and CUDA-10.2 on rzansel

src/axom/sidre/spio/IOManager.cpp
- This PR is a small refactoring, possible bugfix.
- Modifies IOManager's reading of I/O protocol string from the root file to only occur on rank 0 and then broadcast it to all ranks.  This is motivated by discussions with SCR team who pointed out that for best use of SCR features, the restarts need to have the rank that wrote a file be the one to read it.  Since rank 0 writes the root file, it needs to be the rank that reads it as well, and then any information needed by other ranks can be sent through MPI calls.
Most of the root file parsing in IO Manager already operates in this way, so this gets this operation in line with the rest of the class and is a cleaner way to do this, with or without SCR.
=> Make rank 0 find protocol string in root file, broadcast to all ranks

src/axom/sidre/CMakeLists.txt
Add ItemCollection.hpp to the list of headers so that
it gets installed to the install prefix.
=> BUGFIX: add ItemCollection.hpp to header list

host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@9.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0_no_fortran.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@no_fortran.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.4.cmake, scripts/uberenv/packages/axom/package.py, scripts/uberenv/packages/conduit/package.py, scripts/uberenv/spack_configs/toss_3_x86_64_ib/compilers.yaml, scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml, scripts/uberenv/specs.json
I added "no fortran" spec so this doesn't happen again
This issue was brought up by a Spack user. This is probably the second or third time not testing against a spec that didn't have fortran has come up.
=> Fix issue when no fortran is defined

src/axom/primal/operators/detail/intersect_impl.cpp, src/axom/primal/operators/detail/intersect_impl.hpp, src/axom/primal/operators/intersect.hpp, src/axom/primal/tests/primal_intersect.cpp, src/axom/quest/MeshTester.cpp, src/axom/quest/MeshTester.hpp, src/tools/mesh_tester.cpp
- Fixes #261 
- It exposes the tolerance threshold `EPS` for determining triangle intersections to the user.
- It sets the default tolerance for triangle intersection to `1E-8`. Previously, the intersections were getting a default of `1E-12` in the fuzzy comparison tests.
- This tolerance option is also exposed to users in the `mesh_tester` app
- I've also added a regression test derived from the mesh in #261
=> Bugfix/improvement for triangle-triangle intersect

RELEASE-NOTES.md, src/axom/mint/examples/mint_unstructured_single_topology_mesh.cpp, src/axom/mint/mesh/CellTypes.hpp, src/axom/mint/tests/CMakeLists.txt, src/axom/mint/tests/mint_mesh_connectivity_array.cpp
The clang@9.0.0 compiler was segfaulting when compiling
the mint_cell_types.cpp unit test. The key issue that
was triggering this is the use of `constexpr` when
defining the static cell_info array in CellTypes.hpp.
This appears to be a bug in the clang@9.0.0 compiler.
Although it would be nice to use `constexpr` for the
cell info, Mint does not rely on this. So, to workaround this 
issue, the code has been changed to use `const` instead 
of `constexpr`.
In addition, the `mint_cell_types.cpp` unit test is now re-enabled for 
all specs.
Resolves #266
=> clang9 workaround

src/axom/spin/ImplicitGrid.hpp, src/axom/spin/tests/spin_implicit_grid.cpp
This PR is a bugfix for ImplicitGrid in Spin. It ensures that the constructor for an ImplicitGrid from raw doubles and integers utilizes the integer argument for resolution of the grid. Previously, it would always take the values 0 for the resolution in all dimensions, due to pulling from an internal data structure. It does so by allocating a Point using the supplied values, then using that for further initialization, thus maintaining the data types used for the rest of the code. 
Also included is an expansion of the existing unit test for the initialization of ImplicitGrid, ensuring that values are being properly used.
=> BUGFIX: Using proper variables in ImplicitGrid Constructor

src/axom/core/tests/core_stack_array.cpp, src/axom/slam/OrderedSet.hpp, src/axom/slam/examples/HandleMesh.cpp, src/axom/spin/internal/linear_bvh/vec.hpp, src/docs/sphinx/dev_guide/github.rst, src/examples/using-with-blt/example.cpp, src/examples/using-with-cmake/example.cpp, src/examples/using-with-make/example.cpp, src/tools/mesh_tester.cpp
- This PR fixes some compiler warnings after a recent upgrade to several `host-configs` on LLNL's `toss3` clusters.
- Our clang host-configs still have the following warnings due to what appears to be an MPI build on the default gcc compiler:
`/usr/bin/ld: warning: libgfortran.so.3, needed by /usr/tce/packages/mvapich2/mvapich2-2.3-clang-10.0.0/lib/libmpi.so, may conflict with libgfortran.so.5`
- There are still numerous warnings about incorrect/invalide host/device decoration. I believe @bmhan12 has a forthcoming PR to address this.  (Possibly #249 ?)
=> Fixes some compiler warnings on LLNL clusters

src/axom/inlet/Table.cpp, src/axom/inlet/tests/inlet_Inlet.cpp
- Modifies Table.cpp to utilize the full path of a Field when adding it to the Inlet
=> Fix for adding Inlet Fields via Table

scripts/uberenv/vcpkg_ports/axom/CONTROL
- This PR is a bugfix: see https://github.com/LLNL/axom/issues/288
- It allows Windows TPL and src to build in a freshly-pulled repository.
This PR does the following:
- Changes the vcpkg CONTROL file for the axom package so build dependencies and features are properly specified
- Sets the default for the source build to 64-bits, to match the TPLs
=> Fix feature list and dependencies for package axom.

src/axom/inlet/LuaReader.cpp, src/axom/inlet/tests/inlet_Inlet.cpp, src/axom/inlet/tests/inlet_LuaReader.cpp
Fix a seg fault in LuaReader that was caused by some combination of existant/non-existant reading of multi-nested tables
Added regression test that seg faulted prior to fix
... This was very annoying to find and I am still not entirely sure I understand what triggers this behavior but this does make it go away.
=> Fix bug related to obtuse bug regarding the lua stack index

src/axom/sidre/examples/sidre_array.cpp, src/axom/sidre/examples/sidre_createdatastore.cpp, src/axom/sidre/examples/sidre_external_array.cpp, src/axom/sidre/tests/sidre_group.cpp, src/axom/sidre/tests/spio/F_spio_basicWriteRead.F, src/axom/sidre/tests/spio/F_spio_externalWriteRead.F, src/axom/sidre/tests/spio/F_spio_irregularWriteRead.F, src/axom/sidre/tests/spio/F_spio_parallelWriteRead.F, src/axom/sidre/tests/spio/F_spio_preserveWriteRead.F, src/axom/sidre/tests/spio/spio_parallel.cpp
- Makes sure Sidre/SPIO tests don't try to use HDF5 I/O protocols when axom is build without HDF5.
- Fixes an issue on our old tracker
=> Fix test failures in non-HDF5 builds

RELEASE-NOTES.md, src/axom/spin/internal/linear_bvh/build_radix_tree.hpp
Adds a call to ``__threadfence_system()`` in the ``propagate_aabbs()`` method which does a bottom-up  parallel construction of the BVH. The memory fence ensures that when a thread computes and stores a parent to global memory, the *write*  is observed by all threads in the system.
This fix currently only applies to NVIDIA GPUs where the bug was observed due to the incoherent L1 cache on NVIDIA GPUs.
Resolves #307
=> Fix Parallel BVH construction on GPUs due to incoherent L1 cache

src/axom/core/tests/utils_about.cpp, src/axom/core/utilities/About.cpp, src/axom/core/utilities/About.hpp, src/tools/mesh_tester.cpp
Prints the Axom version in the mesh_tester executable. Given that a number of users have gotten their hand on this executable, printing the corresponding Axom version will allow us to tell what was the corresponding Axom version used to produce the given executable.
=> Print Axom version in the mesh_tester executable

src/axom/mint/CMakeLists.txt
In some instances the code was failing to compile b/c
the compiler was not able to resolve the hdf5 header include
in one of the Sidre header. To handle this more robustly, hdf5
needs to be specified explicitely for mint when using Sidre.
Fixed that.
=> Link hdf5 when using Sidre with Mint

RELEASE-NOTES.md, src/axom/primal/operators/detail/intersect_impl.cpp, src/axom/primal/operators/intersect.hpp, src/axom/primal/tests/primal_intersect.cpp
- Fixes #152 
- There was a bug in one of the 2D triangle-triangle intersection cases in the original paper
- I added the test case from #152 and several variations
- I also added a number of 2D triangle-triangle tests where one of the points of the second triangle are known to be inside the first triangle.  It uses points from barycentric coordinates to ensure that we can get exact edge and corner cases where the other points of the triangles are on edges and corners :)
- Minor: I ran uncrustify on primal
=> Fixes a 2D triangle intersection case

RELEASE-NOTES.md, azure-pipelines.yml, src/axom/quest/InOutOctree.hpp, src/axom/quest/examples/quest_signed_distance_interface.cpp, src/axom/slam/BivariateMap.hpp, src/axom/slam/Map.hpp, src/axom/slam/MapBase.hpp, src/axom/slam/SubMap.hpp, src/axom/slam/examples/ShockTube.cpp, src/axom/slam/examples/UnstructMeshField.cpp, src/axom/slam/examples/lulesh2.0.3/lulesh-init.cpp, src/axom/slam/examples/lulesh2.0.3/lulesh-util.cpp, src/axom/slam/examples/lulesh2.0.3/lulesh.cpp, src/axom/slam/examples/lulesh2.0.3/lulesh.hpp, src/axom/slam/tests/slam_set_IndirectionSet.cpp, src/axom/spin/ImplicitGrid.hpp, src/axom/spin/OctreeBase.hpp, src/axom/spin/OctreeLevel.hpp, src/axom/spin/SparseOctreeLevel.hpp, src/axom/spin/SpatialOctree.hpp, src/axom/spin/UniformGrid.hpp, src/axom/spin/tests/spin_spatial_octree.cpp
- Resolves #296 -- Axom can once again be configured with `AXOM_USE_64BIT_INDEXTYPE`
- Resolves #295 -- Quest's `InOutOctree` can use up to 64 levels when axom is configured with `AXOM_USE_64BIT_INDEXTYPE`
A future PR will consider extentions to the `Octree` and `InOutOctree` classes to allow more than 32 levels of resolution, regardless of the value of `axom::IndexType`. This might take the form of an extra template parameter that defaults to `axom::IndexType`.
=> Bugfix for 64 bit indexing in slam, spin and quest

src/axom/core/utilities/About.cpp
This is fixes a build error when not in a git repository.
... i just want to use a new Axom in Serac....
=> Fix build error when AXOM_VERSION_EXTRA is not defined

src/axom/sidre/examples/lulesh2/CMakeLists.txt
A user showed that we were guarding hdf5 properly in our lulesh2 example.  I reproduced this by turning off axom's and conduits hdf5 variant then building.  Because hdf5 is not a target in this state CMake blindly puts -lhdf5 on the link line hoping it is on the system (it actually is on rzgenie, unhelpfully?).  But this fix made it go away.
(All the labels for @kennyweiss )
=> Guard hdf5

RELEASE-NOTES.md, src/axom/core/examples/core_containers.cpp, src/axom/inlet/LuaReader.hpp, src/axom/primal/operators/detail/intersect_impl.hpp, src/axom/primal/operators/intersect.hpp, src/axom/primal/tests/primal_intersect.cpp
- This PR is a bugfix for `primal::intersect(Segment, BoundingBox)`
- It fixes the initial bounds calculations for determining if the segment intersect bounding box
- Closes #342
=> Bugfix for primal::intersect(Segment, BoundingBox)

src/axom/inlet/SchemaCreator.hpp, src/thirdparty/tests/CMakeLists.txt
I swear I tested this. I am not sure how the hdf5 ever worked. Serac is the only configuration I know that turns on mpi for hdf5 but I turned it on 25 days ago and there has been multiple TPL builds since then...
=> Fix build errors found with Serac's configuration

RELEASE-NOTES.md, src/axom/slic/core/Logger.cpp, src/axom/slic/core/Logger.hpp, src/axom/slic/docs/sphinx/sections/getting_started.rst, src/axom/slic/examples/CMakeLists.txt, src/axom/slic/examples/basic/custom_abort_logger.cpp, src/axom/slic/interface/slic.cpp, src/axom/slic/interface/slic.hpp
- Adds the ability for the user to specify a custom abort function - `axom::utilities::processAbort` remains the default
`std::function` could be used in place of raw function pointers.
An example usage was also added.
=> Allow user to specify an abort callback for slic abort

src/axom/inlet/Inlet.hpp, src/axom/inlet/LuaReader.hpp, src/axom/inlet/SchemaCreator.hpp, src/axom/inlet/tests/inlet_LuaReader.cpp, src/axom/primal/geometry/NumericArray.hpp, src/axom/primal/geometry/Point.hpp, src/axom/primal/geometry/Vector.hpp, src/axom/primal/tests/primal_numeric_array.cpp, src/axom/primal/tests/primal_point.cpp, src/axom/primal/tests/primal_vector.cpp, src/axom/sidre/core/DataStore.cpp, src/axom/sidre/core/DataStore.hpp, src/axom/sidre/tests/sidre_group.cpp, src/axom/sidre/tests/sidre_view.cpp
The primal class templates NumericArray, Point, and Vector now have
constructors from initializer lists. As per a conversation with Kenny
and Rich, these are not marked with AXOM_HOST_DEVICE for now.
- This PR is a  feature
- It does the following
- Creates constructors on Vector, Point, and NumericArray to create these classes from instances of std::initializer_list.
=> Added std::initializer_list constructors to primal primitives

RELEASE-NOTES.md, src/axom/primal/tests/primal_numeric_array.cpp, src/axom/primal/tests/primal_point.cpp, src/axom/primal/tests/primal_vector.cpp, src/axom/quest/examples/containment_driver.cpp
- It adds a ``--batched`` flag to the quest::InOutOctree point containment example
- When this is set and the code is built using RAJA and OpenMP, it will run the containment query
over an array of points using the RAJA OMP execution policy.
=> Adds batched option to quest's InOutOctree containment example

RELEASE-NOTES.md, src/axom/inlet/Field.cpp, src/axom/inlet/Field.hpp, src/axom/inlet/Proxy.cpp, src/axom/inlet/Proxy.hpp, src/axom/inlet/Table.cpp, src/axom/inlet/Table.hpp, src/axom/inlet/Verifiable.hpp, src/axom/inlet/VerifiableScalar.hpp, src/axom/inlet/examples/user_defined_type.cpp, src/axom/inlet/tests/inlet_object.cpp
- Adds const to member functions and local variables
- Adds `true` as the default argument to `Verifiable::required` and `VerifiableScalar::required` (and the implementations of those interfaces)
In the interest of keeping PRs small, other fixes (e.g. removing `shared_ptr` when possible) will be part of future PRs.
=> Const correctness in Inlet

RELEASE-NOTES.md, src/axom/inlet/Field.cpp, src/axom/inlet/Field.hpp, src/axom/inlet/Inlet.cpp, src/axom/inlet/Inlet.hpp, src/axom/inlet/Table.cpp, src/axom/inlet/Table.hpp, src/axom/inlet/Verifiable.hpp, src/axom/inlet/VerifiableScalar.hpp, src/axom/inlet/examples/arrays.cpp, src/axom/inlet/examples/documentation_generation.cpp, src/axom/inlet/examples/user_defined_type.cpp, src/axom/inlet/examples/verification.cpp, src/axom/inlet/inlet_utils.hpp, src/axom/inlet/tests/inlet_Inlet.cpp, src/axom/inlet/tests/inlet_object.cpp
- Removes all `shared_ptr`s from the Inlet component as shared ownership is not necessary from what I can tell
Unfortunately this PR is somewhat large, but the changes are fairly boring.  
In general, functions that returned `shared_ptr`s to `Field`s or `Table`s now return references as ownership is managed by the parent `Table` object.  Functions that previously returned `shared_ptr`s to the calling object now return references to the calling object.
`unique_ptr`s were used for the `Reader` and `DocWriter` classes (where instances are moved into the `Inlet` object, as I could not think of a use case where unique ownership is insufficient.  `Table`s store references to the `Reader` object as ownership is managed by the parent `Inlet`. …
=> Remove shared_ptr from Inlet

scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/devtools/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/devtools/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/packages.yaml, scripts/uberenv/spack_configs/docker/packages.yaml, scripts/uberenv/spack_configs/toss_3_x86_64_ib/devtools/packages.yaml, scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml
Forgot to add the new packages.yaml support for the general `mpi` target when i updated spack.
=> simplify the packages.yaml mpi buildable logic

RELEASE-NOTES.md
Subtle niche error that showed up in a Spack build on WSL
=> Update blt to get fix that prevents a failure when clangformat is autodetected

src/axom/core/tests/CMakeLists.txt, src/axom/lumberjack/tests/CMakeLists.txt, src/axom/sidre/examples/lulesh2/CMakeLists.txt, src/axom/sidre/tests/spio/CMakeLists.txt, src/axom/slam/examples/lulesh2.0.3_orig/CMakeLists.txt
This updates BLT to include the fix i just put in to split HEADERS from SOURCES on blt_add_executable.  This is important for file level dependency checking during the build system run (ie makefiles) as well as IDE folder support.
Surprisingly enough CMake is not smart enough not to compile a header when you flag it for separable compilation, it has logic everywhere else not to compile a header by itself based on file extension.  My guess this is in the old CUDA support and will go away when we switch to the new CMake CUDA support.
=> Split HEADERS from SOURCES on blt_add_executable

src/axom/sidre/tests/spio/F_spio_blueprintIndex.F
Fixes array indexing in one test to use Fortran 1:n indexing.
=> Fix Fortran array indexing error

src/axom/sidre/spio/IOManager.cpp, src/axom/sidre/spio/IOManager.hpp
- This PR is an enhancement.
- Removes the "_%07d" suffix from the outer "datagroup" in output files when using M->M file per processor output.
- Addresses https://github.com/LLNL/axom/issues/386
- This will make future enhancements to automatic blueprint index generation easier, and this limited change doesn't break current usage in applications.
=> Removes integer suffix from "datagroup" label in SPIO output

host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@9.0.0_upstream_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_coral.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_nvcc.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@9.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1_no_fortran.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.4.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@9.0.0_upstream_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-gcc@7.3.1.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_coral.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_nvcc.cmake, scripts/uberenv/packages/axom/package.py, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/packages.yaml, scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml, src/thirdparty/sol/sol.hpp, src/thirdparty/sol/sol.patch
* Backport fix from main sol repo to our older version of sol for Lua 5.4 compatibility
* Umpire was the only library building shared, this fixes it.  (For @gzagaris )
host-configs incoming soonish
=> Lua 5.4 compatibility + Static Umpire

src/axom/core/examples/CMakeLists.txt, src/axom/core/tests/CMakeLists.txt, src/axom/inlet/examples/CMakeLists.txt, src/axom/inlet/tests/CMakeLists.txt, src/axom/lumberjack/tests/CMakeLists.txt, src/axom/mint/tests/CMakeLists.txt, src/axom/primal/tests/CMakeLists.txt, src/axom/quest/examples/CMakeLists.txt, src/axom/quest/tests/CMakeLists.txt, src/axom/sidre/examples/CMakeLists.txt, src/axom/sidre/examples/lulesh2/CMakeLists.txt, src/axom/sidre/tests/CMakeLists.txt, src/axom/sidre/tests/spio/CMakeLists.txt, src/axom/slam/examples/CMakeLists.txt, src/axom/slam/examples/lulesh2.0.3/CMakeLists.txt, src/axom/slam/examples/tinyHydro/CMakeLists.txt, src/axom/slam/tests/CMakeLists.txt, src/axom/slic/examples/CMakeLists.txt, src/axom/slic/tests/CMakeLists.txt, src/axom/spin/internal/linear_bvh/vec.hpp, src/axom/spin/tests/CMakeLists.txt, src/axom/spin/tests/spin_bvh.cpp, src/cmake/AxomMacros.cmake, src/docs/sphinx/dev_guide/testing.rst, src/thirdparty/tests/CMakeLists.txt
#349 
* Adds a common `axom_add_test` macro, this allows us to do project-wide changes to all our tests in one place
* Fix spin_bvh test by setting environment variable `CUDA_VISIBLE_DEVICES`
=> Add test macro wrapper and fix spin_bvh test

src/axom/inlet/LuaReader.hpp
This change should enable standard lua math libraries, string, io, and package libraries in inlet. The main utility of this is to be able to calculate certain model parameters that are not compute intensive directly in lua or load external libraries no included by default.
=> Added a few standard lua base packages to the LuaReader class

RELEASE-NOTES.md, src/axom/core/utilities/StringUtilities.cpp, src/axom/core/utilities/StringUtilities.hpp, src/axom/inlet/CMakeLists.txt, src/axom/inlet/LuaReader.hpp, src/axom/inlet/YAMLReader.cpp, src/axom/inlet/YAMLReader.hpp, src/axom/inlet/tests/CMakeLists.txt, src/axom/inlet/tests/inlet_Reader.cpp, src/axom/inlet/tests/inlet_test_utils.cpp, src/axom/inlet/tests/inlet_test_utils.hpp
- Adds an implementation of the `inlet::Reader` interface for YAML
- Adds primitive Lua -> YAML translation functionality for testing purposes
I opted for a hand-rolled translation approach to avoid adding dependencies on flex/bison/ANTLR or similar and because the subset of Lua that we care about for testing purposes is fairly minimal.
=> Add YAML reader to Inlet

azure-pipelines.yml, scripts/azure-pipelines/linux-build_and_test.sh, src/axom/inlet/tests/inlet_Inlet.cpp, src/axom/inlet/tests/inlet_object.cpp
- It does the following
- Removes >= C++14 `std::make_unique`
- Adds a CI job to prevent cxx11 regressions
=> hotfix: remove make_unique from C++11-compatible tests

src/axom/sidre/examples/sidre_createdatastore.cpp, src/axom/sidre/examples/sidre_generateindex.cpp
- Adds a "_par" to the filenames used in SPIO output when running the sidre_createdatastore and sidre_generateindex examples in parallel.  This should eliminate the possibility that the serial and parallel runs of these examples might simultaneously write to the same files during regression testing.
=> Use different filenames for serial and parallel test runs of sidre examples

src/axom/inlet/Field.cpp, src/axom/inlet/Table.cpp, src/axom/inlet/Table.hpp
- Adds more helpful warnings when attempting to retrieve a primitive type that does not match the `sidre::View`'s type
- Single-quotes names in error messages to avoid ambiguity, e.g., if a user has a field called `name` in their input file:
`[Inlet] No table, field, or function with name 'name' exists` is clearer than 
`[Inlet] No table, field, or function with name name exists`
Resolves #443 
`[Inlet] Field with name 'a_simple_int' was expected to be of type 3 but was actually of type 5`
is replaced with
`[Inlet] Field with name 'a_simple_int' was expected to be of type 'int32' but was actually of type 'int8'`
=> fix: display type name when primitive type differs from expected

RELEASE-NOTES.md, src/axom/inlet/Proxy.hpp, src/axom/inlet/Table.hpp, src/axom/inlet/examples/nested_structs.cpp, src/axom/inlet/tests/inlet_object.cpp
- Adds a method to retrieve `std::vector`s of containers that ignores indices
Inlet currently uses `std::unordered_map<int, T>` as the primary representation for array types, as some `Reader`s support array discontiguous indexing.  In some cases only the contents of the array is useful (i.e., not its indices), so the added method provides a means of obtaining just the values.  Values are returned in ascending order by index.
This approach is more permissive than one that checks for contiguity and errors out accordingly, but since the user is specifically requesting a vector of the contents, I think it is reasonable to not require contiguity as long as the order of the returned vector is guaranteed.
=> Add conversion of arrays to std::vector<T>

RELEASE-NOTES.md, src/axom/inlet/Table.cpp, src/axom/inlet/examples/nested_structs.cpp, src/axom/inlet/tests/inlet_object.cpp
- This PR is a hotfix
- Fixes a bug where paths are not filtered before calls to the `Reader` as they already are in `addPrimitive` and `addGenericContainer`
=> Nested primitive array lookups must filter their paths

scripts/azure-pipelines/linux-check.sh, src/axom/slam/tests/slam_map_SubMap.cpp
This PR fixes a segfault issue when running 'make check', and re-enables cppcheck on azure-pipelines.
This PR addresses #368 .
=> Fix 'make check' segfault and re-enable cppcheck on azure-pipelines

RELEASE-NOTES.md, src/axom/inlet/Field.hpp, src/axom/inlet/Inlet.cpp, src/axom/inlet/Inlet.hpp, src/axom/inlet/Proxy.cpp, src/axom/inlet/Proxy.hpp, src/axom/inlet/Table.cpp, src/axom/inlet/Table.hpp, src/axom/inlet/examples/documentation_generation.cpp, src/axom/inlet/examples/mfem_coefficient.cpp, src/axom/inlet/examples/tables.cpp, src/axom/inlet/examples/user_defined_type.cpp, src/axom/inlet/examples/verification.cpp, src/axom/inlet/inlet_utils.cpp, src/axom/inlet/inlet_utils.hpp, src/axom/inlet/tests/inlet_Inlet.cpp, src/axom/inlet/tests/inlet_function.cpp, src/axom/inlet/tests/inlet_object.cpp
- This PR is a cleanup
- Restricts the public interface of `Inlet::Table`, in particular by removing duplicated functionality
Per my comments in https://github.com/LLNL/axom/pull/434#discussion_r564056514 and https://github.com/LLNL/axom/pull/434#issue-558533411, the interface has been tweaked a bit.
* The `addGenericArray`/`addGenericDictionary` aliases for `addStructArray`/`addStructDictionary` have been removed
* `addTable` is now private - `addStruct` should be used for nested data in the input file
* "Type-erased" implementations of `name()` and `sidreGroup` for `inlet::Proxy` have been implemented that forward to the underlying object. 
* The `Proxy` object (via `op[]`) is now the only method of access/retrieval (instead of with `getTable`) - this motivated …
=> Inlet interface cleanup

RELEASE-NOTES.md, src/axom/inlet/Table.cpp, src/axom/inlet/Table.hpp, src/axom/inlet/tests/inlet_object.cpp
- Partially addresses #476 by ignoring indices of elements that are not of the requested type
Currently, having elements of type other than the one requested in an array or dictionary is not an error - these elements are just ignored.  This PR ensures that these other elements are always ignored, but this means that an array that contains the wrong types is indistinguishable from an array that does not exist.  Both cases will cause verification to fail.  
The logic to ignore elements of unexpected type is implemented at the `Reader` level, so one option would be to throw errors there if unexpected elements are found.  This would clash with the current convention of avoiding throwing errors from the `Reader`s (and instead letting Inlet handle …
=> Consistent behavior for unexpected types in primitive arrays

RELEASE-NOTES.md, src/axom/inlet/Container.cpp, src/axom/inlet/Container.hpp, src/axom/inlet/Field.cpp, src/axom/inlet/Field.hpp, src/axom/inlet/tests/inlet_object.cpp
- This PR is a feature/bugfix
- Modifies `Field::operator bool` to ignore default values
This is sort of an extension of the discussion here: https://github.com/LLNL/axom/pull/478#discussion_r583117072
and a follow-up to #481.  With this latest set of changes, a `Container` will now only be verified if something was specified in the input file (the desired behavior) and *not* when defaults were provided in `Field`s within that `Container` (the current behavior).
=> Adjust Field::operator bool to ignore default values

src/axom/sidre/core/Buffer.cpp, src/axom/sidre/tests/sidre_native_layout.cpp, src/axom/sidre/tests/spio/spio_parallel.hpp
- Attempting to track down a bug with zero-sized arrays when opening blueprint meshes in VisIt
=> Augments sidre_native_layout tests with zero-sized arrays

src/cmake/AxomConfig.cmake, src/cmake/AxomMacros.cmake
- This PR is a build system refactoring
- Avoids rewriting headers that would not otherwise change when CMake is reconfigured
This PR is primarily intended to address the unnecessary full rebuilds that take place every time CMake is reconfigured.
Specifically, any modification to a CMakeLists.txt anywhere within Axom will cause CMake to reconfigure (which is reasonable).
The issue is that this will "touch" the config header and per-component unified headers, which most Axom components are dependent on - meaning that everything will rebuild.
These changes improve developer efficiency by only "touch"ing the generated headers if doing so would change their contents.
=> Don't rewrite generated headers if they haven't changed

src/conf.py
Before:
https://axom.readthedocs.io/en/develop/axom/inlet/docs/sphinx/advanced_types.html#accessing
After:
https://axom.readthedocs.io/en/feature-white238-banishpukegreen/axom/inlet/docs/sphinx/advanced_types.html#accessing
Examples of other choices:
https://help.farbox.com/pygments.html
=> change code-blocks syntax highlighting to not sphinx

src/axom/sidre/core/Group.cpp, src/axom/sidre/core/View.cpp, src/axom/sidre/core/View.hpp, src/axom/sidre/tests/sidre_view.cpp
- Refactors code that was in `Group::importConduitTree` to create a standalone method to import a Node holding an array into a View
As I have been working on some SPIO changes to deal with changes to the Blueprint index, I found the need to import a Node that had a simple array of integers into a View that would hold a copy of that array in an internal attached Buffer.  `importConduitTree` has the code to do this, but it only works when the array Node is a leaf in a larger tree of hierarchical conduit data, and Sidre did not provide a method to do this operation by itself.
This PR refactors the existing code that did this task in `importConduitTree` into a standalone method `importArrayNode`.
=> Add method to import Node holding array data into a View

RELEASE-NOTES.md, src/axom/quest/CMakeLists.txt, src/axom/quest/InOutOctree.hpp, src/axom/quest/examples/containment_driver.cpp, src/axom/quest/tests/CMakeLists.txt, src/axom/quest/tests/quest_regression.cpp
- A user reported seeing warnings from quest's `InOutOctree` about incorrect coloring for a specific mesh, which they provided 
- The mesh quality was really nice, but had a lot of axis-aligned triangles that grazed octree block faces
- After a few false starts, I was able to resolve this by inflating the block bounding boxes before testing for intersections
- As a consequence, we will likely have more "gray" blocks (i.e. blocks that intersect the mesh geometry) for this type of triangle
- See more details in #513 
This PR also has some code maintenance
- Migrates the axom regression test command line parsing to CLI11
- Loosens regression test that compares signed distance and point containment in cases where the point lies really close to the surface. I.e. the two can disagree about …
=> Bugfix for incorrect coloring in InOutOctree

src/axom/sidre/examples/spio/CMakeLists.txt
PR needed to trigger GitLab pipeline
Since we've run into this before, would it be worth extending `axom_add_test` as follows (pseudocode)?
```py
if not num_mpi_tasks and enable_mpi:
num_mpi_tasks = 1
```
See the current definition of `axom_add_test` below:
https://github.com/LLNL/axom/blob/f7d112c808e0a2767e57e6055c05d934c9538cca/src/cmake/AxomMacros.cmake#L118-L155
=> Fixes for SCR test in CI

.github/workflows/test_windows_tpls.yml
- This PR adds a manually triggered github actions workflow to test our Windows TPLs
- The workflow builds our TPLs via `uberenv`/`vcpkg` using the `x64-windows` and `x86-windows` triplets
and tests Axom against these for Axom's `Debug` and `Release` builds
- As a future extension, it might be nice if we could cache the TPLs. Then we could test these against PRs into develop. 
- See issue #546 for more details
- I'm planning to squash merge this to reduce due to all the trial and error commits
Successful run of this workflow after merging #502:  
* https://github.com/LLNL/axom/actions/runs/824679693
=> Adds manually triggered github actions workflow for testing Windows TPLs

RELEASE-NOTES.md, src/cmake/thirdparty/FindConduit.cmake
We were using the old legacy config directory which has now been removed.
https://github.com/LLNL/conduit/issues/679
=> Use newer Conduit config directory

host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@9.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1_no_fortran.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.4.cmake, scripts/spack/specs.json
- This PR disables openmp within the Intel host-configs on LLNL's toss3 platform
- Discussed during team meeting on 5/10/2021
- Intel's openmp optimizations were taking too long and then giving up after 20+ minutes
- I built the `intel@19` host-config manually and it compiled fairly quickly
- Resolves #544
=> Disables openmp on Intel host-configs

.github/workflows/test_windows_tpls.yml
* This PR contains some tweaks to improve the Windows TPL action workflow
* Adds option to continue on failure  -- That way one failure won't cancel the entire job.
* Export uberenv and ctest logs as "artifacts"
I tried to "publish" the unit tests so it appears visually, but it didn't seem to be in the right format.
=> Some tweaks to Windows TPL action

RELEASE-NOTES.md, scripts/spack/configs/toss_3_x86_64_ib/packages.yaml, scripts/spack/packages/axom/package.py, scripts/spack/packages/conduit/package.py, src/cmake/thirdparty/SetupHDF5.cmake
- Adds support for legacy (?) hdf5 cmake build system which creates an `hdf5` target not `hdf5::hdf5-static` etc
=> Support legacy hdf5 cmake build system

src/cmake/CMakeBasics.cmake
- This PR is a build system change
- Extends the max template depth for PGI
- Fixes #559 
Tested with PGI 21.1
=> Add template depth flag for PGI

src/axom/inlet/Container.cpp, src/axom/sidre/examples/spio/IO_SCR_Checkpoint.cpp
- Our style checker is passing on develop, but locally some files were failing `make check`
- Not sure why.
- Very low priority, but somewhat annoying when running make style on the rest of the code...
Here's what I got w/ make check:
```
>make check
Scanning dependencies of target tools_clangformat_check
[  0%] Running ClangFormat source code formatting checks.
[  0%] Built target tools_clangformat_check
Scanning dependencies of target thirdparty_tests_clangformat_check
[  0%] Running ClangFormat source code formatting checks.
[  0%] Built target thirdparty_tests_clangformat_check
Scanning dependencies of target core_clangformat_check
[ 16%] Running ClangFormat source code formatting checks.
[ 16%] Built target core_clangformat_check
Scanning dependencies of target …
```
=> Ran clang-format on codebase

RELEASE-NOTES.md, scripts/spack/packages/axom/package.py, src/CMakeLists.txt, src/cmake/AxomOptions.cmake
- This PR is a bugfix/feature
- Adds new AXOM_ENABLE_TOOLS and guards the appropriate tools from built
- Harden our guards against developer tools from bleeding into users
Closes #560 
Closes #114
=> Add and harden various CMake options

RELEASE-NOTES.md, src/axom/inlet/Inlet.hpp, src/axom/inlet/examples/arrays.cpp, src/axom/inlet/examples/nested_structs.cpp, src/axom/inlet/examples/user_defined_type.cpp, src/axom/inlet/examples/verification.cpp, src/axom/inlet/tests/inlet_Inlet.cpp, src/axom/inlet/tests/inlet_function.cpp, src/axom/inlet/tests/inlet_jsonschema_writer.cpp, src/axom/inlet/tests/inlet_object.cpp
- Modifies `inlet::Inlet` to not require a user-provided Sidre root group
- Fixes #569 
- Removes the no-longer-necessary manual datastore creation from most tests and some examples
=> Add Inlet constructor that doesn't require a Sidre group

scripts/spack/packages/axom/package.py
This was found during getting Serac to build `+cuda` on a personal laptop.  Basically it just removes the blueos checks from the generic cuda logic.
I tested this against all specs on rzansel and they passed.
=> Remove blueos requirement on cuda logic

RELEASE-NOTES.md, src/axom/inlet/Container.cpp, src/axom/inlet/Container.hpp, src/axom/inlet/Inlet.hpp, src/axom/inlet/docs/sphinx/simple_types.rst, src/axom/inlet/examples/fields.cpp, src/axom/inlet/tests/inlet_object.cpp
- Adds a name parameter (via overload) to `Container::isUserProvided` to allow for easy querying of subobjects
Provides a better solution for the workaround implemented in https://github.com/LLNL/serac/pull/491
=> Extend isUserProvided() to accept a name parameter

src/axom/mint/mesh/CurvilinearMesh.hpp, src/axom/mint/mesh/RectilinearMesh.hpp, src/axom/sidre/tests/sidre_group_F.F, src/axom/sidre/tests/sidre_view_F.f
- This PR is a bugfix for Fortran tests with XLF
- It converts empty string literals (`""`) into string literals with a space (`" "`) in some comparisons a string which is expected to be empty
- These literals are implicitly trimmed by XLF for the actual comparison
- I think we've encountered this in the past, but couldn't find it
- I also ran clang-format for two files that were somehow missed and are passing in our CI
=> Bugfix for empty string literals in XLF

RELEASE-NOTES.md, src/axom/config.hpp.in, src/cmake/AxomConfig.cmake
This PR moves some MSVC-related pragmas out of `axom/config.hpp` for non-MSVC configurations.
These caused problems with the Cray Fortran compiler and are now only added for MSVC configurations.
The errors were of the form:
```
ftn-1165 crayftn: ERROR AXOM_SIDRE, File = axom/config.hpp, Line = 171, Column = 2
Conditional compilation has unexpected syntax.  Expected conditional compilation directive.
ftn-1165 crayftn: ERROR AXOM_SIDRE, File = axom/config.hpp, Line = 173, Column = 2
Conditional compilation has unexpected syntax.  Expected conditional compilation directive.
ftn-1165 crayftn: ERROR AXOM_SIDRE, File = axom/config.hpp, Line = 175, Column = 2
Conditional compilation has unexpected syntax.  Expected conditional compilation directive.
ftn-855 crayftn: ERROR AXOM_SIDRE, File = …
```
=> Moves some MSVC-related pragmas out of config.hpp.in

src/axom/inlet/docs/sphinx/verification.rst, src/axom/inlet/examples/verification.cpp
- This PR is a docs update
- Updates the docs to match the current unexpectedNames/strict() functionality
https://axom.readthedocs.io/en/docs-essman-container_strict/axom/inlet/docs/sphinx/verification.html#unexpected-entries-in-input-files
=> Clean up + add documentation for unexpectedNames/strict()

src/cmake/axom-config.cmake.in, src/cmake/thirdparty/FindConduit.cmake
I missed one of the two directories that need to be moved in parallel.  This affects downstream users.
This should probably be fixed in conduit ultimately because this fails in a very subtle way (`conduit` is created instead of all the `conduit::conduit` targets)
Conduit outputs two sets of cmake config files, limited set in `${CONDUIT_DIR}\lib\cmake` and the full set in `${CONDUIT_DIR}\lib\cmake\conduit`
Limited set:
```
[white238@rzgenie5:repo]$ ls -al /usr/WS1/axom/libs/toss_3_x86_64_ib/2021_06_08_23_40_14/clang-10.0.0/conduit-0.7.2/lib/cmake/
total 24
drwxrwsr-x 3 weiss27 axom 4096 Jun  9 00:12 .
drwxrwsr-x 3 weiss27 axom 4096 Jun  9 00:12 ..
drwxrwsr-x 2 weiss27 axom 4096 Jun  9 00:12 conduit
-rw-rw-r-- 1 weiss27 axom 3472 Jun  9 00:11 conduit-relwithdebinfo.cmake
-rw-rw-r-- 1 …
```
=> fix exported conduit dependency

src/axom/primal/geometry/NumericArray.hpp, src/axom/primal/geometry/Vector.hpp, src/axom/spin/internal/linear_bvh/build_radix_tree.hpp
- Fixes an issue identified by @steveg21, where initializing `spin::BVH` fails with CUDA.
`nvcc` somehow doesn't warn us about certain functions with missing `AXOM_HOST_DEVICE` annotations, and instead will generate a call instruction to address `0x0`. The existing tests for the BVH code weren't able to catch the issue, since the functions in question are somehow getting inlined when our tests are being built, which avoids the problematic call instruction.
=> Add missing host/device annotations to Primal/Spin functions

RELEASE-NOTES.md, src/axom/core/Map.hpp, src/axom/core/tests/CMakeLists.txt, src/axom/core/tests/core_serial_main.cpp, src/axom/core/tests/utils_stringUtilities.hpp, src/axom/core/tests/utils_utilities.hpp, src/axom/core/utilities/StringUtilities.cpp, src/axom/core/utilities/StringUtilities.hpp, src/axom/sidre/core/MFEMSidreDataCollection.cpp, src/axom/sidre/spio/IOManager.hpp, src/axom/spin/BVH.hpp, src/tools/CMakeLists.txt, src/tools/data_collection_util.cpp
- This PR is a feature, but also includes some bugfixes
- It adds a new tool for generating distributed blueprint-compliant (high order) meshes over a Cartesian domain or from an mfem mesh: `data_collection_util`. The latter is active when Axom is configured with `mfem` and `AXOM_ENABLE_MFEM_SIDRE_DATACOLLECTION`
- This PR also improves support for loading data collections in `MFEMSidreDataCollection`. 
- Specifically:
- It avoids appending the `.root` suffix to an input root file when that suffix is already present
- It wires up the high order nodal grid function during load (when available)
- It improves error messages when attempting to load using a different number of ranks than were used to save the file
- This PR also add a new string utility function: `removeSuffix()`
- I noticed …
=> Adds a data collection utility and improves support for loading in MFEMSidreDataCollection

RELEASE-NOTES.md, src/axom/sidre/core/MFEMSidreDataCollection.cpp
- Some user configurations are built with C++14, but are pointing at a gcc@4.9.3 standard library
- The latter is not fully C++14 compliant, but is the default on some platforms, and it can be difficult to propagate the right flags in some build configuration.
- This change allows the code to build in the above configuration.
Possible resolution of #616
Note: This workaround doesn't fix the underlying problem of using `C++14` but pointing to a pre-`C++14` library. It only avoids using a feature from `C++14` that is missing from `gcc@4.9.3`'s standard library implementation, and thus not triggering the error.
=> Workaround for C++14 feature missing from gcc@4.9.3

RELEASE-NOTES.md, src/axom/primal/CMakeLists.txt, src/axom/primal/geometry/BoundingBox.hpp, src/axom/primal/geometry/NumericArray.hpp, src/axom/primal/geometry/Point.hpp, src/axom/primal/geometry/Ray.hpp, src/axom/primal/geometry/Vector.hpp, src/axom/primal/tests/CMakeLists.txt, src/axom/primal/tests/primal_zip.cpp, src/axom/primal/utils/ZipBoundingBox.hpp, src/axom/primal/utils/ZipIndexable.hpp, src/axom/primal/utils/ZipPoint.hpp, src/axom/primal/utils/ZipRay.hpp, src/axom/primal/utils/ZipVector.hpp, src/axom/spin/BVH.hpp, src/axom/spin/internal/linear_bvh/build_radix_tree.hpp, src/axom/spin/policy/LinearBVH.hpp, src/axom/spin/tests/spin_bvh.cpp
- Adds a helper template class `primal::ZipIndexable<GeomType>` which can be used to index into primitive data stored in struct-of-arrays format
- Adds implementations of `ZipIndexable` for `primal::Point`, `primal::Vector`, `primal::BoundingBox`, and `primal::Ray` via an inherited detail class `ZipBase<T>`
Resolves #604
=> Primal zip iterators

RELEASE-NOTES.md, src/axom/core/Array.hpp, src/axom/core/docs/sphinx/core_containers.rst, src/axom/core/memory_management.hpp, src/axom/core/tests/CMakeLists.txt, src/axom/core/tests/core_array.hpp, src/axom/core/tests/numerics_eigen_solve.hpp, src/axom/core/tests/numerics_matvecops.hpp
- This PR is a refactor
- Modifies/refactors `axom::Array` by adding a template parameter for the dimension of the array
This is the first of several array-related PRs, which I'm trying to minimize the size of in order to make reviewing easier.
See #633 for a more thorough plan of action
=> Extend Array to multiple dimensions

src/axom/spin/internal/linear_bvh/bvh_traverse.hpp, src/axom/spin/policy/LinearBVH.hpp
This PR adds an optimization for point queries against a BVH with the device traversal API. At a given node in the BVH, when both child nodes need to be traversed, we first traverse the node with the bounding box that is closer to the query point. This improves the performance of signed-distance queries, since the current-minimum distance for a given query point converges much faster to the actual minimum distance. As a result, more of the tree can be excluded from traversal.
This is not added to the `BVH::findCandidates` methods, because in that case, we must traverse all tentatively-intersecting nodes regardless.
Measured with `./examples/quest_signed_distance_interface_ex --batched --box_dims 200 200 200 --file ../data/quest/plane.stl`
|          | `develop` | this branch | speedup |
| …
=> BVH optimization for SignedDistance

RELEASE-NOTES.md, src/axom/core/Array.hpp, src/axom/sidre/core/MFEMSidreDataCollection.cpp, src/axom/sidre/core/MFEMSidreDataCollection.hpp, src/axom/sidre/tests/sidre_mfem_datacollection.cpp
- Moves the call to `Mesh::Finalize` to after the nodal grid function is set
- Fixes #643 @alecampos2009
=> Defer element orientation checks until nodal GF is set in MFEMSidreDataColl

src/axom/quest/SignedDistance.hpp, src/axom/quest/docs/sphinx/point_mesh_query.rst, src/axom/quest/docs/sphinx/point_mesh_query_cpp.rst, src/axom/quest/examples/quest_signed_distance_interface.F, src/axom/quest/examples/quest_signed_distance_interface.cpp, src/axom/quest/interface/c_fortran/wrapQUEST.cpp, src/axom/quest/interface/c_fortran/wrapQUEST.h, src/axom/quest/interface/c_fortran/wrapfquest.F, src/axom/quest/interface/python/pyQUESTmodule.cpp, src/axom/quest/interface/quest_shroud.yaml, src/axom/quest/interface/signed_distance.cpp, src/axom/quest/interface/signed_distance.hpp, src/axom/quest/tests/quest_regression.cpp, src/axom/quest/tests/quest_signed_distance.cpp, src/axom/quest/tests/quest_signed_distance_interface.cpp
- Removes obsolete/unused options from `SignedDistance`
- Adds capability to specify custom allocator in `SignedDistance` for both C and C++ interface
- Update documentation
Resolves #655.
=> Signed distance cleanup

scripts/spack/packages/raja/package.py, scripts/spack/packages/umpire/package.py
Found these while doing other builds. They have been upstreamed to Spack but cut a lot of time off the builds and don't want to forget next time we do a TPL build.
These are not worth rebuilding TPLs now.
=> fix some spack package build options

.gitlab-ci.yml, .gitlab/build_ruby.yml, RELEASE-NOTES.md, azure-pipelines.yml, scripts/azure-pipelines/linux-build_and_test.sh, scripts/llnl_scripts/build_src.py, scripts/llnl_scripts/llnl_lc_build_tools.py, src/axom/core/execution/execution_space.hpp, src/axom/primal/geometry/Vector.hpp, src/axom/primal/operators/closest_point.hpp, src/axom/primal/tests/primal_vector.cpp, src/axom/quest/SignedDistance.hpp, src/axom/quest/examples/quest_signed_distance_interface.cpp, src/axom/quest/tests/CMakeLists.txt, src/axom/spin/BVH.hpp
- It resolves #703 
- It improves the robustness of `primal::closest_point(pt, triangle)` by adding an `EPS` tolerance parameter and using fuzzy comparisons to better determine if/when the closest point is on an edge or vertex of the triangle
- It uses this in `SignedDistance` to better track whether the closest point is on an edge or vertex.
For these two cases, we need to track the weighted sum of all triangles incident in the edge or vertex
- It also improves how `SignedDistance` tracks which case it is in (face, edge or vertex)
- This improvement was tested against a configuration of the `plane_simp.stl` triangle mesh that was reported in #703 
as well as a new `tetrahedron.stl` mesh that was added for this PR
- Also resolves #708
- Also resolve #346
=> Improves robustness of `SignedDistance` query

src/CMakeLists.txt, src/axom/core/CMakeLists.txt, src/axom/quest/tests/quest_regression.cpp, src/thirdparty/CMakeLists.txt, src/thirdparty/tests/CMakeLists.txt, src/thirdparty/tests/c2c_smoke.cpp, src/thirdparty/tests/cli11_smoke.cpp
This removes all global include directories from Axom.  These go against CMake best practices.
=> Remove global include directories

RELEASE-NOTES.md, src/axom/core/Array.hpp, src/axom/core/Macros.hpp, src/axom/core/Map.hpp, src/axom/core/docs/sphinx/core_containers.rst, src/axom/core/examples/core_containers.cpp, src/axom/core/execution/execution_space.hpp, src/axom/core/execution/for_all.hpp, src/axom/core/execution/internal/cuda_exec.hpp, src/axom/core/execution/internal/omp_exec.hpp, src/axom/core/execution/internal/seq_exec.hpp, src/axom/core/tests/CMakeLists.txt, src/axom/core/tests/core_array.hpp, src/axom/core/tests/core_array_for_all.hpp, src/axom/core/tests/core_map.hpp, src/axom/core/tests/core_serial_main.cpp
- This PR improves testing of `axom::Array` and `axom::ArrayView` when called through `axom::for_all` kernels
- It adds a `view()` method to `axom::Array` to make it easier to get an `ArrayView` corresponding to an `Array`
- It highlights the need to mark lambdas as `mutable` if you want to modify the `ArrayView`'s data
- I also added a new macro -- `AXOM_TYPED_TEST` -- to allow using gtest's `TYPED_TESTS` with device code. The only difference was that it exposes `TestBody()` as a public method instead of a private method 
Thanks @joshessman-llnl  for a helpful discussion.
I noticed that there are potentially difficult-to-diagnose problems that can arise when (accidentally) using an `axom::Array` within a kernel. I attempted to resolve this, but after a few false turns created #724 to …
=> Adds `axom::Array::view()` method and improves testing with kernels

RELEASE-NOTES.md
- This small PR is a doc bugfix
- It updates the RELEASE-NOTES about a changed template parameter for `spin::ImplicitGrid`, which was modified in #677
- Adding after encountering compilation errors in a branch that uses `ImplicitGrid`
=> Updates RELEASE-NOTES for new template parameter in ImplicitGrid

src/axom/core/utilities/BitUtilities.hpp, src/axom/spin/internal/linear_bvh/build_radix_tree.hpp
- Resolves #583 
- Adds call to `__clz()` CUDA intrinsic for `axom::utilities::leadingZeros()` function
=> Consolidate bit-twiddle functions

src/axom/core/Array.hpp, src/axom/core/ArrayBase.hpp, src/axom/core/ArrayIteratorBase.hpp, src/axom/core/ArrayView.hpp, src/axom/core/docs/sphinx/core_containers.rst, src/axom/core/examples/core_containers.cpp, src/axom/core/tests/core_array_for_all.hpp, src/axom/quest/detail/PointFinder.hpp
- Resolves #732 
- Enables modifying data pointed to by `ArrayView<T>` when `T` is not const
- Removes requirement for marking lambdas as `mutable` in order to use `ArrayView`
- Adds `ArrayTraits<T>` class for passing static information to `ArrayBase` CRTP class
=> Allow modifying underlying data from non-const ArrayView

src/axom/sidre/tests/sidre_group.cpp
- This PR is a new test
- Adds a test that puts strings from a vector of strings into a sidre `Group` using `Group`'s list format, which uses `ListCollection` under the hood.
- Demonstrates how the list format can be used to address the request in #746
=> Add test that puts strings from a vector into a Group with list format

.mailmap, RELEASE-NOTES.md, src/axom/quest/PointInCell.hpp, src/axom/quest/detail/PointFinder.hpp, src/axom/quest/detail/PointInCellMeshWrapper_mfem.hpp, src/axom/quest/tests/quest_point_in_cell_mfem.cpp, src/axom/slam/BitSet.hpp, src/axom/spin/tests/spin_implicit_grid.cpp
- It resolves #755 
- It adds a missing 3rd parameter to the `PointInCell` class. The 3rd and 4th parameters have default values, and the code was supplying the 1st, 2nd and 4th parameters.
- **Update:** I had to remove the fourth parameter from `PointInCell` invocation in the `point_in_cell_mfem` unit tests. This will be resolved in #757 
- It also initializes a variable that was not being initialized in non-RAJA runs (like our manual Windows CI, which have `mfem` and `conduit`, but do not yet have `raja` or `umpire`)
=> Bugfix point in cell query

RELEASE-NOTES.md, src/axom/quest/SignedDistance.hpp, src/axom/quest/tests/CMakeLists.txt
- It resolves #783 
- The problem was related to cases where the closest point was along an edge with an acute dihedral angle and the incident triangles had (vastly) different areas. The sign is related to a pseudo-normal computation that sums the normals of the two incident triangles, and the code was not unitizing the normals before adding them. This can cause a problem when one of the triangles had a very small area, since the larger triangles was disproportionately weighting the sum.
- I created a few regression meshes in https://github.com/LLNL/axom_data/pull/9 that were failing before my fix and passing afterwards
=> Bugfix for sign computation in `quest::SignedDistance`

src/axom/core/ArrayBase.hpp, src/axom/spin/ImplicitGrid.hpp
- Fixes a performance regression on `ImplicitGrid` queries on the GPU, as a result of data not being correctly allocated in device memory
- On the `car.stl` mesh tester run, the ImplicitGrid kernels were running ~10 times slower than before
- As a bonus, removes usage of `aligned_storage` - it wasn't used correctly in `ArrayOps`, and it's getting deprecated in C++23 anyways
=> Fix for ImplicitGrid performance regression

RELEASE-NOTES.md, scripts/spack/configs/toss_3_x86_64_ib/compilers.yaml, scripts/spack/configs/toss_3_x86_64_ib/packages.yaml, src/axom/core/Macros.hpp, src/axom/core/memory_management.hpp, src/axom/core/tests/core_array_for_all.hpp, src/axom/quest/IntersectionShaper.hpp, src/axom/quest/detail/MeshTester_detail.hpp, src/axom/quest/detail/PointFinder.hpp, src/axom/quest/examples/quest_signed_distance_interface.cpp, src/axom/quest/interface/signed_distance.cpp, src/axom/quest/tests/quest_signed_distance.cpp, src/axom/spin/ImplicitGrid.hpp
- This PR is a bugfix for user-reported compiler errors in a `gcc@8.1` configuration without RAJA or Umpire.
- We do not currently have a CI test for this configuration and I am not sure that we need one.
- GCC was complaining about several kernels in `MeshTester` that modified lambda-captured `axom::ArrayView`s passed in by-value (using `AXOM_LAMBDA`. The fix was to change the default lambda capture to `by-reference`
- Update: This appears to be a compiler bug in `gcc@8.1` that is fixed in `gcc@8.3`
- I added the spec for the `gcc@8.3.1` compiler to our spack configuration on toss3
- I tested this branch (locally) against `%gcc@8.3.1~cpp14+devtools+mfem+c2c` and `%gcc@8.3.1~cpp14+devtools+mfem+c2c~raja~umpire`, but did not add host-configs for these new specs
- Also fixes some errors and …
=> Bugfix for gcc@8.1 config without RAJA or Umpire

.gitlab/build_corona.yml
This PR removes the allocate and release stages from the corona job.
=> Remove corona allocate/release from gitlab

src/axom/slic/core/Logger.hpp, src/axom/slic/docs/doxygen_collective_list.doc, src/axom/slic/docs/sphinx/sections/appendix.rst, src/axom/slic/docs/sphinx/sections/architecture.rst, src/axom/slic/docs/sphinx/sections/citations.rst, src/axom/slic/docs/sphinx/sections/getting_started.rst, src/axom/slic/docs/sphinx/sections/wrapping_slic_in_macros.rst, src/axom/slic/interface/slic.hpp, src/axom/slic/interface/slic_macros.hpp, src/axom/slic/streams/LumberjackStream.hpp, src/axom/slic/streams/SynchronizedStream.hpp, src/docs/doxygen/Doxyfile.in
This PR updates ReadTheDocs and doxygen to document which SLIC macros/functions are collective operations.
Resolves #524, relates to #26 discussion.
RTD of this branch:
https://axom.readthedocs.io/en/docs-han12-slicmpi/index.html
Table of collective SLIC macros:
https://axom.readthedocs.io/en/docs-han12-slicmpi/axom/slic/docs/sphinx/sections/appendix.html#collective-slic-macros
Slic Doxygen link:
https://axom.readthedocs.io/en/docs-han12-slicmpi/doxygen/html/namespaceaxom_1_1slic.html
Slic Macros Doxygen Link:
https://axom.readthedocs.io/en/docs-han12-slicmpi/doxygen/html/slic__macros_8hpp.html
=> Document Collective SLIC Functions

src/axom/core/ArrayBase.hpp, src/axom/core/tests/core_array_for_all.hpp
Currently, `axom::Array<T>` initializes memory on the device by creating an array on the host, then copying it to the device. This is to work around limitations where `T` has a non-trivial default constructor, as that constructor would need to be device-annotated.
However, if `T` is trivially default-constructible, the host-allocate-and-copy workaround is unnecessary and may cost some performance. In this PR, we launch a kernel for default-initialization if the type `T` is trivially default-constructible.
As a bonus, we replace the use of SFINAE in `detail::ArrayOpsBase` with tag-dispatch.
Measured on rzansel with `./bin/mesh_tester --method [accel_method] -p 3 --skipWeld -i [test_mesh]`:
| Test case | `develop` | this PR | speedup |
| ---------- | ---------- | ------- | -------- |
| …
=> Device optimization for axom::Array

host-configs/ruby-toss_3_x86_64_ib-clang@10.0.0.cmake, host-configs/ruby-toss_3_x86_64_ib-gcc@8.1.0_nofortran.cmake, host-configs/ruby-toss_3_x86_64_ib-gcc@8.3.1.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0_nofortran.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.3.1.cmake, scripts/spack/packages/axom/package.py, src/cmake/thirdparty/FindSCR.cmake
- This PR is a build system/TPL bug fix
- SCR depends on the library `libyogrt` and we had incorrect references to the spack package name for that library. It is `libyogrt` and not `yogrt`.  This was causing configurations to skip including SCR.
=> Fix libyogrt dependency for SCR

RELEASE-NOTES.md, src/axom/core/Array.hpp, src/axom/core/ArrayBase.hpp, src/axom/core/tests/core_array.hpp, src/axom/core/tests/core_array_for_all.hpp
This is an assortment of changes for `axom::Array`.
Public interface changes:
- Adds an initializer list constructor and assignment operator for 1-D arrays
- Adds an uninitialized memory overload for `Array::resize()`
- The "uninitialized-ness" of an Array is no longer a property of the array instance; instead, memory is only left uninitialized at the point of a call to the constructor or `Array::resize()`.
Robustness fixes:
- `ArrayOps::fill_range` now accepts a memory space argument for the source array; this allows for the proper invocation of copy constructors on the host side for arrays of a non-trivially-copyable type.
- Calls to `axom::copy` in the Array copy constructor have been replaced with a call to `ArrayOp::fill_range`.
- The type trait `HasTrivialCopyCtor<T>` which aliases …
=> Miscellaneous axom::Array improvements

.gitlab-ci.yml
This PR disables corona gitlab CI test until update to rocm 5.1.0 (4.5.2 removed)
=> Disable corona gitlab CI test until update to rocm 5.1.0

src/axom/quest/CMakeLists.txt, src/axom/quest/DistributedClosestPoint.hpp, src/axom/quest/IntersectionShaper.hpp, src/axom/quest/examples/CMakeLists.txt, src/axom/quest/examples/quest_distributed_distance_query_example.cpp, src/axom/spin/BVH.hpp, src/axom/spin/UniformGrid.hpp
- It adds a `DistributedClosestPoint` class to quest, which solves the following problem:
- Given an "object" mesh composed of a collection of points distributed across MPI ranks
and a "query" mesh composed of a collection of points, distributed across the MPI ranks
- Find the closest point in the object mesh to each point in the query mesh. (Also find the rank containing the closest point and the index of the object on that rank).
- This can be used, e.g. to compute the distance and/or direction to the object
- The class takes the dimension (2 or 3) and the execution space (sequential CPU, openmp CPU or CUDA) as runtime parameters
- The current approach to solving the distributed problem is for each rank to generate a spatial index over its "object mesh" and to …
=> Adds first cut at Distributed Closest Point query with example application

src/axom/inlet/Container.cpp, src/axom/inlet/inlet_utils.hpp
This removes the now unneeded `cpp11_compat::make_unique`.
=> Remove now unnecessary C++11 compatible `make_unique`

scripts/spack/packages/axom/package.py
Found a missed case in the `fortran` variant when building Serac.  This fixes that and just cleans up the logic.  This does not change any TPL builds so I won't be rebuilding.
=> Clean up fortran variant logic

src/axom/sidre/core/MFEMSidreDataCollection.cpp, src/axom/sidre/core/MFEMSidreDataCollection.hpp, src/axom/sidre/examples/sidre_mfem_datacollection_restart.cpp, src/axom/sidre/tests/sidre_mfem_datacollection.cpp
Allow the user to set the number of output files for Parallel IO in MFEMSidreDataCollection
- Add setter method for number of files
- use this user-specified number of files (if given) when writing out the files to disk. If not provided, use num_procs as before.
=> Set  number of output files MFEMSidreDataCollection

RELEASE-NOTES.md, src/axom/inlet/LuaReader.cpp, src/axom/inlet/LuaReader.hpp, src/axom/inlet/docs/sphinx/readers.rst, src/axom/inlet/examples/lua_library.cpp, src/axom/inlet/tests/inlet_function.cpp, src/thirdparty/CMakeLists.txt, src/thirdparty/axom/sol_forward.hpp
`sol.hpp` is a very heavily templated header.  This causes large compile times of any users of Inlet. We originally exposed the Sol `state` class for a user but that never went anywhere.
This moves the `LuaReader::solState()` getter to protected in case someone does want it and documents it that they need to derive there own class and include `sol.hpp` in their own code.
**Axom Build Times**
develop: 2m08s
This branch: 1m51s
=> Guard Sol State and Sol header

RELEASE-NOTES.md, src/axom/primal/geometry/Polyhedron.hpp, src/axom/primal/operators/detail/clip_impl.hpp, src/axom/primal/tests/primal_zip.cpp, src/axom/primal/utils/ZipBoundingBox.hpp, src/axom/primal/utils/ZipPoint.hpp, src/axom/primal/utils/ZipRay.hpp, src/axom/primal/utils/ZipVector.hpp, src/axom/quest/CMakeLists.txt, src/axom/quest/Delaunay.hpp, src/axom/quest/ScatteredInterpolation.hpp, src/axom/quest/examples/CMakeLists.txt, src/axom/quest/examples/delaunay_triangulation.cpp, src/axom/quest/examples/scattered_interpolation.cpp
- It adds a scattered data interpolation capability to `quest`
- Given a point mesh with scalar fields, following the [Conduit mesh blueprint schema](https://llnl-conduit.readthedocs.io/en/latest/blueprint_mesh.html) and a collection of query points, the class enables interpolating the scalar fields at the query points 
- This PR also adds an example application to quest that either reads in a mesh blueprint file from disk, or generates a random collection of points and uses the point coordinate positions as scalar fields. 
- The implementation builds a Delaunay triangulation over the input point set
- It then locates the simplex (triangle or tetrahedron) containing each query point and performs linear interpolation to interpolate the scalar value at its location
- …
=> Adds scattered interpolation capability to quest

.github/workflows/test_windows_tpls.yml, .uberenv_config.json, config-build.py
- It updates vcpkg to 2022.05.10 release
- It updates config-build.py to use MSVC 2022
Note: A sidre data collection test was failing in develop. This appears to be related to #820.
=> Update config-build and uberenv for MSVC 2022

RELEASE-NOTES.md, src/axom/sidre/core/Group.cpp, src/axom/sidre/core/Group.hpp, src/axom/sidre/core/SidreDataTypeIds.h, src/axom/sidre/examples/sidre_stressgroups.cpp, src/axom/sidre/interface/c_fortran/wrapGroup.cpp, src/axom/sidre/interface/c_fortran/wrapGroup.h, src/axom/sidre/interface/c_fortran/wrapfsidre.F, src/axom/sidre/interface/sidre_shroud.yaml, src/axom/sidre/tests/sidre_allocatable_F.f, src/axom/sidre/tests/sidre_buffer.cpp, src/axom/sidre/tests/sidre_external.cpp, src/axom/sidre/tests/sidre_group.cpp, src/axom/sidre/tests/sidre_group_F.F, src/axom/sidre/tests/sidre_view.cpp
- When IndexType is set to int32_t, the sidre_external and sidre_group tests fail.  The wrong overload of createView is being called since the prototypes are now too similar.
```
View* Group::createView(const std::string& path,
TypeID type,
int ndims,
const IndexType* shape)
View* Group::createView(const std::string& path,
TypeID type,
IndexType num_elems,
void* external_ptr)
```
- Consistently renamed createView functions with `int ndims, IndexType *shape` by adding `WithShape`. There are now `createViewWithShape` and  `createViewWithShapeAndAllocate`.
- Did not rename `View` methods with `int ndims, IndexType* shape` arguments.
- Update `Shroud` interface.
On June 6, 2022 We discussed the design ideas.
1. Append `WithShape` to some `createView` methods.
2. In issue #43, suggested adding …
=> Rename Group methods to createViewWithShape

src/axom/core/tests/core_array_for_all.hpp, src/axom/quest/detail/Discretize_detail.hpp, src/axom/quest/tests/quest_point_in_cell_mfem.cpp, src/axom/spin/ImplicitGrid.hpp, src/axom/spin/tests/spin_bvh.cpp, src/axom/spin/tests/spin_implicit_grid.cpp
On some of our open PRs, a couple of our GPU tests were failing on the blueos CI runs. While these failures were somewhat spurious, they always happened on the same set of tests.
As it turns out, some of our tests were trying to access host memory from device kernels; the address translation service on blueos systems would normally bail us out on these, but that capability seems to have gotten flakier recently. This PR tries to fix that by explicitly copying the offending memory to/from the device.
=> Attempted fix for CI flakiness on blueos

src/axom/quest/DistributedClosestPoint.hpp
- This PR is a minor bugfix
- It reduces the default verbosity of a logging statement within the `DistributedClosestPoint` query
=> Reduce verbosity of the distributed closest point query

RELEASE-NOTES.md, src/axom/mint/utils/vtk_utils.cpp, src/axom/primal/operators/closest_point.hpp, src/axom/primal/operators/detail/clip_impl.hpp, src/axom/primal/tests/primal_closest_point.cpp, src/axom/quest/Discretize.cpp, src/axom/quest/DistributedClosestPoint.hpp, src/axom/quest/IntersectionShaper.hpp, src/axom/quest/SignedDistance.hpp, src/axom/quest/examples/quest_signed_distance_interface.F, src/axom/quest/interface/c_fortran/wrapQUEST.cpp, src/axom/quest/interface/c_fortran/wrapQUEST.h, src/axom/quest/interface/c_fortran/wrapfquest.F, src/axom/quest/interface/python/pyQUESTmodule.cpp, src/axom/quest/interface/quest_shroud.yaml, src/axom/quest/interface/signed_distance.cpp, src/axom/quest/interface/signed_distance.hpp, src/axom/quest/readers/C2CReader.cpp, src/axom/quest/tests/quest_signed_distance.cpp, src/axom/quest/tests/quest_signed_distance_interface.cpp
- This PR is a feature based on a user request from @dtaller 
- It adds an overload to quest's `SignedDistance` query to return the closest point on the surface to the query point as well as the surface normal at that point
- It also exposes this to quest's signed distance C/Fortran API
- Resolves #845
=> Adds signed distance overload to return closest point and surface normal

src/axom/quest/examples/quest_inout_interface.cpp, src/axom/quest/interface/internal/QuestHelpers.cpp, src/axom/sidre/core/MFEMSidreDataCollection.cpp
- It fixes the build for configurations without MPI. 
- There were two issues 
- one had an unguarded inclusion of spio (which is only available when MPI is available. See: #849.
Looks like I introduced this problem in #837 when I got rid of `sidre/core/sidre.hpp`
- the other was for configs with C2C but not MPI.
- Resolves #849
=> Fixes build in configurations without MPI

src/axom/primal/operators/squared_distance.hpp
- Fixes doxygen comments in code to compute squared distances between primal objects.
The comments referred to "signed" distances and "signed" squared distances, which don't make sense and are probably outdated.  I removed the "signed" and added "squared" where needed.
=> Fix outdated references to "signed" distances in doxygen comments.

RELEASE-NOTES.md, src/axom/sidre/core/SidreDataTypeIds.h, src/axom/sidre/core/SidreTypes.hpp, src/axom/sidre/interface/SidreTypes.h, src/axom/sidre/interface/c_fortran/fsidresplicer.f, src/axom/sidre/interface/c_fortran/genfsidresplicer.py, src/axom/sidre/interface/c_fortran/wrapBuffer.cpp, src/axom/sidre/interface/c_fortran/wrapBuffer.h, src/axom/sidre/interface/c_fortran/wrapDataStore.cpp, src/axom/sidre/interface/c_fortran/wrapDataStore.h, src/axom/sidre/interface/c_fortran/wrapGroup.cpp, src/axom/sidre/interface/c_fortran/wrapGroup.h, src/axom/sidre/interface/c_fortran/wrapView.cpp, src/axom/sidre/interface/c_fortran/wrapView.h, src/axom/sidre/interface/c_fortran/wrapfsidre.F, src/axom/sidre/interface/sidre_shroud.yaml, src/axom/sidre/tests/sidre_allocatable_F.f, src/axom/sidre/tests/sidre_buffer_F.f, src/axom/sidre/tests/sidre_external.cpp, src/axom/sidre/tests/sidre_external_F.f, src/axom/sidre/tests/sidre_group_F.F, src/axom/sidre/tests/sidre_view_F.f
- This PR is a bugfix or maybe a feature.
- Makes a consistent size for `IndexType` between Core and Sidre components.
- This changes the default `IndexType` from `int64` to `int32` for Sidre.
- Adds parameter `SIDRE_IndexType` to Fortran for the kind of `IndexType`.
- Adds parameter `SIDRE_TypeID` to C and `TypeID` to Fortran to use with `axom::sidre::TypeID`
- Fixes #43
- Uses the current Shroud in the TPLs so I had to work around a bug by naming the Fortran parameter as `TypeID` instead of `SIDRE_TypeID`.  But I like that better anyways.
- The C and Fortran type for the C++ enum `TypeID` was set to `short` instead of `int`. This removes some ambiguity in some Fortran generic interface for `View::apply``.
=> IndexType32

src/axom/sidre/core/MFEMSidreDataCollection.cpp
- This PR is a bug fix
- The value `number_of_domains` in the blueprint index produced by MFEMSidreDataCollection was not set correctly because it was set prior to the data collection getting access to the MPI communicator (the true number of domains is equal to the number of procs in the communicator).  This fix sets the value correctly immediately prior to writing the index to the root file.
=> Set value number_of_domains in blueprint index to the correct value

RELEASE-NOTES.md, src/axom/core/utilities/Utilities.hpp, src/axom/mint/mesh/Field.hpp, src/axom/mint/mesh/UnstructuredMesh.hpp, src/axom/quest/Delaunay.hpp, src/axom/quest/ScatteredInterpolation.hpp, src/axom/quest/examples/CMakeLists.txt, src/axom/quest/examples/scattered_interpolation.cpp, src/axom/slam/DynamicMap.hpp, src/axom/slam/IndirectionSet.hpp, src/axom/slam/examples/UserDocs.cpp, src/axom/slam/policies/IndirectionPolicies.hpp, src/axom/slam/tests/slam_AccessingRelationDataInMap.cpp, src/axom/slam/tests/slam_relation_DynamicConstant.cpp, src/axom/slam/tests/slam_relation_StaticConstant.cpp, src/axom/slam/tests/slam_relation_StaticVariable.cpp, src/axom/slam/tests/slam_set_IndirectionSet.cpp, src/axom/slam/tests/slam_set_Iterator.cpp, src/axom/spin/ImplicitGrid.hpp
- It reorders the input points for the scattered interpolation example following the Biased Randomized Insertion Order (BRIO) algorithm. This improves the theoretical expected runtime as well as the practical performance of the Delaunay mesh generation algorithm.
- BRIO was introduced in the following paper: 
N. Amenta, S. Choi, and G. Rote. "Incremental constructions con BRIO." 
Proceedings of the 19th annual symposium on Computational geometry, 2003.
- This PR also adds a function to `quest::ScatteredInterpolation` to directly get the interpolation indices and weights. This allows users to perform the interpolation themselves.
- The scattered_interpolation example uses the latter to compare the two interpolation schemes and to check interpolation for the position …
=> Reorders input points in Scattered Interpolation query

.gitlab-ci.yml, .gitlab/build_tioga.yml, scripts/llnl_scripts/build_src.py, scripts/llnl_scripts/llnl_lc_build_tools.py
This PR:
- Adds tioga, removes corona from gitlab CI
- Adds a `--test-serial` option to build_src.py to run unit tests serially (`make test -j16` is current default) 
- This is to get around a srun/mpibind issue on tioga, where issuing multiple srun's in parallel results in `Fatal error in PMPI_Init` errors (recent discussion on Mattermost on why this is happening)
EDIT: Tioga job allowed to fail for now to safeguard against future, regular system updates.
=> Add tioga to Gitlab CI

RELEASE-NOTES.md, src/axom/core/ArrayBase.hpp, src/axom/core/tests/core_array_for_all.hpp
Fixes a segfault caused by calling `axom::Array<T>::insert()/::erase()` for a non-trivial type.
In order to create a slot for a new element in the middle of an array, or compact an array after erasing elements in the middle, we have an `ArrayOps::move()` helper to move a block of elements within an array. The resulting call to `std::move/move_backwards` will move-assign elements in the array to an uninitialized index, containing a junk pointer-to-data. The move assignment operator then attempts to deallocate this junk pointer, which causes the segfault.
The fix is to use `std::uninitialized_copy` with move iterators to correctly handle move-construction of objects in uninitialized memory.
Resolves #869.
=> Fix non-trivial axom::Array<T> insertion behavior

src/axom/primal/geometry/Triangle.hpp, src/axom/primal/tests/primal_triangle.cpp
This PR fixes a sign error in the `signedArea()` method of `primal::Triangle` objects, and updates the relevant test in `primal_triangle` that expects the incorrect behavior. Currently, triangles whose vertices are oriented counter-clockwise incorrectly return a negative area. This is also inconsistent with the behavior described by the Doxygen header. 
This is fixed by adjusting the determinant calculated in `signedArea()` to be consistent with the ["Shoelace Theorem"](https://artofproblemsolving.com/wiki/index.php/Shoelace_Theorem) for finding the oriented area of a polygon. The relevant test in `primal_triangle` is adjusted so that the points are oriented counter-clockwise.
=> Fix sign error in primal::Triangle::signedArea()

src/cmake/Dashboard.cmake.in
- This PR is a new feature
- set site name
- CTEST_DROP_SITE as environment variable LC_CDASH_DROP_SITE (injected pipeline)
- _auth_token as env. variable LC_CDASH_TOKEN (injected pipeline)
=> Adding env variables for CDash site and token

src/cmake/AxomConfig.cmake, src/cmake/thirdparty/SetupAxomThirdParty.cmake, src/thirdparty/CMakeLists.txt
This PR does two cleanup things:
1. Allows users to provide their own `mfem` CMake target.  This is useful for projects that co-develop multiple projects together. For example, Serac has the option to co-develop MFEM and Axom in one build. Fixes #874
2.  Removes the now unnecessary sparsehash header check. `std::tr1` was deprecated pre-c++11
=> Misc cleanup

src/tools/data_collection_util.cpp
This PR fixes a small bug with the parameter order:
https://github.com/mfem/mfem/blob/3dd5cbbe074607d5e98b568269ba38e0eb0a6951/mesh/mesh.hpp#L609-L612
=> Bugfix for 3D MFEM Cartesian Mesh generation

RELEASE-NOTES.md, src/axom/primal/CMakeLists.txt, src/axom/primal/constants.hpp, src/axom/primal/geometry/NumericArray.hpp, src/axom/primal/geometry/Polygon.hpp, src/axom/primal/geometry/Tetrahedron.hpp, src/axom/primal/geometry/Triangle.hpp, src/axom/primal/geometry/Vector.hpp, src/axom/primal/operators/in_sphere.hpp, src/axom/primal/operators/intersect.hpp, src/axom/primal/tests/primal_numeric_array.cpp, src/axom/primal/tests/primal_tetrahedron.cpp, src/axom/primal/tests/primal_triangle.cpp, src/axom/primal/tests/primal_vector.cpp, src/axom/primal/tests/primal_winding_number.cpp, src/axom/quest/Discretize.cpp, src/axom/quest/Discretize.hpp, src/axom/quest/detail/Discretize_detail.hpp, src/axom/spin/RectangularLattice.hpp
- It improves the robustness of several operations on primal's Triangles and Tetrahedra, including the computation of areas/volumes, barycentric coordinates and circumspheres.
- Specifically, it recasts several coordinate-based determinants as operations on vectors. This reduces the dimension of the underlying matrices by one and better uses the limited floating point precision
- It also adds a `skipNormalization` parameter to Triangle and Tetrahedron's `physToBarycentric()` method (defaulting to `false`) to avoid normalizing the results by the element's volume. This can be useful in cases where we only need the relative weights and can avoid division by zero for (nearly) degenerate elements. It also adds a tiny amount (`1e-50`) to the denominator when …
=> Improves robustness of barycentric and circumsphere computations

src/cmake/AxomConfig.cmake, src/cmake/thirdparty/SetupAxomThirdParty.cmake
I am getting closer but I am beginning to think it's not really possible to toggle between `add_subdirectory()` and `find_package()` in a clean way.
This at least allows me to build and test Axom/MFEM inside of Serac but not install.  Though that is not our normal usage so this seems okay for now.
=> More submodule work

RELEASE-NOTES.md, src/axom/primal/operators/squared_distance.hpp, src/axom/primal/tests/primal_squared_distance.cpp, src/axom/quest/DistributedClosestPoint.hpp, src/axom/quest/examples/CMakeLists.txt, src/axom/quest/examples/quest_distributed_distance_query_example.cpp
- It allows quest's `DistributedClosestPoint` query to be run on meshes where some ranks have empty "object meshes" and/or "query meshes". 
- This matches how users are planning to run the code, where the "object meshes" might be features that exist on only a subset of the ranks, and similarly, where the query points might also only exist on a subset of the ranks.
- I tried to minimize changes to the `DistributedClosestPoint` class in anticipation of merging #879 (I'm not sure which one will get merged first)
The following picture was run on a 36 rank problem where ~25% of the ranks did not have any object points (the points on the circle) and, independently, ~25% of the ranks did not send any data to the distributed closest point query. This run also used a cutoff …
=> Adds support to Distributed closest point query for empty ranks 

src/axom/primal/geometry/BezierCurve.hpp, src/axom/primal/operators/detail/in_curved_polygon_impl.hpp, src/axom/primal/operators/in_curved_polygon.hpp, src/axom/primal/operators/in_polygon.hpp, src/axom/primal/operators/is_convex.hpp, src/axom/primal/operators/split.hpp, src/axom/primal/tests/primal_polygon.cpp, src/axom/primal/tests/primal_rational_bezier.cpp, src/axom/primal/tests/primal_winding_number.cpp
This PR addresses issue #894, and is a bugfix for the following issues
-  Evaluation of winding numbers at endpoints of Bezier curves fails when endpoints are duplicated
-- Solution: Endpoint formula iterates over nodes until distinct one is found
-  Evaluation of winding numbers at endpoints of Bezier curves fails when tangent lines are anti-parallel
-- Solution: When this case is identified, iterating over interior nodes identifies orientation and returns correct winding number
- `in_polygon` returns incorrect value when point is on same horizontal line as initial vertex
-- Solution: Replace a `1` with a `0`
Additional tests were added to `primal_winding_number.cpp` and `primal_polygon.cpp` to account for these errors. Additionally, this PR addresses issues of efficiency and readability …
=> Fix direct formulas for `winding_number` on endpoint of Bezier curves

RELEASE-NOTES.md, src/axom/core/ArrayIteratorBase.hpp, src/axom/core/ArrayView.hpp, src/axom/core/IteratorBase.hpp, src/axom/primal/operators/clip.hpp, src/axom/primal/operators/detail/clip_impl.hpp, src/axom/primal/tests/primal_clip.cpp
This PR:
- Generalizes the `clipOctahedron()` input to take a Polyhedron,  becoming `clipPolyhedron()`
- Adds overloaded function `clip(tet1, tet2)` for clipping of two tetrahedrons
=> Tetrahedron - Tetrahedron Clipping

.gitignore, host-configs/other/no-tpl-toss_3_x86_64_ib-clang@10-ifort@19.cmake, src/axom/primal/tests/primal_rational_bezier.cpp, src/axom/quest/examples/CMakeLists.txt
- This PR tweaks our build system to allow mixing clang as the C/C++ compiler with ifort as the Fortran compiler and adds a simple (no-tpl) host-config
- In doing so, it cleans up how we add Fortran examples and associated tests in quest
- It also resolves #905 by adding a line to the `.gitignore` file
=> Fixes configuration with clang C/C++ compiler and Intel Fortran compiler

src/axom/sidre/core/Group.cpp, src/axom/sidre/tests/sidre_group.cpp
- This PR is a bug fix
- Modifies `Group::copyToConduitNode` to handle Groups using the list format.j
- Fixes #928 
This method had the assumption that all child items have a name.  This fix adds handling of unnamed items held in a list, and creates lists of unnamed child Nodes in the conduit output.
=> Fix Group::copyToConduitNode so that it handles lists correctly

.gitlab/build_tioga.yml
This PR converts slurm command to flux on tioga (note: there are no partitions in flux, checked with `flux resource list` ).
=> Convert slurm to flux on tioga

src/axom/primal/operators/detail/in_curved_polygon_impl.hpp, src/axom/primal/tests/primal_winding_number.cpp
This PR is a bugfix that fixes the behavior of `winding_number` with respect to nonconvex Bezier curve objects. We now require that the control polygon of a Bezier curve be convex before we can ensure our winding number formulations will be correct, which is enforced by repeated recursion until such a condition is met. Previously, there existed cases where a query point could be external to the control polygon, but still contained in the shape formed by closing the Bezier curve. A new test has been added in `primal_winding_number.cpp` to detect this incorrect behavior, and verify the correct behavior in this update.
Additionally, this PR addresses issue #907 by fixing the sign in the output of `linear_winding_number`, and adjusting signs in other areas of the winding number functionality …
=> Fixes misidentification for containment within `CurvedPolygon`s with nonconvex edges

src/axom/sidre/core/Group.hpp
- This PR is a comment-only change
- Removes some obsolete comments about Group's importConduitTree not working for conduit lists. This was true for the original implementation, but later changes made it work. The original comments did not get removed at the time.
=> Remove obsolete comments about importing conduit lists

src/axom/sidre/core/Group.cpp, src/axom/sidre/tests/sidre_group.cpp
- This PR is a fix for a code inconsistency, possibly a bug, and adds test coverage
- Modifies Group::importConduitTreeExternal to make it handle lists with unnamed members the same way as importConduitTree. The two methods should construct their Sidre hierarchical representation of the Conduit input tree in the same way. I noticed this while preparing #937
- Adds test coverage for importing Conduit lists using importConduitTreeExternal; nothing for this was existent.
=> Fix inconsistency in importConduitTreeExternal, and add test coverage

.gitlab/build_lassen.yml, .gitlab/build_tioga.yml, host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@8.0.1_cuda.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@8.3.1_cuda.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.1_cuda.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@8.3.1_cuda.cmake, scripts/spack/configs/blueos_3_ppc64le_ib_p9/compilers.yaml, scripts/spack/configs/blueos_3_ppc64le_ib_p9/packages.yaml, scripts/spack/packages/axom/package.py, scripts/spack/specs.json, src/axom/mint/tests/mint_mesh_unstructured_mesh.cpp, src/axom/quest/DistributedClosestPoint.hpp, src/axom/sidre/tests/sidre_group_F.F, src/axom/sidre/tests/spio/F_spio_externalWriteRead.F, src/axom/slam/examples/lulesh2.0.3/CMakeLists.txt, src/axom/slam/tests/slam_map_Map.cpp
This PR:
- Adds a gcc@8.3.1 host-config with both openmp and cuda enabled.
- Relates to #520 
EDIT: 
- Adds openmp to the clang@8+xlf+cuda host-config
=> Host-config with OpenMP and CUDA enabled

RELEASE-NOTES.md, src/axom/core/Array.hpp, src/axom/core/ArrayView.hpp, src/axom/core/tests/core_array.hpp, src/axom/core/tests/core_array_for_all.hpp
- Adds `Array::front()`, `Array::back()` methods, and `Array::resize(size, value)` overload to more closely conform with `std::vector` API
- Adds `ArrayView::empty()` method to match `std::span`
- Makes `Array` move constructors noexcept
=> Various axom::Array changes

.gitlab/build_tioga.yml
This was originally turned on due to Tioga being updated and causing failures. This is not a safe thing to turn on long term and was forgotten.
=> Turn off allow failure on tioga

.gitlab-ci.yml
Without this the dedicated ci allocation won't work for retries through the UI.  We should move to this anyways.
=> Use service user for gitlab ci

src/axom/spin/internal/linear_bvh/bvh_traverse.hpp, src/axom/spin/policy/LinearBVH.hpp
Add documentations for public interfaces and mention that call-back functors should use memory available in their execution environment.
- This PR is a source-code documentation update
- Add documentation about the call-backs used in BVH tree traversals.
- State that the call-backs should only access memory available in the execution space of the traversal code.
The BVH code is factored to several files.  We've mentioned a similar requirement for data to initialize the BVH class.  But we lack similar documentations on the call-back functions used in the tree traverser class.
=> Document call-back functors for traversing BVH

src/axom/sidre/core/Array.hpp, src/axom/sidre/core/AttrValues.hpp, src/axom/sidre/core/View.hpp
- This PR adds documentation
- Add "\return" comments for `View` methods that look up `Attribute`s.
Attribute look-ups return nullptr and Attribute-setting methods are no-ops when there's no such `Attribute`.
The added comments are based on my reading of the code.
=> Document behavior when a non-existent Attribute is looked up.

host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.1.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.2_cuda.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@8.3.1.1.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@8.3.1.2_cuda.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1.1.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1.2_cuda.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.2_cuda.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@8.3.1.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@8.3.1.2_cuda.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1.2_cuda.cmake, scripts/spack/configs/blueos_3_ppc64le_ib_p9/compilers.yaml, scripts/spack/packages/axom/package.py, scripts/spack/packages/mfem/package.py, src/axom/core/ArrayBase.hpp
Updates the XL compilers to use the GCC 8.3.1 toolchain on blueos.
Also:
- modifies the Axom Spack package to pass through C++ compiler flags to the host compiler when using NVCC
- fixes an issue with the MFEM Spack package when C++ compiler flags are present in the compiler spec
=> Use libstdc++ 8 with XL compilers on blueos

.uberenv_config.json, host-configs/rzvernal-toss_4_x86_64_ib_cray-clang@14.0.0_hip.cmake, host-configs/tioga-toss_4_x86_64_ib_cray-clang@14.0.0_hip.cmake, scripts/spack/configs/toss_4_x86_64_ib_cray/compilers.yaml, scripts/spack/configs/toss_4_x86_64_ib_cray/packages.yaml, scripts/spack/packages/axom/package.py, scripts/spack/packages/raja/package.py
- This is a maintenance PR in support of a user request / bug report
- It resolves #971 
- It updates spack to the HEAD of its develop branch on 7Dec2022, which incorporates a bugfix for properly setting the `ROCM_PATH` relative to the provided `HIP_ROOT_DIR` (https://github.com/spack/spack/pull/33772)
- Spack diff: https://github.com/spack/spack/compare/bb1cd430c0d6f8bebfb655c65244a25bcc325d8d...ddc6e233c70273dd5dfd8dab31729eaf538693b8
- It updates our EAS3 compiler from `rocm@5.1.1` to `rocm@5.2.3`
=> Updates EAS3 compiler to `rocm@5.2.3`

RELEASE-NOTES.md, scripts/vcpkg_ports/axom/portfile.cmake, scripts/vcpkg_ports/axom/vcpkg.json, scripts/vcpkg_ports/camp/portfile.cmake, scripts/vcpkg_ports/camp/vcpkg.json, scripts/vcpkg_ports/raja/portfile.cmake, scripts/vcpkg_ports/raja/vcpkg.json, scripts/vcpkg_ports/umpire/portfile.cmake, scripts/vcpkg_ports/umpire/vcpkg.json, src/axom/inlet/tests/CMakeLists.txt, src/axom/quest/IntersectionShaper.hpp
- It adds `vcpkg` ports for `RAJA`, `Umpire` and `camp`
- I used the Umpire@2022.10 release since the 2022.03 release had problems with zero-sized allocations on Windows
- This also required updating our `fmt` version due to an incompatibility between the vendored copies of `fmt` in `axom` and `Umpire`. Specifically, the [strerror overloads in `fmt@7.1/format-inl.h`](https://github.com/LLNL/axom/blob/8da4ba2f8eec19b5b0cbd91857ae57c41b40a771/src/thirdparty/axom/fmt/format-inl.h#L30-L33) differed only in return type. These were removed in `fmt@9.1`
- It also adds an optional `OpenMP` feature to the Windows build
- These are all enabled by default
- This PR resolves #982
=> Adds support for RAJA and Umpire to Windows build

src/axom/quest/DistributedClosestPoint.hpp
@adayton hit the following:
```
ld.lld: error: duplicate symbol: axom::quest::format_as(axom::quest::DistributedClosestPointRuntimePolicy)
>>> defined at DistributedClosestPoint.hpp:65 (lib/toss3_intel.oneapi.2022/axom/include/axom/quest/DistributedClosestPoint.hpp:65)
>>>            CMakeFiles/dir/__/io/ReadStl.cc.o:(axom::quest::format_as(axom::quest::DistributedClosestPointRuntimePolicy))
>>> defined at DistributedClosestPoint.hpp:65 (lib/toss3_intel.oneapi.2022/axom/include/axom/quest/DistributedClosestPoint.hpp:65)
>>>            CMakeFiles/dir/__/shapegen/ShapeFileStl.cxx.o:(.text._ZN4axom5quest9format_asENS0_36DistributedClosestPointRuntimePolicyE+0x0)
```
=> Fix duplicate symbol when compiling with intel oneapi

RELEASE-NOTES.md, src/axom/core/ArrayView.hpp, src/axom/core/tests/core_array.hpp
The over-large size was allowing access of potentially invalid memory by the `ArrayView`.  This can happen in the object returned by `ArrayView::subspan`.
- Reduce the size of the new `ArrayView` by the offset amount, to make it NOT okay to access data past the end of the original view.
- Make the returned view consistent with the doxygen comments.
- Add unit test on the range of the created `ArrayView`.
I added the unit test because `subspan` isn't used anywhere in the library.  This change may affect application code that makes use of the buggy feature.  The change is indicated in the release notes.
=> Reduce size of ArrayView returned by `subspan`

.gitlab/build_tioga.yml
- This PR is an attempted workaround for the CI runner of LC's `tioga`
- LC advised explicitly pointing at the `tioga10` runner since something appears to be wrong with the `tioga11` runner.
=> Attempted workaround for temporarily faulty CI tioga runner

src/axom/core/CMakeLists.txt
- This PR is a workaround for a potential bug in blt
- When we specify that `core` depends on `RAJA` in `blt_add_library`, it should transitively depend on RAJA's dependencies. However, the `RAJA::roctx` dependency was not being properly propagated. The latter is present when RAJA is configured with `RAJA_ENABLE_ROCTX`.
- Since `core` is a CMake  `OBJECT` library, we're internally setting it up as a `blt_register_library`
- As a temporary workaround, this PR explicitly adds `RAJA::roctx` when available/needed
=> Bugfix for RAJA's optional RAJA::roctx dependency

RELEASE-NOTES.md, src/axom/primal/geometry/BoundingBox.hpp, src/axom/primal/geometry/Polygon.hpp, src/axom/primal/geometry/Polyhedron.hpp, src/axom/primal/operators/detail/intersect_impl.hpp, src/axom/primal/tests/primal_clip.cpp, src/axom/primal/tests/primal_intersect.cpp, src/axom/primal/tests/primal_intersect_impl.cpp, src/axom/primal/tests/primal_polygon.cpp, src/axom/primal/tests/primal_polyhedron.cpp, src/examples/using-with-blt/example.cpp, src/examples/using-with-cmake/example.cpp
- It improves the robustness of primal's `intersect` operators for bounding boxes against planes and triangles by first checking if the bounding box is valid before using its geometry.
- This PR also has some minor modernization in the implementation of `primal::intersect`, `primal::Polyhedron` and related unit tests
Credit: Thank you @liyangrock for bringing this bug to our attention in #1005 and for creating a reproducer!
=> Improves robustsness of intersection operators against bounding boxes

.readthedocs.yml, host-configs/tioga-toss_4_x86_64_ib_cray-clang@14.0.0_hip.cmake, src/conf.py
This PR:
- Fixes #1012  (404 Doxygen pages)
- Issue was related to filepath name changes on the ReadTheDocs end.
- [ReadTheDocs link ](https://axom.readthedocs.io/en/test-han12-doxytree/) to documentation generated by this PR.
- Reverts #1011
- Tioga has flux wrappers for SLURM commands so `srun` calls `flux mini run` underneath. Issue last week was flux wrappers not being initialized by default on the system after updates.
=> Fix doxygen on ReadTheDocs (+ return to srun for MPI tests on tioga)

.gitlab/build_tioga.yml
For several reasons, Tioga is too unstable right now. We have agreed as a team to allow these jobs to fail and monitor the situation manually.
=> Turn back on allow_failure for tioga jobs

RELEASE-NOTES.md, scripts/vcpkg_ports/axom/portfile.cmake, scripts/vcpkg_ports/axom/vcpkg.json, src/axom/quest/examples/CMakeLists.txt, src/axom/quest/tests/CMakeLists.txt, src/axom/sidre/tests/spio/spio_parallel.hpp, src/axom/sidre/tests/spio/spio_serial.hpp, src/cmake/thirdparty/FindLUA.cmake, src/cmake/thirdparty/SetupAxomThirdParty.cmake
- This PR contains several bugfixes
- It improves the constraints on axom's `mfem` dependency in its spack package
- It adds an optional `lua` dependency to the Windows build
- It improves the import logic for lua (this manifested in a local WSL build, where `-dl` was required and missing from our previous formulation)
- It also fixes some failing tests when axom is configured without `hdf5`. 
- An observed failure in the `spio_parallel` tests for this configuration will be resolved in
#1018
=> Bugfixes in support of Windows build

src/axom/primal/tests/primal_curved_polygon.cpp, src/axom/primal/tests/primal_orientedboundingbox.cpp, src/axom/spin/tests/spin_bvh.cpp, src/cmake/thirdparty/SetupAxomThirdParty.cmake
- This PR is a bugfix for importing a `caliper`-enabled `mfem` in a `cuda` configuration
- The former depends on `cupti` which was not being exported, leading to compiler errors
- As a hack, we patch mfem to depend on `CUDA::cupti`
- It also fixes some floating point comparisons in axom's unit tests
=> Bugfix for importing caliper-enabled mfem in cuda configs

RELEASE-NOTES.md, src/cmake/thirdparty/FindROCTracer.cmake, src/cmake/thirdparty/SetupAxomThirdParty.cmake
- This PR is a bugfix for importing a `caliper`-enabled `mfem` in `hip` configurations
- In this case, `caliper` depends on roctracer/roctx, but this is not properly exported by caliper or mfem
- This PR is a companion to #1025 which had a similar improvement for handling the implicit `cupti` dependency in `cuda` configs
Credit: Thanks @white238 for helping me set up and export the new `roctracer` target
=> Further improves import logic for caliper-enabled mfem target

.gitlab/build_lassen.yml, src/axom/spin/UniformGrid.hpp, src/axom/spin/policy/UniformGridStorage.hpp, src/axom/spin/tests/spin_uniform_grid.cpp
- Various memory fixes for `UniformGrid::initialize()`
- Allocate `binCounts` array with the user-provided allocatorID
- Remove dependence on implicit this-capture by using local variables
- Adds a test which exercises `UniformGrid`'s vector-based constructor
- Explicitly disable Address Translation Service in BlueOS CI
=> UniformGrid memory fixes

scripts/spack/configs/config.yaml, scripts/spack/devtools_configs/config.yaml
This should eliminate warnings from newer versions of Spack
=> Update config.yaml to modern spec.format syntax

src/axom/primal/tests/primal_orientedboundingbox.cpp, src/axom/spin/tests/spin_bvh.cpp, src/cmake/thirdparty/FindLUA.cmake
- This PR contains some bugfixes for previous bugfix PRs
- It improves the import logic for lua (https://github.com/LLNL/axom/pull/1017)
- CMake's `string(FIND )` returns an index, not a boolean
- It improves some floating point tests (https://github.com/LLNL/axom/pull/1025)
- We need to use `EXPECT_NEAR` with a provided tolerance rather than `EXPECT_DOUBLE_EQ`
- I also slightly cleaned up the code in the test files
=> Bugfixes for bugfixes

RELEASE-NOTES.md, src/axom/core/ArrayBase.hpp, src/axom/quest/DistributedClosestPoint.hpp, src/axom/quest/PointInCell.hpp, src/axom/quest/detail/PointInCellMeshWrapper_mfem.hpp, src/axom/quest/examples/point_in_cell_benchmark.cpp, src/axom/sidre/core/MFEMSidreDataCollection.cpp, src/axom/sidre/examples/spio/IO_SCR_Checkpoint.cpp
- It exposes some additional parameters to control the initial guess and solver projection strategy for the per-element `InverseElementTransformation` within quest's `PointInCell` query
- It also exposes those parameters in the `point_in_cell_benchmark` example, and refactors that example
- Resolves #1038 
- Minor: It also fixes some warnings in Release builds
Using the new parameters exposed in the point_in_cell benchmark example, I ran some experiments on the 336 element cubic mesh from #1038, varying the "projection type" (i.e. what to do when the query leaves the element's reference space), as well as its "guess type" and "guess order", which relate to initializing the query.
Each result was for 1,000,000 query points and is the average of three runs. The goal …
=> Improves user control of `PointInCell` query

src/axom/sidre/core/Buffer.cpp, src/axom/sidre/core/Buffer.hpp, src/axom/sidre/core/Group.cpp, src/axom/sidre/core/Group.hpp, src/axom/sidre/core/View.cpp, src/axom/sidre/core/View.hpp, src/axom/sidre/docs/sphinx/file_io.rst, src/axom/sidre/tests/sidre_group.cpp
- Adds new protocols "sidre_layout_json" and "conduit_layout_json" to provide output of the DataStore layout in a user-readable format that excludes the numerical arrays held by Views and Buffers.
- Addresses #765 ;  See my comment https://github.com/LLNL/axom/issues/765#issuecomment-1444841842 describing my approach.
WIP until I add Sphinx documentation of the new protocols.
=> Add new sidre Group output protocols for metadata

src/axom/slic/CMakeLists.txt
- This PR is a portability bugfix.
- Adds a link library to slic on FreeBSD hosts.  On Linux, `backtrace()` and `backtrace_symbols()` come from glibc.  On FreeBSD, those functions come from libexecinfo.
=> Add a library required by FreeBSD

.gitlab-ci.yml, .gitlab/build_quartz.yml, scripts/llnl_scripts/build_src.py, scripts/llnl_scripts/llnl_lc_build_tools.py
This PR:
- Targets pdebug queue for quartz. pbatch is rather popular.
- Fixes quartz not re-using `salloc` allocation
- `build_src.py` script now prints the name of the running node (hostname) for easier debugging in the future (Thanks @white238 for the suggestion!)
=> Use pdebug queue for quartz allocation

src/axom/slic/interface/slic_macros.hpp
This PR:
- Makes a small reversion to PR #1079 to get intersection shaper unit tests running on rzvernal and tioga.
-  NOTE: This reintroduces the HIP-related unused variable warnings that were previously ignored by `SLIC_ASSERT`
Closes  #1089
=> Change to fix intersection shaper unit tests with HIP

src/axom/CMakeLists.txt, src/axom/multimat/examples/calculate_gpu.cpp, src/axom/multimat/examples/helper.hpp, src/axom/multimat/examples/traversal.cpp, src/axom/multimat/multimat.cpp, src/cmake/axom-config.cmake.in, src/examples/using-with-cmake/CMakeLists.txt
- This PR is a bugfix for some errors in axom's installation
- It installs the new export headers
- It makes the `axom` target depend on all axom components, not just the last one (using `APPEND`)
- It fixes a bug in the `using-with-cmake` example for configs that depend on mpi
- It fixes some warnings in multimat
=> Some bugfixes for axom's installation

RELEASE-NOTES.md, src/axom/quest/IntersectionShaper.hpp, src/axom/quest/SamplingShaper.hpp, src/axom/quest/Shaper.cpp, src/axom/quest/detail/shaping/shaping_helpers.cpp, src/axom/quest/detail/shaping/shaping_helpers.hpp, src/axom/quest/examples/shaping_driver.cpp, src/axom/sidre/core/MFEMSidreDataCollection.cpp, src/thirdparty/tests/umpire_smoke.cpp
- It enables importing existing volume fractions into quest's sample-based shaping query
- The klee-based shapes are then painted on top of these.
- Resolves #1040
- Adds a `--background-material` command line argument to the shaping example to exercise this capability
- Misc: Also reduces default verbosity of shaping query
- Misc: umpire smoke test now prints out version and available allocators
* The default run of the ["circles" problem](https://github.com/LLNL/axom_data/blob/main/shaping/circles.yaml) has two materials defined by nested circles/spheres: `steel` and `void`:  
`> ./examples/quest_shaping_driver_ex -m box_2d.root -i ../data/shaping/circles.yaml `
("steel" on left; "void" on right)
* If we set the background material to `"background"`, we get a …
=> Import existing volume fractions into sampling shaper

.gitignore, src/axom/primal/CMakeLists.txt, src/axom/primal/geometry/BezierCurve.hpp, src/axom/primal/geometry/BezierPatch.hpp, src/axom/primal/tests/CMakeLists.txt, src/axom/primal/tests/primal_bezier_patch.cpp
- Adds a `BezierPatch` class that implements a (possibly rational) tensor product Bezier surface. Methods for `BezierPatch` follow conventions of `BezierCurve`, with most having an additional `axis` parameter.
- Adds a number of tests for the above `BezierPatch` class
- Adds a Visual Studio configuration folder `.vs/` to the `.gitignore`
=> Add BezierPatch class to primal/geometry

RELEASE-NOTES.md, src/axom/mint/mesh/ConnectivityArray.hpp, src/axom/sidre/core/Array.hpp
- Multiplies the tuple size (nodes per cell) with the number of tuples (cells) to get the capacity.  The number of tuples had been omitted.
- Add this change to the `RELEASE-NOTES.md` file.
- Updates some outdated doxygen comments.
The errors caused this behavior.  You want a capacity for N cells.  You get N/2 in 2D and N/3 in 3D.
The capacity set by the constructors are now correct and consistent with the capacity set using the `reserve` method.
There was probably some confusion because capacity meant different things to high-level `ConnectivityArray` vs low-level `Array` containers.  The `ConnectivityArray` only looks at the first dimension, because it considers the second dimension to be fixed even as the container grows.  `Array` looks at …
=> Fix `ConnectivityArray` setting bad capacity in constructor.

RELEASE-NOTES.md, src/axom/multimat/CMakeLists.txt, src/axom/multimat/multimat.cpp, src/axom/multimat/multimat.hpp, src/axom/multimat/tests/multimat_test.cpp, src/axom/slam/RelationSet.hpp, src/axom/slam/policies/CardinalityPolicies.hpp
- Moves `RelationSet::flatToFirstIndex()` logic into CardinalityPolicy
- Adds a `MappedVariableCardinality` policy which holds an extra indirection buffer for mapping flat relation offsets to the first set index
- This allows for constant-time `flatToFirstIndex()` lookups for variable cardinality, at the cost of extra space
- Use `MappedVariableCardinality` for static relations to accelerate transposition operations
- Ports transposition of field data between cell-dominant/material-dominant and sparse/dense layouts
- Ports `MultiMat::makeOtherRelation()` to GPU
- Ports `MultiMat::setCellMatRel(counts, indices)` overload to GPU
- `counts` and `indices` must be in GPU-accessible space if `slamAllocatorID` is a GPU-accessible allocator
=> Multimat: GPU porting and acceleration

RELEASE-NOTES.md, src/axom/core/Array.hpp, src/axom/core/tests/core_array.hpp
- Fixes an ambiguous call to `Array::resize()` for `axom::Array`s of type `bool`.
The underlying problem was a protected overload of `resize()` used by the public-facing resize methods; we just rename this to `resizeImpl()` to avoid the ambiguity.
Resolves #1082.
=> Fix instantiation of Array::resize

RELEASE-NOTES.md, src/axom/core/Array.hpp, src/axom/core/ArrayBase.hpp, src/axom/core/ArrayView.hpp, src/axom/core/tests/CMakeLists.txt, src/axom/core/tests/core_array.hpp, src/axom/core/tests/core_serial_main.cpp, src/axom/core/tests/core_utilities.hpp, src/axom/core/utilities/Utilities.hpp
- Adds `ArrayView` constructor with user-defined striding parameter
- User-defined strides can include column-major or arbitrary striding
- Adds `ArrayView::subspan()` overload for multi-dimensional ArrayViews
- Moves spacing field into `ArrayBase::m_strides`
=> ArrayView: multi-dim subspans, non-row-major striding

RELEASE-NOTES.md, src/axom/klee/Geometry.hpp, src/axom/klee/IO.cpp, src/axom/klee/tests/klee_geometry.cpp, src/axom/klee/tests/klee_io.cpp, src/axom/multimat/multimat.cpp, src/axom/primal/operators/winding_number.hpp, src/axom/primal/tests/primal_bezier_patch.cpp, src/axom/primal/tests/primal_solid_angle.cpp, src/axom/quest/SamplingShaper.hpp, src/axom/quest/Shaper.cpp, src/axom/quest/detail/shaping/shaping_helpers.cpp, src/axom/quest/detail/shaping/shaping_helpers.hpp, src/axom/quest/examples/shaping_driver.cpp, src/axom/quest/tests/CMakeLists.txt, src/axom/quest/tests/quest_sampling_shaper.cpp
- This PR is a feature related to quest's shaping application of klee input decks
- It allows "preshaped" materials (e.g. where the volume fractions are generated prior to invoking axom's shaping pipeline) to participate in replacement rules.
- It adds support in Klee for a shape to have no geometric data. This is specified with `geometry/format: none`. If so, it will not have a `geometry/path` entry.
- It also adds unit tests for quest's `SamplingShaper` class
- Resolves #1104 
- Update klee/shaping files in `axom_data` repo, as necessary
_Update:_ I'll update the `axom_data` repo in a follow-up PR since it will involve non-trivial changes to the shaping example
=> Support replacement rules for preshaped geometry

RELEASE-NOTES.md, src/axom/core/tests/core_array.hpp, src/axom/klee/tests/KleeMatchers.hpp, src/axom/klee/tests/klee_geometry_operators.cpp, src/axom/klee/tests/klee_geometry_operators_io.cpp, src/axom/klee/tests/klee_io_util.cpp, src/axom/primal/operators/detail/winding_number_impl.hpp, src/axom/primal/tests/primal_polygon.cpp, src/axom/primal/tests/primal_polyhedron.cpp, src/axom/quest/tests/quest_signed_distance_interface.cpp
- This PR is maintenance and bugfixes
- It updates the blt submodule to `blt@0.5.3`, which updates the gtest and gmock version
- It fixes a compilation error in the `axom::Array` unit tests -- the templated type requires an `operator<<()` overload and was missing for a type defined in the tests.
- It also removes some utility functions in the above test from the `axom` namespace
- It also fixes a build error w/ MSVC that has cropped up before. When using defines like `M_PI` from `math.h`, we either have to make sure that we load `<cmath>` after defining `_USE_MATH_DEFINES`, or include `math.h` instead due to a guard in msvc's cmath that prevents it from being loaded a second time. (See also: https://github.com/search?q=repo%3ALLNL%2Faxom+cmath&type=commits)
- It also fixes a compilation …
=> Updates and bugfixes for blt@0.5.3

host-configs/rzvernal-toss_4_x86_64_ib_cray-clang@14.0.0_hip.cmake, host-configs/tioga-toss_4_x86_64_ib_cray-clang@14.0.0_hip.cmake
This PR:
- Changes unit tests to use srun flux wrapper instead of slurm srun.
This change will require modifying the spack recipe for axom to make it automated and not manual, which can be done in a follow-up PR (#1122 will modify the spack recipe)
=> Use srun flux wrapper path for toss 4 cray machines

src/axom/primal/geometry/Sphere.hpp, src/axom/quest/MarchingCubes.cpp, src/axom/quest/MarchingCubes.hpp, src/axom/quest/detail/MarchingCubesImpl.hpp, src/axom/quest/examples/CMakeLists.txt, src/axom/quest/examples/quest_marching_cubes_example.cpp
- Fix a loop that was parallelized but is not data-parallel so should not have been.
- Fix a test rule that allowed this bug to slip through
- Fix the marching cubes test code so that it puts mesh data on the GPU.
- Fix `MarchingCubesImpl` where it was unintentionally trying to use host data on the GPU.
I added template parameter `SequentialLoopPolicy` for use with loops that should not be parallelized.  An unconventional RAJA construct is used to run loops sequentially.
There was some systemic problem running on GPUs, problems that was hidden by the automatic address translation services.  One of the needed changes was to factor out some functionalities into smaller classes whose light-weight objects can be …
=> Fix marching cubes loops on GPUs

src/axom/slic/streams/LumberjackStream.cpp, src/axom/slic/streams/SynchronizedStream.cpp
This PR:
- Adds missing ostream call to `flush()` for parallel LogStreams (LumberjackStream and SynchronizedStream)
Related to #1140
=> Flush parallel logStreams

src/axom/core/tests/CMakeLists.txt, src/axom/quest/detail/Discretize_detail.hpp, src/axom/quest/detail/MeshTester_detail.hpp, src/tools/CMakeLists.txt
This PR:
- Fixes failing `mesh_tester` executable
- Bug was introduced by a change made in PR #1111 ([link to exact buggy commit](https://github.com/LLNL/axom/pull/1111/commits/d340e93be55a314853a6609c47b0b16cf21a20c9))
- Adds tests for `mesh_tester` for the different spatial indexes and RAJA policies.
- Re-enable `core_openmp_map` unit test.
- `AXOM_USE_RAJA` was used of instead of `RAJA_FOUND` to guard test inclusion.
=> Fix mesh tester example and add tests

src/axom/sidre/core/MFEMSidreDataCollection.cpp
This short PR fixes two bugs when reading an `mfem::GridFunction` from an `MFEMSidreDataCollection`.
1) It constructs a new `mfem::FiniteElementSpace` when the vdim is different from what is currently stored in Sidre.
2) It correctly determines whether the stored grid function is ordered by nodes or VDIM.
=> Fix `MFEMSidreDataCollection` finite element space bug

src/cmake/axom-config.cmake.in
- This PR is a bugfix to the CMake target.  It defines a variable to allow us to refer to files with relative paths.
=> Fill _IMPORT_ROOT in the CMake target.

src/cmake/CMakeBasics.cmake
- This PR is a minor bugfix for the build system
- It ensures that several defined `ENV` variables are not empty before appending them to a list
- These were causing config failures for axom on a `toss4` system in a user application
=> Ensure several `ENV` variables are not empty before appending them to a list

RELEASE-NOTES.md, src/axom/quest/DistributedClosestPoint.hpp, src/axom/quest/MarchingCubes.cpp, src/axom/quest/MarchingCubes.hpp, src/axom/quest/examples/quest_distributed_distance_query_example.cpp, src/axom/quest/examples/quest_marching_cubes_example.cpp
The Blueprint coordset name is specified in the topology group, but I had been assuming a coordset name when I wrote the code (because I didn't know it could be different).  The assumed name may not necessarily match the topology-specified name.  This PR removes the assumption.
A topology specifies one coordset, and a coordset may be used by many topologies.
This change is needed by concurrent work, where we have to access both the topology and its coordset.  By specifying the topology, we have both.  If we specify coordset, we can't get to the topology.
- This PR is a refactoring.
- Modifies the `DistributedClosestPoint` and `MarchingCubes` classes so that they use the Blueprint coordset name specified by the topology.
- Changes a few public interfaces that were …
=> Use Blueprint-specified coordset name, instead of assuming one

src/axom/sidre/core/Group.cpp, src/axom/sidre/core/Group.hpp, src/axom/sidre/core/View.cpp, src/axom/sidre/core/View.hpp, src/axom/sidre/tests/sidre_group.cpp
- Adds deep copy methods for Group and View
- Addresses #769 
The actual deep copy of buffer data occurs on the Views, with the deep copy of a Group copying the entire hierarchy with deep copies of all Views.
All deep copies of Views with Buffer or external data are copied into a new sidre Buffer attached to the new View.  If the source View's description sees only a part of its Buffer or external array due to offsets or strides, only the elements that are seen by the description will be copied, and the Buffer for the new View will be sized to receive the exact number of elements that are copied.
=> Add deep copy methods for Group and View

RELEASE-NOTES.md, src/axom/quest/SamplingShaper.hpp, src/axom/quest/detail/shaping/shaping_helpers.cpp, src/axom/quest/tests/quest_sampling_shaper.cpp
- This PR is a proof of concept that we can use `stl` meshes and `c2c` contours in the same shaping deck for sample-based shaping
- Resolve #1135 
- It also has some minor bugfixes/maintenance:
- Resolves #1143  -- we can now have materials with underscores in the name, e.g. `a_material_name`
- Changes the logging level of a log message related to replacement rules from `DEBUG` to `INFO`, since it can be useful to check that replacement rules act as expected, even from release builds.
- Refactor/clean up a debugging function in the `SamplingShaper`
- Improves testing for sample-based shaping
=> Checks that we can use both `c2c` and `stl` in the same sample-based shaping deck

RELEASE-NOTES.md, src/axom/primal/CMakeLists.txt, src/axom/primal/docs/sphinx/primitive.rst, src/axom/primal/geometry/BoundingBox.hpp, src/axom/primal/geometry/Quadrilateral.hpp, src/axom/primal/operators/compute_bounding_box.hpp, src/axom/primal/tests/CMakeLists.txt, src/axom/primal/tests/primal_boundingbox.cpp, src/axom/primal/tests/primal_compute_bounding_box.cpp, src/axom/primal/tests/primal_quadrilateral.cpp, src/axom/spin/tests/spin_bvh.cpp
- Adds Quadrilateral primitive
- Adds BoundingBox constructor that takes an initializer list
- Adds compute_bounding_box operator for Quadrilateral
=> Adds a Quadrilateral primitive

host-configs/quartz-toss_4_x86_64_ib-clang@14.0.6.cmake, host-configs/quartz-toss_4_x86_64_ib-gcc@10.3.1.cmake, host-configs/quartz-toss_4_x86_64_ib-intel@2022.1.0.cmake, host-configs/rzgenie-toss_4_x86_64_ib-clang@14.0.6.cmake, host-configs/rzgenie-toss_4_x86_64_ib-gcc@10.3.1.cmake, host-configs/rzgenie-toss_4_x86_64_ib-intel@2022.1.0.cmake, host-configs/rzwhippet-toss_4_x86_64_ib-clang@14.0.6.cmake, host-configs/rzwhippet-toss_4_x86_64_ib-gcc@10.3.1.cmake, host-configs/rzwhippet-toss_4_x86_64_ib-intel@2022.1.0.cmake, scripts/llnl_scripts/build_devtools.py, scripts/spack/specs.json, src/cmake/thirdparty/SetupAxomThirdParty.cmake
This PR:
- Adds back +scr to some toss4 configs (previous scr built only with some toss3 configs)
- ~~Edits `build_devtools` script to allow non-atk users to build to shared directory~~
=> Build configs with +scr

src/axom/CMakeLists.txt, src/cmake/axom-config.cmake.in
- Creates the targets, `axom` and the namespaced component targets, for projects that include us as a submodule
- Strips all created targets in our exported config logic of non-existant include directories. This produces errors if they creep in, which keeps happening, and stops it from happening from us.
=> Various clean-up for downstream projects

.gitlab/build_lassen.yml, .gitlab/build_quartz.yml, .gitlab/build_tioga.yml
Move all CI to `atk` and move to the `wdev` bank on Lassen.
The `LLNL_SERVICE_USER` variable was already in `.gitlab-ci.yml`, so I just had to turn on the Gitlab setting to allow us to use the service user.
=> Move to service user and new bank on lassen

RELEASE-NOTES.md, src/axom/primal/operators/clip.hpp, src/axom/primal/operators/detail/clip_impl.hpp, src/axom/primal/tests/primal_clip.cpp
- Adds a clip operator for a tet and plane
- Refactors internal code for clipping a polyhedron by a set of planes
=> Add clip operator for a tet and plane

RELEASE-NOTES.md, src/axom/primal/examples/hex_tet_volume.cpp, src/axom/primal/geometry/Polyhedron.hpp, src/axom/primal/geometry/Tetrahedron.hpp, src/axom/primal/operators/clip.hpp, src/axom/primal/operators/detail/clip_impl.hpp, src/axom/primal/operators/intersection_volume.hpp, src/axom/primal/tests/primal_clip.cpp, src/axom/primal/tests/primal_hexahedron.cpp, src/axom/primal/tests/primal_tetrahedron.cpp, src/axom/quest/IntersectionShaper.hpp
This PR:
- Adds a `checkAndFixOrientation()` function to the `Tetrahedron` class that swaps vertex order if the signed volume is negative to get a positive volume.
- Adds detail to the `checkSign` flag documentation
- Adjusts unit test for `triangulate()` function of the `Hexahedron` class to check total _signed_ volume of the tetrahedron subvolumes.
Addresses #1206
=> Intersection-based Primal improvements

src/axom/quest/tests/quest_mesh_view_util.cpp
- This PR is a bug fix
- Disables MPIinit, which mysteriously crashes the `MeshViewUtil` class test.
- Disable conduit validity test that relied on MPI.
Test crashed for quartz CI.  Not reproducible when run in shell.  Don't know why.  The disabled test wasn't too important--just a sanity check.
=> Fix MeshViewUtil test failure

src/axom/core/utilities/System.cpp
Some systems throw an error on `std::locale("")` if there is no user-defined locale. 
Use `std::locale("C")` instead. 
* We originally encountered this inside a docker image.
* A user reported the problem w/ axom@0.8.1
* Cherry-picked commit from https://github.com/LLNL/axom/pull/1171
=> Bugfix for `axom::utilities::locale`

src/axom/core/Array.hpp, src/axom/core/ArrayBase.hpp, src/axom/core/tests/core_array.hpp
A type is considered "trivially relocatable" if a bitcopy of the object can be treated as a "move-and-destroy" of the original object. Types which are not trivially-relocatable need to call the move or copy constructor in order to correctly construct the destination object.
This is usually the case when a type maintains a pointer/reference to itself; one example of a common type which is not trivially-relocatable is `std::string` in the GCC STL (more examples [here](https://quuxplusone.github.io/blog/2019/02/20/p1144-what-types-are-relocatable/))
This PR improves the handling of these non-trivially relocatable types in `axom::Array`, by ensuring that the move/copy constructor is called on non-trivially copyable types when reallocating the underlying memory.
=> Fix axom::Array reallocation for non-trivially relocatable types

RELEASE-NOTES.md, src/axom/quest/DistributedClosestPoint.hpp, src/axom/quest/MeshViewUtil.hpp, src/axom/quest/examples/quest_distributed_distance_query_example.cpp
If not provided, use local domain's iteration index. Fix error setting domain.
- Modifies `DistributedClosestPoint` to use the blueprint `state/domain_id` field to identify mesh domain, if the field is given.
- Fixes https://github.com/LLNL/axom/issues/1197
- Documents this change in the release notes.
Issue https://github.com/LLNL/axom/issues/1197 also requires the same change in `MarchingCubes`, and that change occurred in a separate, merged PR.
This PR and related comments led to issue https://github.com/LLNL/axom/issues/1236, on being bit width compatibility of blueprint data.
=> Use domain_id for identification if provided in DistributedClosestPoint.

RELEASE-NOTES.md, src/axom/core/CMakeLists.txt, src/axom/core/FlatMap.hpp, src/axom/core/detail/FlatTable.hpp, src/axom/core/tests/CMakeLists.txt, src/axom/core/tests/core_flatmap.hpp, src/axom/core/tests/core_serial_main.cpp
Adds `axom::FlatMap`, an initial implementation of a hash map container as a mostly drop-in replacement for `std::unordered_map`. The eventual goal is to enable the use of hash maps on the GPU.
FlatMap is largely based on Boost's `unordered_flat_map` design, described [here](https://bannalia.blogspot.com/2022/11/inside-boostunorderedflatmap.html). Pertinent design points are:
- Open-addressing as opposed to `std::unordered_map`'s closed-addressing model.
- Non-relocating quadratic probing to resolve hash collisions.
- The hash map is split into groups of 15 "buckets":
- Each group is represented by a 128-bit chunk of metadata, consisting of an "overflow" byte and one byte for each bucket in the group.
- The "overflow" byte is used as a Bloom filter to test if the next group should be …
=> Add a FlatMap container

.gitlab/build_lassen.yml, .gitlab/build_quartz.yml, .gitlab/build_tioga.yml
* Moves us to the new CI queue: https://lc.llnl.gov/confluence/display/GITLAB/Special+partitions+for+CI+batch+jobs
* Moves away from deprecated `flux mini` command
=> Use new CI queue

RELEASE-NOTES.md, src/axom/core/numerics/Matrix.hpp, src/axom/primal/geometry/Polygon.hpp, src/axom/primal/tests/primal_polygon.cpp
- This PR is a fork from #1232 to allow for internal testing
- It also improves our testing of Polygon area computations. We now test against scaled, rotated and translated Polygons in 2D and 3D. Resolves #1240
=> Pr from fork/1232

src/axom/primal/geometry/Polygon.hpp, src/axom/primal/tests/primal_polygon.cpp
- Fixes the area computation for planar 3d polygons that are not parallel to the xy-plane
=> Enable area computation for planar polygons with arbitrary orientation

.uberenv_config.json, RELEASE-NOTES.md, src/axom/quest/tests/quest_point_in_cell_mfem.cpp
- This PR is a feature.
- Modifies/refactors test quest_point_in_cell_mfem to print out the size of the test.
- Fixes #1222 
- Updates vcpkg to the current state of their master branch, fixing a problem with downloading a now-missing TPL of vcpkg
On 18 Dec 2023, we reviewed the issue linked, which is that the quest_point_in_cell_mfem test takes much longer when running release than debug.  @kennyweiss pointed out that the release build tests 10x more points and twice as many refinement steps than the debug build.  That explained the difference in runtime.   The message in this PR is an attempt to alert future developers to the different problem size between debug and release.
=> Log an explanatory message for quest_point_in_cell_mfem

RELEASE-NOTES.md, src/axom/mint/mesh/StructuredMesh.cpp, src/axom/multimat/examples/traversal.cpp, src/axom/multimat/multimat.hpp, src/axom/primal/CMakeLists.txt, src/axom/primal/geometry/BoundingBox.hpp, src/axom/primal/geometry/OrientedBoundingBox.hpp, src/axom/primal/geometry/Ray.hpp, src/axom/primal/operators/clip.hpp, src/axom/primal/operators/compute_bounding_box.hpp, src/axom/primal/operators/detail/clip_impl.hpp, src/axom/primal/operators/detail/fuzzy_comparators.hpp, src/axom/primal/operators/detail/intersect_impl.hpp, src/axom/primal/tests/primal_bezier_patch.cpp, src/axom/primal/tests/primal_boundingbox.cpp, src/axom/primal/tests/primal_clip.cpp, src/axom/primal/tests/primal_compute_bounding_box.cpp, src/axom/primal/tests/primal_orientedboundingbox.cpp, src/axom/primal/tests/primal_tetrahedron.cpp, src/axom/quest/InOutOctree.hpp, src/axom/quest/detail/inout/BlockData.hpp, src/axom/quest/detail/inout/MeshWrapper.hpp, src/axom/quest/tests/quest_regression.cpp, src/axom/spin/OctreeBase.hpp
- This PR is a bugfix for `primal::clip(Triangle, BoundingBox)` 
- the core bugfix is from @simonradler in #1239 
- placed in a new branch for internal testing
- This branch extends the original bugfix with some additional tests and code cleanup including:
- modified the behavior of `BoundingBox::contains(BoundingBox)` to return true when the latter is empty 
- added an overload to `primal::compute_bounding_box` for `primal::Polygon`
- fixed some minor warnings
=> Bugfix for primal's clip(triangle,bbox)

RELEASE-NOTES.md, src/axom/sidre/core/AttrValues.cpp, src/axom/sidre/core/AttrValues.hpp, src/axom/sidre/core/DataStore.cpp, src/axom/sidre/core/DataStore.hpp, src/axom/sidre/tests/sidre_attribute.cpp
- It allows loading a group with attributes into a datastore that already has that attribute
- When loading, only create the attribute if it doesn't already exist, but use the default value from the file
- Includes some minor code cleanup
- Fixes https://github.com/LLNL/axom/issues/67
=> Bugfix when loading group with attributes

src/cmake/thirdparty/SetupAxomThirdParty.cmake
This happened in another repo and I can't imagine this happening here, but you can't call install on a non-real target.
=> Guard install

host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.1.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.2_cuda.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@8.3.1.1.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@8.3.1.2_cuda.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1.1.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1.2_cuda.cmake, host-configs/quartz-toss_4_x86_64_ib-clang@14.0.6.cmake, host-configs/quartz-toss_4_x86_64_ib-gcc@10.3.1.cmake, host-configs/quartz-toss_4_x86_64_ib-intel@2022.1.0.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.2_cuda.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@8.3.1.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@8.3.1.2_cuda.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1.2_cuda.cmake, host-configs/rzgenie-toss_4_x86_64_ib-clang@14.0.6.cmake, host-configs/rzgenie-toss_4_x86_64_ib-gcc@10.3.1.cmake, host-configs/rzgenie-toss_4_x86_64_ib-intel@2022.1.0.cmake, host-configs/rzwhippet-toss_4_x86_64_ib-clang@14.0.6.cmake, host-configs/rzwhippet-toss_4_x86_64_ib-gcc@10.3.1.cmake, host-configs/rzwhippet-toss_4_x86_64_ib-intel@2022.1.0.cmake, scripts/spack/configs/blueos_3_ppc64le_ib_p9/spack.yaml, scripts/spack/configs/toss_4_x86_64_ib/spack.yaml, scripts/spack/configs/toss_4_x86_64_ib_cray/spack.yaml, scripts/spack/devtools_configs/toss_4_x86_64_ib/spack.yaml, scripts/spack/packages/py-shroud/package.py
- This PR is a devtool update
- Part of #1258
- Removes Shroud as part of the `build_devtools.py` scripts. Instead it uses a version installed at `/collab/usr/gapps/shroud/public/$SYS_TYPE`.
- Changes the host-configs files to use this version.
- Adds `py-shroud/package.py` file. This should be upstreamed into spack.
A future PR will regenerate the Fortran and C wrappers using this version.
The current hash of spack used in `scripts/spack/devtools.json` only supplies 0.12.1, while we were requesting 0.12.2.
=> Feature/taylor/shroud 0.13.0

src/axom/lumberjack/CMakeLists.txt, src/axom/lumberjack/Lumberjack.cpp, src/axom/lumberjack/Lumberjack.hpp, src/axom/lumberjack/TextEqualityCombiner.hpp, src/axom/lumberjack/TextTagCombiner.hpp, src/axom/lumberjack/docs/sphinx/combiner_class.rst, src/axom/lumberjack/docs/sphinx/core_concepts.rst, src/axom/lumberjack/docs/sphinx/lumberjack_classes.rst, src/axom/lumberjack/tests/CMakeLists.txt, src/axom/lumberjack/tests/lumberjack_TextTagCombiner.hpp, src/axom/lumberjack/tests/lumberjack_serial_main.cpp, src/axom/slic/core/LogStream.hpp, src/axom/slic/core/Logger.cpp, src/axom/slic/core/Logger.hpp, src/axom/slic/docs/sphinx/sections/appendix.rst, src/axom/slic/docs/sphinx/sections/getting_started.rst, src/axom/slic/examples/basic/logging.cpp, src/axom/slic/interface/slic.cpp, src/axom/slic/interface/slic.hpp, src/axom/slic/interface/slic_macros.hpp, src/axom/slic/streams/GenericOutputStream.cpp, src/axom/slic/streams/GenericOutputStream.hpp, src/axom/slic/streams/LumberjackStream.cpp, src/axom/slic/streams/LumberjackStream.hpp, src/axom/slic/streams/SynchronizedStream.cpp, src/axom/slic/streams/SynchronizedStream.hpp, src/axom/slic/tests/slic_macros.cpp, src/axom/slic/tests/slic_macros_parallel.cpp, src/axom/slic/tests/slic_uninit.cpp
This PR
- Adds the ability to create user-defined tags for tagged streams and messages.
- Tagged streams only receive messages with the corresponding tag.
- Adds a `TextTagCombiner` Combiner for Lumberjack that combines messages based on message and tag content.
ReadTheDocs link for this branch: https://axom.readthedocs.io/en/feature-han12-slic_tags/axom/slic/docs/sphinx/sections/getting_started.html#step-5-1-tagged-log-streams
=> Slic tags for streams and messages

src/axom/quest/examples/quest_inout_interface.F, src/axom/quest/interface/inout.cpp, src/axom/quest/interface/inout.hpp
- This PR is a bugfix for intermittent failure in our gcc@11 CI `quest_inout_interface` Fortran test
- It only calls the `finalize()` function for the dimension (2 or 3) that was initialized
=> Bugfix for intermittent failure of quest_inout_interface Fortran example

RELEASE-NOTES.md, src/axom/core/FlatMap.hpp, src/axom/core/tests/CMakeLists.txt, src/axom/core/tests/core_bit_utilities.hpp, src/axom/core/tests/utils_endianness.hpp, src/axom/core/utilities/BitUtilities.hpp, src/axom/core/utilities/Utilities.hpp, src/axom/lumberjack/TextTagCombiner.hpp, src/axom/lumberjack/tests/lumberjack_TextTagCombiner.hpp, src/axom/quest/examples/quest_proe_bbox.cpp, src/axom/quest/readers/STLReader.cpp, src/axom/slam/BitSet.cpp, src/axom/spin/ImplicitGrid.hpp, src/axom/spin/internal/linear_bvh/build_radix_tree.hpp
- This is a maintenance PR
- It renames several functions in the `axom::utilities` namespace that have recently been added to the `c++20` and `c++23` standards
- Specifically
- `popCount() -> popcount()`
- `trailingZeros() -> countr_zero()` 
- `leadingZeros() -> countl_zero()`
- `swapEndian() -> byteswap()`
- Resolves #762
=> Renames some bit/byte operations to match newer C++ standards

.gitlab/build_rzansel.yml, src/examples/using-with-cmake/CMakeLists.txt
This PR:
- Bumps up the `cmake_minimum_required` version for the using-with-cmake examples.
=> using-with-cmake example cmake version 

src/axom/core/Array.hpp, src/axom/core/tests/core_array_for_all.hpp
A user is seeing an issue with a "missing `__ppc_trap()` symbol" link error when using Clang 16 + CUDA 11.2. Replace this with `assert(false)`, which should serve a similar purpose in a debug build.
=> Fix a link issue with Clang 16 + CUDA

src/axom/core/CMakeLists.txt, src/axom/core/utilities/Annotations.cpp, src/axom/core/utilities/Annotations.hpp, src/axom/core/utilities/CommandLineUtilities.hpp, src/axom/quest/examples/CMakeLists.txt, src/axom/quest/examples/containment_driver.cpp, src/axom/quest/examples/quest_marching_cubes_example.cpp, src/axom/quest/examples/shaping_driver.cpp
- This PR is a feature/enhancement
- It improves our usage of `caliper` and `adiak` in the annotations API based on an offline code review of #1312 from @daboehme (Thanks!)
- Fixes #1314 by adding a custom CLI Validator for caliper modes
- Fixes #1315 by using a caliper function call that uses the `name` passed to `axom::utility::annotations::end(name)`
=> Improvements to annotations API

src/axom/slam/Map.hpp, src/axom/slam/SubMap.hpp, src/axom/spin/OctreeLevel.hpp
- This PR bugfix.
- Fixes #1244 (reported from a build of serac, also showing up in another host code build)
- Fixes #1320 (showed up when I tried to start working on 1244).  As @publixsubfan noted, this issue may come from a mismatch between `axom::IndexType` and whatever `IndexType` is visible from within slam.
=> Do not inherit from std::iterator

src/axom/primal/operators/closest_point.hpp, src/axom/primal/operators/squared_distance.hpp, src/axom/primal/tests/primal_closest_point.cpp
- This PR is a refactoring and bugfix
- Removes ambiguous overload of closest_point to Segment operator
- Updates default tolerance for closest_point to Segment operator (1e-12 -> PRIMAL_TINY = 1.0e-50)
- Refactors closest_point to Segment operator to only punt if it needs to
- Uses closest_point to Segment operator in squared_distance to Segment operator
- Adds actual degenerate test case for closest_point to Segment operator
=> Fixes/improvements for closest_point to Segment operator

src/axom/primal/operators/closest_point.hpp, src/axom/primal/tests/primal_closest_point.cpp
- This PR is a bugfix:
- Modifies closest_point on triangle query to handle degenerate triangles
- Adds tests for closest_point on triangle query at the request of myself
- Fixes #1307
=> Add tests for closest_point on triangle operator

src/axom/quest/detail/DistributedClosestPointImpl.hpp
In earlier versions, Conduit used to not support MPI_ANY_SOURCE and MPI_ANY_TAG when checking non-blocking sends and receives. It does now.
This change backs out a work-around I implemented at the time.
=> Undo work-around for Conduit limitation.

src/axom/primal/operators/detail/intersect_impl.hpp, src/axom/primal/operators/intersect.hpp, src/axom/primal/tests/primal_intersect.cpp
This PR adds an _intersect_ function in primal that lets the user slice a tetrahedron with plane and if there is an intersection, return the intersection polygon. There are existing _intersect_ functions for other primal primitives. This new function follows the established pattern. A new CI test was added.
This resolves #1324, which was requested by @adayton1.
=> Add intersect function for plane/tet that returns polygon output.

RELEASE-NOTES.md, src/axom/primal/geometry/Plane.hpp, src/axom/primal/tests/primal_plane.cpp
- Adds reflectPoint method to Plane at the request of myself
- Makes sure all Plane methods (except I/O) are device accessible
- Removes redundant (and potentially harmful) "inline" keyword on methods in Plane
=> Add a reflectPoint method to Plane

RELEASE-NOTES.md, src/cmake/AxomMacros.cmake, src/cmake/axom-config.cmake.in, src/cmake/thirdparty/SetupAxomThirdParty.cmake
A user submitted a problem where our finding of Conduit was defaulting to a Conduit installed in a system installed Python installation over the specified `CONDUIT_DIR`.  This turns off that.
It also adds a new macro to ensure the target that we expect to come out of the find calls is present afterwards.
=> Harden CMake find_*

scripts/llnl_scripts/archive_job.py, scripts/llnl_scripts/build_devtools.py, scripts/llnl_scripts/build_src.py, scripts/llnl_scripts/build_tpls.py, scripts/llnl_scripts/report.py
- This PR is a Python module update
- Replaces deprecated module optparse with argparse.
- Fixes #1268
=> Convert Python scripts to use argparse

RELEASE-NOTES.md, src/axom/core/examples/core_acceleration.cpp, src/axom/core/execution/internal/cuda_exec.hpp, src/axom/core/execution/internal/hip_exec.hpp, src/axom/core/tests/core_array_for_all.hpp, src/axom/core/tests/core_execution_for_all.hpp, src/axom/core/tests/core_execution_space.hpp, src/axom/mint/tests/mint_execution_cell_traversals.cpp, src/axom/mint/tests/mint_execution_face_traversals.cpp, src/axom/mint/tests/mint_execution_node_traversals.cpp, src/axom/primal/tests/primal_boundingbox.cpp, src/axom/primal/tests/primal_clip.cpp, src/axom/primal/tests/primal_numeric_array.cpp, src/axom/primal/tests/primal_point.cpp, src/axom/primal/tests/primal_polyhedron.cpp, src/axom/primal/tests/primal_vector.cpp, src/axom/primal/tests/primal_zip.cpp, src/axom/quest/DistributedClosestPoint.cpp, src/axom/quest/IntersectionShaper.hpp, src/axom/quest/detail/Discretize_detail.hpp, src/axom/quest/detail/DistributedClosestPointImpl.hpp, src/axom/quest/examples/quest_distributed_distance_query_example.cpp, src/axom/quest/tests/quest_discretize.cpp, src/axom/quest/tests/quest_signed_distance.cpp, src/axom/spin/tests/spin_bvh.cpp, src/axom/spin/tests/spin_implicit_grid.cpp, src/tools/mesh_tester.cpp
This PR:
- Makes device the default Umpire allocator id instead of unified for CUDA and HIP execution policies.
- Adjusts unit tests and examples to reflect device memory as the new default.
- For tests and examples where device id for memory allocation did not work, unified id is used instead.
Follow-up work is required to revisit tests and examples that still require unified memory, and adjust the source implementation.  These are captured in https://github.com/LLNL/axom/issues/1339
=> Set default allocator id to device instead of unified for CUDA and HIP execution policies

.gitlab-ci.yml, .gitlab/build_lassen.yml, .gitlab/build_quartz.yml, .gitlab/build_rzansel.yml, .gitlab/build_rzgenie.yml, .gitlab/build_tioga.yml
Now that the CI queue on LC has been proven to be effective, I feel like it's time that we can reduce the complexity of our gitlab scripts. The two focuses in this PR are: removing the allocate/deallocate stages and moving us to the batch runners instead of the shell runners.
=> Gitlab batch runners

src/axom/quest/DistributedClosestPoint.cpp, src/axom/quest/DistributedClosestPoint.hpp, src/axom/quest/detail/DistributedClosestPointImpl.hpp, src/axom/quest/examples/CMakeLists.txt, src/axom/quest/examples/quest_distributed_distance_query_example.cpp
- Break up `DistributedClosestPointImpl` into a non-templated base class and the derived class `DistributedClosestPointExec` templated on `DIM` and `ExecSpace`.
- Makes minor fixes to the CMake test set-up.
The refactoring simplifies the code and follows the separation of template and non-template code used in the marching cubes implementation.  It helps the optimization I'm implementing in `DistributedClosestPointImpl`.
Before this re-factoring, `DistributedClosestPointImpl` is templated on `DIM` and has BVH objects that are templated on DIM and `ExecSpace`.  We had separate pointers for all possible dimensions and execution spaces.  There was a lot of trivial-yet-clunky code to pick the correct pointers.
After the refactoring, …
=> Separate templated and non-template code in DistributedClosestPointImpl

azure-pipelines.yml
This PR updates the Azure Pipelines MacOS agent to macOS-12.
The current macOS-11 agent is being deprecated as of June 28th:
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
=> Update MacOS Azure agent

RELEASE-NOTES.md, src/axom/core/Array.hpp, src/axom/core/ArrayBase.hpp, src/axom/core/tests/core_array_for_all.hpp
- Adds GPU-side `ArrayOps` operations for unified and pinned memory.
As with the operations for device memory, unified and pinned memory operations try to use Umpire operations when the type is trivially-copyable, and instantiate a GPU kernel for fill operations when the type is trivially-constructible. This potentially avoids unwanted memory motion between the CPU and GPU.
In the case where the type isn't trivially-copyable or trivially-constructible, the corresponding operation needs to be performed on the device in order to correctly call the required constructor. However, since unified and pinned memory are accessible on the device, we can just do that operation in-place instead of allocating a temporary buffer.
=> Array: improve support for unified memory

src/axom/sidre/examples/sidre_stressgroups.cpp
- This PR is a refactor
- It replaces std::random_shuffle, which has been removed in c++17, with std::shuffle
Resolves https://github.com/LLNL/axom/issues/1000
=> Replace `std::random_shuffle` with `std::shuffle`

RELEASE-NOTES.md, src/axom/primal/geometry/Polyhedron.hpp, src/axom/primal/tests/primal_polyhedron.cpp
This PR:
- Changes `Polyhedron::centroid()` function to return center of mass of the polyhedron.
- Adds `Polyhedron::vertexMean()`, returns average of polyhedron's vertices (previous `centroid` functionality).
- Adds `Polyhedron::moments()`, returns the volume and centroid of the polyhedron, the 0th and 1st moments respectively.
- Based on PolyClipper's [moments ](https://github.com/LLNL/PolyClipper/blob/3091a15aba5ad685afdaf19016a79673b58308da/src/polyclipper3dImpl.hh#L183-L231)function. 
- `centroid()` and `signedVolume()` delegate to `moments()`.
Resolves #1348
=> Polyhedron centroid

src/axom/quest/MarchingCubes.cpp, src/axom/quest/MarchingCubes.hpp
The bug was triggered when generating the contour from multiple meshes (such as SAMR levels), and the number of domains decrease.  When this happens, the memory-use optimization leaves all single-domain objects, but keeps track of the count separately.  Loops through domains should use the separately maintained count, not the number of items allocated.
=> Fix bug crashing MarchingCubes.

RELEASE-NOTES.md, src/axom/core/CMakeLists.txt, src/axom/core/StaticArray.hpp, src/axom/core/tests/CMakeLists.txt, src/axom/core/tests/core_serial_main.cpp, src/axom/core/tests/core_static_array.hpp, src/axom/primal/geometry/Point.hpp, src/axom/primal/geometry/Polygon.hpp, src/axom/primal/operators/clip.hpp, src/axom/primal/operators/detail/clip_impl.hpp, src/axom/primal/operators/detail/intersect_impl.hpp, src/axom/primal/operators/intersect.hpp, src/axom/primal/tests/primal_clip.cpp, src/axom/primal/tests/primal_intersect.cpp, src/axom/primal/tests/primal_polygon.cpp
This PR:
- Implements an overload `clip()` for 2D polygons using the Sutherland–Hodgman algorithm.
- host-device decorated to run on device. 
- Generalizes `intersect(plane, segment)` for 2D.
- Moved `StaticArray` from Polygon class into core.
=> 2D Polygon Intersection

.github/actions/apply-style/entrypoint.sh, .mailmap, src/CMakeLists.txt, src/axom/config.hpp.in, src/axom/core/CMakeLists.txt, src/axom/inlet/CMakeLists.txt, src/axom/inlet/Field.cpp, src/axom/klee/CMakeLists.txt, src/axom/lumberjack/CMakeLists.txt, src/axom/mint/CMakeLists.txt, src/axom/mint/core/config.hpp.in, src/axom/multimat/CMakeLists.txt, src/axom/primal/CMakeLists.txt, src/axom/quest/CMakeLists.txt, src/axom/sidre/CMakeLists.txt, src/axom/slam/CMakeLists.txt, src/axom/slic/CMakeLists.txt, src/axom/spin/CMakeLists.txt, src/cmake/AxomMacros.cmake, src/docs/sphinx/dev_guide/component_org.rst, src/examples/using-with-blt/example.cpp, src/examples/using-with-cmake/example.cpp, src/examples/using-with-make/example.cpp, src/thirdparty/tests/CMakeLists.txt, src/tools/CMakeLists.txt
Couldn't test this until it was in the default branch. This does the following:
* Removes component based code checks
* Simplifies `axom_add_code_checks` macro
* Run style on more files that are included due to previous bullet point
=> Fix `/style` functionality

RELEASE-NOTES.md, src/axom/slic/core/LogStream.cpp, src/axom/slic/core/LogStream.hpp, src/axom/slic/docs/sphinx/sections/architecture.rst, src/axom/slic/examples/basic/lumberjack_logging.cpp, src/axom/slic/streams/GenericOutputStream.cpp, src/axom/slic/streams/LumberjackStream.cpp, src/axom/slic/streams/SynchronizedStream.cpp
=> Split RANK_COUNT out of RANK in SLIC message formatting

src/axom/core/Array.hpp, src/axom/core/MDMapping.hpp, src/axom/core/tests/core_array.hpp, src/axom/core/tests/core_array_for_all.hpp, src/axom/mint/execution/internal/for_all_faces.hpp, src/axom/mint/tests/mint_mesh_connectivity_array.cpp, src/axom/mint/tests/mint_mesh_unstructured_mesh.cpp, src/axom/primal/geometry/Polygon.hpp, src/axom/sidre/core/Array.hpp, src/axom/sidre/tests/sidre_mcarray.cpp
- Modifies the `axom::Array` dynamic reallocation logic to conform with LLVM libc++'s behavior. At present, the current method always allocates at least `new_num_elements * resize_ratio` elements when doing a dynamic reallocation; this might result in excessive memory usage when allocating a fixed-size `axom::Array`.
- Separate out the device-enabled `push_back` and `emplace_back` methods into new methods `Array::pushBackDevice()` and `Array::emplaceBackDevice()`. This avoids spurious host/device warnings that result from calling `push_back()` or `emplace_back()` with an object that isn't copyable on the device.
- Add some missing host/device annotations to `axom::MDMapping`.
=> Miscellaneous Array fixups

scripts/docker/dockerfile_gcc-9_cuda-11, scripts/spack/configs/docker/ubuntu20_cuda/spack.yaml
This PR:
- Updates the CUDA AWS Tutorial image for 2024
- Verified image works in an AWS instance, and axom tests and executables were able to run in the instance.
- AWS Setup instructions were also updated: https://lc.llnl.gov/confluence/display/ASCT/AWS+Setup+Working+Notes
- The updated Docker image can be found here: https://hub.docker.com/r/han12/axom-tutorial/tags
A follow-up PR will likely be necessary once #1171 is merged.
=> AWS tutorial Docker image update

src/axom/quest/DistributedClosestPoint.cpp, src/axom/quest/DistributedClosestPoint.hpp, src/axom/quest/MeshTester.hpp, src/axom/quest/MeshViewUtil.hpp, src/axom/quest/PointInCell.hpp, src/axom/quest/SignedDistance.hpp
@gberg617
Guy noticed that a compilation error in the new release due to SLIC being used in a header and not including SLIC.  This should fix that and more.
=> Add missing SLIC includes

src/thirdparty/axom/CLI11.hpp
Change CLI11's `Success` to `CLI11_Success` to work around X11 #defining the symbol.
This fixes https://github.com/LLNL/axom/issues/1400
=> Work around X11 #defining "Success" and conflicting with CLI11

src/thirdparty/axom/CLI11.hpp
Somehow, I broke the association between the branch and the pull request for resolving the X11-CLI11 conflict.  This is a new pull request to take place of the one that was already approved by @rhornung67 and @agcapps.  While removing some white spaces as suggested by @agcapps, I broke the association.
=> Substitute PR for resolving X11-CLI11 conflict

src/axom/mint/execution/internal/for_all_cells.hpp, src/axom/mint/execution/internal/for_all_faces.hpp, src/axom/mint/execution/internal/for_all_nodes.hpp, src/axom/mint/execution/internal/helpers.hpp, src/axom/mint/tests/mint_execution_cell_traversals.cpp, src/axom/mint/tests/mint_execution_face_traversals.cpp, src/axom/mint/tests/mint_execution_node_traversals.cpp, src/axom/primal/examples/CMakeLists.txt, src/axom/primal/examples/hex_tet_volume.cpp, src/axom/quest/DistributedClosestPoint.cpp, src/axom/quest/detail/MeshTester_detail.hpp, src/axom/quest/examples/CMakeLists.txt, src/axom/quest/examples/point_in_cell_benchmark.cpp, src/axom/quest/examples/quest_bvh_two_pass.cpp, src/tools/mesh_tester.cpp
This PR:
- Contains work related to issue https://github.com/LLNL/axom/issues/1339
- Refactors several examples and tests to allow for execution with a device policy (previously required unified policy to run on device), notably:
- mint `for_all_*` execution loops
- `mesh_tester`
- `point_in_cell_benchmark`
=> Allow device policy execution for more tests and examples

src/axom/lumberjack/MPIUtility.cpp
This fixes a warning that I saw when running mpi mustrun /collab/usr/global/tools/tce4/opt/must-1.9.2/bin/mustrun --must:mpiexec srun --must:np -n -n 4 executable -inputs
```
Argument 5 (tag) is a tag that is larger than 32767 and may thus only be supported by some MPI implementations. This implementation supports tags up to 268435455. For portability reasons you sh...
```
there were a few other warnings but this seemed to be the most important.
Also, intel documentation (see https://www.intel.com/content/www/us/en/developer/articles/technical/large-mpi-tags-with-the-intel-mpi.html ) says that a tag value exceeding 32767 or 15 bits may not be portable.
=> change to tag number to fix warning

src/axom/sidre/core/Group.cpp, src/axom/sidre/core/Group.hpp
- Moves the declaration and initialization of the static vector containing all valid I/O protocol strings into the static method that uses it.
- Fixes #1408
=> Move I/O protocol vector into static method

src/axom/quest/examples/quest_candidates_example.cpp
This PR:
- Adds caliper annotations to `quest_candidates_example` 
As part of this, also re-ran my test scripts using the same setup as before to get the _average_ numbers (in seconds) for the spatial index performances. In addition, I added numbers for rzwhippet for 112 threads.
Notably, the initialization times for both bvh and implicit grid are an order of magnitude faster than before for HIP and CUDA (previous PR #1278 for comparison):
| Policy - Spatial Index         | Initialize Spatial Index | Query candidates | Write candidate pairs | Total average processing runtime | System Tested On |
|-------------------------------|-------------------------|------------------|----------------------|---------------------------------| ---------------------------|
| Sequential - BVH (36 threads) …
=> Add caliper annotations to quest_candidates_example

src/axom/primal/geometry/Point.hpp, src/axom/primal/geometry/Segment.hpp, src/axom/primal/geometry/Vector.hpp
- Adds missing device functions to Point, Segment, and Vector at the request of myself
=> Add missing device functions to primal

src/axom/core/Array.hpp, src/axom/core/ArrayBase.hpp, src/axom/core/ArrayView.hpp, src/axom/core/IteratorBase.hpp, src/axom/core/detail/FlatTable.hpp, src/axom/slam/BivariateMap.hpp, src/axom/slam/BivariateSet.hpp, src/axom/slam/Map.hpp, src/axom/slam/OrderedSet.hpp, src/axom/slam/SubMap.hpp, src/axom/slam/policies/IndirectionPolicies.hpp, src/axom/spin/tests/spin_bvh.cpp
Clears up the bulk of Slam/Core-associated host/device usage warnings.
- Most of these were associated with the Slam `IndirectionPolicy` accessing the array value by reference; the interface has been changed to return a pointer-to-value, which allows us to just return `nullptr` for `STLVectorIndirectionPolicy`.
- The remainder were associated with the construction of `Map`, `BivariateMap`, and `SubMap` iterators, and were resolved by adding a bunch of `AXOM_HOST_DEVICE` annotations, and using a concrete interface policy for `Map` types by default.
The other remaining warnings were:
- `FlatMap`: Improperly setting an unsigned hash value with a negative sentinel value. The assignment was extraneous and removed.
- `BVH`: A test passed in an `axom::Array` to `BVH::initialize()`, which is …
=> Cleanup a bunch of GPU warnings

RELEASE-NOTES.md, src/axom/core/numerics/eigen_solve.hpp, src/axom/primal/geometry/OrientedBoundingBox.hpp, src/axom/primal/tests/primal_orientedboundingbox.cpp
- This PR is a bugfix. It removes an unnecessary early termination criterion in the `numerics::eigen_solve` method.
- A test for the `primal::OrientedBoundingBox( const PointType* pts )` constructor has been added, which utilizes this method.
The `numerics::eigen_solve` method uses the power method to find eigenvalues and eigenvectors for an NxN matrix. At each step, a random vector is created and then made orthonormal to previously found eigenvectors. If this randomly created vector is (numerically) already in the span of previously found eigenvectors, it has zero magnitude, and the algorithm will terminate early with an error status.
While this event has mathematically zero chance of occurring, it occurs numerically in roughly 0.05% of runs of the existing `numerics_eigen_solve` test, …
=> Bugfix: Early exit in `eigen_solve` method

.github/workflows/test_windows_tpls.yml
Previous versions were deprecated.
See:
* https://github.blog/news-insights/product-news/get-started-with-v4-of-github-actions-artifacts/
* https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
=> Upgrade upload-artifact action to v4

src/axom/core/MDMapping.hpp, src/axom/slam/BivariateMap.hpp
- Modifies `MDMapping::isPermutation` to avoid warning about unsigned integer comparison
- Add `AXOM_HOST_DEVICE` annotation to `BivariateMap::iterator::value()`
=> More warnings cleanup

src/axom/core/Array.hpp, src/axom/core/memory_management.hpp, src/axom/core/tests/core_execution_space.hpp
Lack of Array::m_executeOnGPU initialization played a role in causing host-initialization of device-allocated memory in certain situations. I was not able to create a reproducer on the develop branch but these changes eliminate warnings about uninitialized memory in axom::Array under Valgrind and fix the crashes on my MIR branch when using CUDA-allocated memory.
- This PR is a bugfix and closes #1432.
- It adds some initialization for Array::m_executeOnGPU, a bool that was causing warnings about uninitialized memory.
=> Initialize Array::m_executeOnGPU

RELEASE-NOTES.md, src/axom/quest/examples/quest_marching_cubes_example.cpp
- This bugfix PR guards `sidre`-related `mint` API calls in the `quest` marching cubes example
- These are only available when the code is configured with `AXOM_MINT_USE_SIDRE`
- Resolves #1435
=> Adds missing preprocessor guard to quest marching cubes example

RELEASE-NOTES.md, src/axom/core/utilities/FileUtilities.hpp, src/axom/slic/interface/slic_macros.hpp, src/axom/slic/tests/slic_macros.cpp, src/axom/slic/tests/slic_macros_parallel.cpp
This PR:
- Adds testing for ranks and rank counts information in `slic_macros_parallel` unit tests.
- Remove `std::ends` from `SLIC_ASSERT`/`SLIC_ASSERT_MSG`/`SLIC_CHECK`/`SLIC_CHECK_MSG` macros that prevented Lumberjack from combining messages. When packing/unpacking messages for combining, `std::ends` does not play nice in std::string --> C-style string conversions. Trailing `std::ends` null character does not get included in the conversion, so output/rank Node's message (with `std::ends` null character) will always be different from the other nodes (no`std::ends` null character), and as such no combining would take place.
- Added check that messages are unique/combined for LumberjackStreams in unit tests.
- Example Reproducer of behavior: https://godbolt.org/z/of9Y74sxz
Relates to …
=> Add unit testing for Slic ranks and rank counts

azure-pipelines.yml, src/docs/sphinx/quickstart_guide/zero_to_axom.rst, src/examples/using-with-blt/CMakeLists.txt, src/examples/using-with-cmake/CMakeLists.txt, src/examples/using-with-make/Makefile.in
I was looking at the online Quickstart guide at "https://axom.readthedocs.io/en/develop/docs/sphinx/quickstart_guide/zero_to_axom.html#using-axom-in-your-project" for some CMake example code and the docs looked incomplete. When I looked at the sources, they were using a "lines" directive to pull out content from some build files. I'd guess that the build files had changed since the docs were written and then the docs did not get updated.
This PR adjusts some line numbers to make the CMake and BLT code examples contain the whole block of code instead of stopping midway through some if-statements.
=> Fix line numbers in Quickstart Guide

azure-pipelines.yml, scripts/azure-pipelines/linux-build_and_test.sh, src/axom/core/memory_management.hpp, src/axom/core/tests/CMakeLists.txt, src/axom/core/tests/core_benchmark_array.cpp, src/axom/primal/tests/primal_nurbs_curve.cpp, src/axom/quest/Shaper.cpp, src/axom/quest/interface/inout.cpp, src/axom/sina/examples/sina_check_datum_type.cpp, src/axom/sina/tests/sina_Record.cpp, src/axom/slam/benchmarks/CMakeLists.txt, src/axom/slam/benchmarks/slam_array.cpp, src/axom/slam/benchmarks/slam_sets.cpp, src/axom/slic/tests/CMakeLists.txt, src/axom/slic/tests/slic_benchmark_asserts.cpp, src/axom/slic/tests/slic_macros.cpp, src/axom/slic/tests/slic_macros_parallel.cpp
- This PR is progress towards #287  
(see also #922)
- It adds initial benchmarking of `axom::Array` vs. `std::vector`
- Specifically, it compares construction times, performance of `push_back` and `emplace_back` and some iterator operations.
- I decided to stop here in this first attempt before the testing got too involved
- This PR also updates BLT to get a bugfix related to running benchmarks (https://github.com/LLNL/blt/pull/698) and fixes our existing gbenchmark tests for `slic` and `slam`
- It also adds `ENABLE_BENCHMARKS` to a debug and a release config CI job and runs the benchmarks as part of the testing
Here are the initial results for a Release Clang config on an LC CTS-2 cluster comparing `axom::Array` vs. `std::vector` templates on several types:
* `int`
* …
=> Adds initial benchmarking for axom::Array vs. std::vector

src/axom/sidre/docs/sphinx/file_io.rst, src/axom/sidre/tests/sidre_external.cpp
- This PR is an addition of a test and documentation of the relevant feature.
- Restores a test for serial save/load of Sidre views with external data.  A broken test was present in the code in an `#if 0` block.  Here this test is fixed to do the right thing and includes a section to be used as a snippet in the sphinx docs.
- Add sphinx documentation of the process required to save and load external views in a way that restores the external state that was saved.
Based on recent conversations I realized that the process to save and load views with external data lacked sufficient documentation, and had no active test code for the serial case (i.e. not using SPIO).  The process takes three steps and is not obvious.  I found the inactive test …
=> Test and documentation for save/load of external Sidre views.

README.md
- This PR changes the link to our documentation on our main project to the new RTD dashboard.
- The current legacy dashboard is going away in March 2025.
- Why wait until the last minute?!?
=> Use new RTD dashboard

RELEASE-NOTES.md, src/axom/sidre/core/MFEMSidreDataCollection.cpp, src/axom/sidre/core/MFEMSidreDataCollection.hpp, src/axom/sidre/tests/CMakeLists.txt, src/axom/sidre/tests/sidre_mfem_datacollection.cpp, src/axom/sidre/tests/sidre_read_write_userdefined_data.cpp, src/axom/sidre/tests/spio/spio_parallel.hpp
* Fixes `MFEMSidreDataCollection::LoadExternalData` to work on the root of the `DataStore` when in parallel because it is currently required, see #1479 
* Add tests/examples on how to work with external data in the `DataStore`, `IOManager` and `MFEMSidreDataCollection` classes
Enables https://github.com/LLNL/serac/pull/1258
=> Fix `MFEMSidreDataCollection::LoadExternalData` and add test cases for various `LoadExternalData` functions

RELEASE-NOTES.md, src/axom/primal/operators/detail/clip_impl.hpp, src/axom/primal/operators/detail/intersect_impl.hpp, src/axom/primal/operators/intersect.hpp, src/axom/primal/tests/primal_clip.cpp
This PR:
- Adds robustness example to unit tests from #1481 
- Fixes robustness issue with 2D polygon clipping by:
- Adding missing tolerance parameter to `intersect` overload   between plane and segment
- Generalizing, simplifying logic to handle duplicate vertices in Sutherland–Hodgman algorithm by performing a pass at the end to remove duplicates.
Closes #1481
=> 2D polygon robustness

src/axom/core/execution/internal/cuda_exec.hpp, src/axom/core/execution/internal/hip_exec.hpp
This fixes a couple of things I missed in the PR for blueprint support in shaping.  There were two similar changes needed in each of the device execution headers, and I only got one.
=> Remove redundant check and use of out-dated hard-wired value.

.gitlab/build_ruby.yml, RELEASE-NOTES.md, host-configs/rzadams-toss_4_x86_64_ib_cray-cce@18.0.0_hip.cmake, host-configs/rzadams-toss_4_x86_64_ib_cray-rocmcc@6.1.2_hip.cmake, host-configs/rzadams-toss_4_x86_64_ib_cray-rocmcc@6.2.1_hip.cmake, host-configs/rzvernal-toss_4_x86_64_ib_cray-cce@18.0.0_hip.cmake, host-configs/rzvernal-toss_4_x86_64_ib_cray-rocmcc@6.1.2_hip.cmake, host-configs/rzvernal-toss_4_x86_64_ib_cray-rocmcc@6.2.1_hip.cmake, scripts/spack/packages/axom/package.py, src/axom/core/Macros.hpp, src/axom/slic/interface/slic_macros.hpp, src/tools/CMakeLists.txt, src/tools/mesh_tester.cpp
This PR
- Enables `assert` for HIP in the `SLIC_ASSERT_*` and `SLIC_CHECK_*` macros.
EDIT: 
- Fixes the `CMAKE_CXX_FLAGS_DEBUG` to actually allow `assert()` for rocm builds.
- Previously, in order to get `mesh_tester` working with a hip policy in #1151, `-DNDEBUG` was added to the debug flags.
- This disabled `assert()` for debug rocm builds.
- Updated axom spack recipe and host-configs to reflect `CMAKE_CXX_FLAGS_DEBUG` change
- Note: `%cce` debug builds require some optimization (`-O1`) to compile without cray compiler errors (error is of the form: `PLEASE submit a bug report to Cray and include the crash backtrace, preprocessed source, and associated run script. Stack dump: ...` ).
- Remove checks for `NDEBUG` in `mesh_tester`
EDIT 2:
- Small change to `sbatch` option for Gitlab CI …
=> Enable HIP assert in SLIC macros

.mailmap, src/axom/sidre/spio/IOManager.cpp
- Fixes unused variables in `IOManager::loadExternalData()` for builds without HDF5
=> Fixed unused variables in builds without HDF5

.mailmap, src/axom/primal/tests/primal_surface_intersect.cpp, src/axom/quest/detail/PointInCellMeshWrapper_mfem.hpp, src/axom/quest/examples/CMakeLists.txt, src/axom/sidre/core/MFEMSidreDataCollection.cpp, src/axom/sidre/core/MFEMSidreDataCollection.hpp, src/axom/sidre/examples/spio/CMakeLists.txt, src/axom/sidre/spio/IOManager.cpp, src/axom/sidre/tests/sidre_external.cpp, src/axom/sidre/tests/sidre_group.cpp, src/axom/sidre/tests/sidre_mfem_datacollection.cpp, src/axom/sidre/tests/sidre_read_write_userdefined_data.cpp, src/cmake/AxomConfig.cmake, src/cmake/axom-config.cmake.in, src/cmake/thirdparty/SetupAxomThirdParty.cmake
- It fixes the build and tests in configurations without `hdf5`
- I also discovered and fixed an unknown dependency for `scr` on `zlib`
I noted in #1480 that Axom supports configurations without `hdf5`. We don't currently have CI for this, and when I configured the code without `hdf5`, I found several tests that did not work. This branch fixes them. 
Since non-`hdf5` configs require a `conduit` without `hdf5` (i.e. a new library set), I'm not sure that we need a CI that tests this -- it might be enough to just manually run the code and fix it every so often. Perhaps we should have a manually run github-action that does this, similar to our manual Windows TPL build?
I configured the code with a host-config generated by running the following uberenv command:
```
> …
```
=> Fixes build and tests when not using `hdf5`

RELEASE-NOTES.md, src/axom/lumberjack/LineFileTagCombiner.hpp, src/axom/lumberjack/docs/sphinx/combiner_class.rst, src/axom/lumberjack/tests/CMakeLists.txt, src/axom/lumberjack/tests/lumberjack_LineFileTagCombiner.hpp, src/axom/lumberjack/tests/lumberjack_serial_main.cpp
- Adds a Lumberjack combiner that combines messages only when the line number, file name, and tag are equal.  If texts are not equal, only one text message will remain after being combined.  This can be useful in some circumstances where we have a similar message that is emitted many times from the same source code location, but may be slightly different in its text content (e.g. if it includes the rank in the message).  In some of these cases, the user may want to just see one message, even if the content is slightly different.
=> Added LineFileTagCombiner

RELEASE-NOTES.md, src/axom/primal/geometry/Polygon.hpp, src/axom/primal/tests/primal_point.cpp, src/axom/primal/tests/primal_surface_intersect.cpp, src/axom/quest/IntersectionShaper.hpp, src/axom/quest/Shaper.cpp, src/axom/quest/examples/CMakeLists.txt, src/axom/quest/examples/quest_shape_in_memory.cpp, src/axom/quest/examples/shaping_driver.cpp, src/axom/quest/util/mesh_helpers.cpp, src/axom/quest/util/mesh_helpers.hpp, triangle_2d.yaml, unit_triangle.stl
This PR:
- Adds 2D intersection shaping, accepting as input either a 2D `stl` mesh of triangles (0 for z-coordinates) or a 2D in-memory triangle blueprint mesh.
- `quest_shape_in_memory.cpp` modified to support a 2D in-memory triangle mesh (`create2DShapeSet`). 
- Adds additional utility functions to `mesh_helpers` for generation of 2D quad meshes using mfem/sidre/blueprint
- Related PR LLNL/axom_data#25 adds a 2D `stl` mesh for testing.
- Fixes bug in `shaping_driver.cpp` where policy used for allocation would always be sequential.
- Runtime regex output tests added in `src/axom/quest/examples/CMakeLists.txt` for `quest_shaping_driver_ex` and `quest_shape_in_memory_ex` executables.
=> Initial 2D intersection shaping

.uberenv_config.json, host-configs/tioga-toss_4_x86_64_ib_cray-cce@18.0.0_hip.cmake, host-configs/tioga-toss_4_x86_64_ib_cray-rocmcc@6.1.2_hip.cmake, host-configs/tioga-toss_4_x86_64_ib_cray-rocmcc@6.2.1_hip.cmake, scripts/vcpkg_ports/umpire/portfile.cmake, scripts/vcpkg_ports/umpire/v2024.07.0-chrono-include.patch, src/axom/config.hpp.in, src/axom/core/Macros.hpp, src/axom/core/memory_management.hpp, src/axom/core/tests/core_utilities.hpp, src/axom/core/utilities/Sorting.hpp, src/axom/mir/clipping/ClipCases.h, src/axom/mir/tests/mir_clipfield.cpp, src/axom/mir/tests/mir_views.cpp, src/axom/mir/utilities/blueprint_utilities.hpp, src/axom/mir/views/view_traits.hpp, src/axom/quest/DiscreteShape.cpp, src/axom/quest/Shaper.cpp, src/axom/quest/util/mesh_helpers.cpp, src/axom/sidre/core/Group.cpp, src/axom/sidre/core/Group.hpp, src/axom/sidre/core/MFEMSidreDataCollection.cpp, src/axom/sidre/tests/sidre_mfem_datacollection.cpp, src/axom/sidre/tests/sidre_read_write_userdefined_data.cpp, src/axom/sina/core/Document.cpp, src/axom/sina/core/ID.cpp, src/cmake/AxomConfig.cmake, src/cmake/AxomMacros.cmake
- This PR is a bugfix for the build on Windows
- It fixes:
-  the MIR build, which required some exports for static members
- MIR tests that depend on the compile time path to the data directory
- A bug with the quicksort algorithm for some data orderings and adds a unit test
- Some quest tests when mfem does not have MPI
- Some quest lambdas that take a constexpr -- MSVC appears to require `static constexpr` w/ c++14. This might be relaxed in c++17
- I also cleaned up/updated some sidre::Group implementations to use the iterator interface while working on sidre test bugfixes
- **Update:** Passes all builds and tests in our Windows TPL CI -- https://github.com/LLNL/axom/actions/runs/13846008225
- The code + tests + examples currently build w/ our msvc configuration
- The following tests …
=> Fixes build and tests on Windows

src/axom/quest/MarchingCubes.hpp, src/axom/quest/detail/MarchingCubesImpl.hpp
- This PR is a bugfix (work-around)
- Use a totally inefficient 32-bit int to represent a boolean, to work around a ROCM behavior.
- Add comment about the same work-around for another array.
- Add notes on when we can remove the work-around.
We have 2 arrays, one with booleans and with ints in [0,5], but we have to use more bits to represent them for ROCM.  We do sum scans on them and put the output in 32-bit ints.  However, ROCM is doing the sum in the **input** type without promoting to the output type.  This work-around bumps up the input type.
Related to https://github.com/LLNL/RAJA/issues/1631
=> Work-around for ROCM overflowing ints when scan-summing arrays

src/axom/quest/readers/C2CReader.cpp, src/axom/quest/readers/C2CReader.hpp, src/axom/quest/readers/PC2CReader.cpp, src/axom/quest/readers/PC2CReader.hpp
- This PR is a refactoring of the C2CReader classes
- It uses axom's internal `NURBSCurve` class from primal to evaluate and discretize the C2C curve pieces.
- We previously used a custom `NURBSInterpolator` class since axom did not yet have the `NURBSCurve` class
I decided to keep this PR relatively small, and will work on several future features/improvements in follow up PRs:
- #1527 
- #1528 
- #1529 
- #1530
=> Improves c2c reader class

scripts/spack/configs/toss_4_x86_64_ib/spack.yaml, scripts/spack/configs/toss_4_x86_64_ib_cray/spack.yaml, scripts/spack/devtools_configs/toss_4_x86_64_ib/spack.yaml, scripts/spack/devtools_configs/toss_4_x86_64_ib_cray/spack.yaml
Spack v1.0 will parse `pkg %gcc +foo` as "pkg with direct dependency gcc
with variant foo enabled" instead of "pkg with variant foo enabled and compiler
gcc". Reorder as `pkg +foo %gcc` to be compatible with Spack v0.x and
v1.0.
=> spack v1.0 support: `%foo +bar` -> `+bar %foo`

src/axom/core/CMakeLists.txt, src/axom/core/numerics/transforms.hpp, src/axom/primal/geometry/Point.hpp, src/axom/primal/geometry/Polygon.hpp, src/axom/primal/tests/primal_polygon.cpp
It was suggested in a different PR that it could be useful to have a function for generating regular polygons, taking a transformation matrix to affect how points are created. This PR adds a function for generating regular polygons and it takes an optional transformation matrix. I added tests for the function to make sure we can vary the transformation. In doing that, it became apparent that we have some scattered transformation routines for rotations, scaling, translation. Some of these were consolidated in ``axom/core/numerics/transforms.hpp``.
=> Add function for making regular polygons

src/axom/quest/examples/CMakeLists.txt, src/axom/quest/examples/shaping_driver.cpp
This PR: 
- Guards 2D STL intersection shaper unit test to only be compiled/run when Axom is built with RAJA and Umpire (IntersectionShaper class is only enabled with RAJA and Umpire).
=> Bugfix - guard 2D STL intersection shaper test

src/axom/primal/operators/detail/intersect_impl.hpp, src/axom/primal/operators/detail/intersect_patch_impl.hpp, src/axom/primal/operators/intersect.hpp
When building on blueos a lot of warnings are issued due to calling ``host`` functions from ``host device`` functions. This category of warnings were mainly coming from primal. This PR fixes many of these warnings.
* Replaced calls like min,max,fabs with equivalents from Axom utilities.
* Changed some functions to pass axom::StaticArray instead of axom::Array so they can be used in ``host device`` functions.
* Fixed an unrelated line of code that looked like a copy/paste error.
=> Fix some host device warnings.

RELEASE-NOTES.md, src/axom/quest/IntersectionShaper.hpp, src/axom/quest/Shaper.cpp, src/axom/quest/examples/CMakeLists.txt, src/axom/quest/examples/shaping_driver.cpp
This PR:
- Adds initial capability to accept c2c meshes as input to the 2D intersection shaper.
- Runtime regex output test added in `src/axom/quest/examples/CMakeLists.txt` for `quest_shaping_driver_ex`
- Fixes a bug where `m_samplesPerKnotSpan` was not being propagated.
- Future work is to support 2D shape bounded by multiple c2c contours (current assumption is a single c2c contour is bounded by the z-axis (x-axis))
=> Initial 2D intersection shaping for c2c

RELEASE-NOTES.md, src/axom/core/CMakeLists.txt, src/axom/core/FlatMap.hpp, src/axom/core/detail/FlatMapOps.hpp, src/axom/core/detail/FlatTable.hpp, src/axom/core/memory_management.hpp, src/axom/core/tests/core_flatmap.hpp
- Adds an `Allocator` wrapper class to disambiguate between integer arguments and allocator ID
This is a speculative change, and I'd like to hear feedback from others: my biggest complaint/regret about the `Array` constructor interface is that we aren't fully drop-in compatible with the `std::vector` constructor interface, as we've sprinkled in `allocator_id` function arguments haphazardly. I'm hoping this might provide an alternative path forward that we can test out in `FlatMap` for now, and maybe bring it over into `Array` proper once fleshed out.
- Adds initial Umpire allocation support for `FlatMap`, supporting the following operations:
- Creating a `FlatMap` within a custom Umpire allocator
- Copying `FlatMap` between two different allocators, including device-based allocators
- …
=> FlatMap: add Umpire support

RELEASE-NOTES.md, src/axom/core/ArrayBase.hpp, src/axom/core/detail/FlatMapOps.hpp
Resolves potential ODR-related issues in `axom::Array` and `axom::FlatMap` when compiling a host-only source file against a GPU-enabled Axom library.
- For `axom::Array`, preprocessor guards on `AXOM_GPUCC` are removed; instead, a static assertion is added within the device-side specialization of `ArrayOpsBase`.
This allows for host-compiled code which does not use or instantiate `axom::Array` to include `axom/Array.hpp` without issue, while blocking an inadvertent and potentially-conflicting instantiation of the device code path within a host-only compilation. [^1]
- For `axom::FlatMap`, replaces a kernel launch with an `axom::copy`.
Resolves the issues https://github.com/LLNL/axom/issues/1182 and https://github.com/LLNL/axom/issues/1440
[^1]: I think the implementation of `ArrayOpsBase` …
=> GPU-related ODR fixes for Array and FlatMap

src/axom/mint/utils/vtk_utils.cpp, src/axom/quest/IntersectionShaper.hpp
- Uses compile-time strings as the format string argument to fmt functions (required in C++20)
- The alternative is to wrap runtime format strings in axom::fmt::runtime
=> Use compile-time strings as the format argument to fmt functions (fixes to support C++20)

RELEASE-NOTES.md, src/axom/core/CMakeLists.txt, src/axom/core/DeviceHash.hpp, src/axom/core/FlatMap.hpp, src/axom/core/detail/FlatTable.hpp, src/axom/core/tests/CMakeLists.txt, src/axom/core/tests/core_device_hash.hpp, src/axom/core/tests/core_serial_main.cpp
- Adds `axom::DeviceHash` for supporting hashing certain primitive types (integers, floating points, enums) on the GPU
- Mimics the libc++ behavior for `std::hash`, which is to return the identity of the hashed value (casted to `axom::IndexType`)
- For unsupported types, just wraps a call to `std::hash::operator ()`
=> Add a DeviceHash class for GPU hashing

RELEASE-NOTES.md, src/axom/sina/CMakeLists.txt
- This PR is a bugfix for some configuration variables in Sina
- It fixes the inclusion/export of some Adiak-related source files 
- It also fixes hdf5 support in sina's Fortran interface.
- Note: `AXOM_USE_<FOO>` variables are not yet available within the Axom components.
=> Fixes some Sina configuration variables

RELEASE-NOTES.md, src/axom/core/Macros.hpp, src/axom/core/MapCollection.hpp, src/axom/core/tests/core_device_hash.hpp, src/axom/inlet/Container.hpp, src/axom/quest/MeshTester.cpp, src/axom/slam/OrderedSet.hpp, src/axom/slam/policies/StridePolicies.hpp, src/axom/slam/tests/slam_set_RangeSet.cpp, src/axom/spin/MortonIndex.hpp, src/axom/spin/SparseOctreeLevel.hpp, src/axom/spin/UniformGrid.hpp, src/axom/spin/internal/linear_bvh/build_radix_tree.hpp
- This PR is a bugfix associated with undefined behavior as identified by ubsan in our clang configuration
- In particular:
- It fixes invalid shifts in the BVH construction. The Morton indexing assumed that the `MortonIndexType` was unsigned, but was being passed in a signed integer. I changed this to an unsigned type and added a `static_assert` to `spin::MortonBase`
- It fixes possible invalid `spin:UniformGrid` initialization when passed geometry with invalid bounding boxes. We now skip those cases
- It fixes a validity check in `slam::OrderedSet` when presented with a stride of zero. There was previously a divide by zero.
- It fixes checks on empty `axom::MapCollection` instances when using sparsehash, which expected a sentinel key (even for empty hashtables). We now check if the …
=> Fixes several bugs related to undefined behavior

RELEASE-NOTES.md, src/axom/core/tests/utils_fileUtilities.hpp, src/axom/core/utilities/FileUtilities.cpp, src/axom/core/utilities/FileUtilities.hpp, src/axom/mint/tests/mint_su2_io.cpp, src/axom/quest/tests/quest_pro_e_reader.cpp, src/axom/quest/tests/quest_sampling_shaper.cpp, src/axom/quest/tests/quest_stl_reader.cpp, src/axom/quest/tests/quest_stl_writer.cpp, src/axom/sina/tests/sina_Document.cpp
- This is a feature PR that add a utility class to help with generating temp files with unique names
- By default, TempFile removes the file once it goes out of scope, but the constructor has a flag to keep the file
- It incorporates this `TempFile` class into several of Axom's unit tests.
- It also fixes a warning from Sina's tests about using an unsafe system call (`tmpnam`), and calls the recommended `mkstemp` instead.
- Removing that warning was the impetus for adding the TempFile class.
- Along the way it also fixes some edge cases in Axom's `joinPath` file utility
- Resolves a subtask of #1467
=> Adds a TempFile utility class to core's file utilities

RELEASE-NOTES.md, src/axom/core/CMakeLists.txt, src/axom/core/FlatMap.hpp, src/axom/core/FlatMapUtil.hpp, src/axom/core/detail/FlatTable.hpp, src/axom/core/examples/CMakeLists.txt, src/axom/core/examples/core_flatmap_perf.cpp, src/axom/core/tests/core_flatmap.hpp, src/axom/core/tests/core_flatmap_for_all.hpp
Adds a method `FlatMap::create()` for constructing a flat hash map over a batch of corresponding key-value pairs.
- A template parameter `ExecSpace` is used to specify whether the batched construction happens on the CPU, GPU, or over multiple threads via OpenMP. The passed-in `allocator` argument must be accessible from the specified execution space.
- If two equivalent keys are inserted, the key-value pair with the higher index is selected.
Also adds a benchmark example for `FlatMap`, which tests the performance of both batched insertion and lookups.
=> FlatMap: add method for batched GPU construction

src/axom/bump/CMakeLists.txt, src/axom/mir/CMakeLists.txt
- This PR is a minimal bugfix which adds a few missing header files to the CMake includes for `bump`/`mir`. Without these, referencing an installed Axom will have issues unless those files are copied over to the install directory directly.
- Reordered some includes to be alphabetical. This made it easier to check there wasn't anything else missing.
=> Add missing includes to bump/mir CMakeLists

src/axom/primal/geometry/BezierCurve.hpp, src/axom/primal/geometry/BezierPatch.hpp, src/axom/primal/geometry/KnotVector.hpp, src/axom/primal/geometry/NURBSCurve.hpp, src/axom/primal/geometry/NURBSPatch.hpp
- It reorganizes and consistently groups the functions in the `BezierCurve`, `BezierPatch`, `NURBSCurve`, `NURBSPatch` and `KnotVector` classes
- This is a precursor to improving the consistency of the APIs across these classes (https://github.com/LLNL/axom/issues/1528)
- Note: This PR has no changes to API or functionality. It only reorganizes the functions and groups them by functionality
- RTD/doxygen links for this branch: 
- https://axom.readthedocs.io/en/feature-kweiss-bezier-nurbs-api/
- [Updated Doxygen for BezierCurve class](https://axom.readthedocs.io/en/feature-kweiss-bezier-nurbs-api/doxygen/html/classaxom_1_1primal_1_1BezierCurve.html)
- [Updated Doxygen for BezierPatch class](https://axom.readthedocs.io/en/feature-kweiss-bezier-nurbs-api/doxygen/htm …
=> Reorganizes the Bezier and NURBS classes for consistency

src/axom/core/FlatMap.hpp, src/axom/core/FlatMapView.hpp, src/axom/sidre/CMakeLists.txt, src/axom/sidre/examples/CMakeLists.txt, src/docs/sphinx/dev_guide/component_org.rst, src/tools/CMakeLists.txt, src/tools/run_python_with_axom.sh.in
This PR:
- Adds a convenience script (`run_python_with_axom.sh`)that runs python interpreter with path to nanobind-generated extensions in the PYTHONPATH.
- Script is based on Conduit's `run_python_with_conduit.sh` script and CMake configuration logic: https://github.com/LLNL/conduit/blob/develop/src/libs/conduit/python/run_python_with_conduit.sh.in
=> Convenience script for nanobind python extensions

src/axom/mir/ElviraAlgorithm.hpp, src/axom/mir/EquiZAlgorithm.hpp, src/axom/mir/MIRAlgorithm.cpp, src/axom/mir/MIRAlgorithm.hpp, src/axom/mir/tests/mir_elvira2d.cpp, src/axom/mir/tests/mir_equiz2d.cpp
Early in MIR development, it was coded to iterate over multiple domains and perform MIR on each domain. The code was then pared back to operate on a single domain, with data provided using various topology, coordset, and matset views. This was done to limit the Blueprint types on which the algorithm needs to operate in order to generate smaller code.
This PR removes a vestige of domain iteration from `MIRAlgorithm` and changes comments to indicate that data are passed one domain at a time.
* Added multidomain testing for MIR
* Fixed an issue arising from domain prefix in Conduit object paths
=> Change MIRAlgorithm to make it clearer that it operates on a single domain.

RELEASE-NOTES.md, src/axom/core/FlatMap.hpp, src/axom/core/FlatMapUtil.hpp, src/axom/core/detail/FlatTable.hpp, src/axom/core/tests/core_flatmap.hpp, src/axom/core/tests/core_flatmap_for_all.hpp
- Adds `FlatMap::insert<ExecSpace>(beginIt, endIt)` function for batched insertions into an existing `FlatMap`.
- Updates `FlatMap::reserve()` behavior to trigger a rehash only if the required load factor would exceed the maximum load factor
- Fixes a bug in `FlatMap::erase()` where the number of elements in the map wasn't getting updated
- Fixes `FlatMap::rehash()` when allocated in device-only memory with CUDA
Resolves #1613
=> FlatMap: add batched insertion interface

src/docs/sphinx/dev_guide/release.rst
- In Axom releases over the past couple of years, we have not been being consistent with how we treat the Axom Data repo for an Axom release.
- The user guide changes hopefully make it more clear what to do.
**Note: I modified Axom GitHub releases over the past three years and applied these changes.**
=> Add some instructions to tag Axom Data repo
