.readthedocs.yml, README.md, src/docs/sphinx/web_main/index.rst
=> Small RTD build fixes

azure-pipelines.yml, scripts/azure-pipelines/linux-build_and_test.sh
Three versions of gcc, two versions of clang. 
If this can be made cleaner, please let me know.
=> Added azure builds and tests for basic linux configuration.

src/thirdparty/CMakeLists.txt
=> Fixed bug when using gcc8 without fortran.

.mailmap, README.md, host-configs/rzgenie-toss_3_x86_64_ib-clang@3.9.1.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@4.0.0.cmake, scripts/uberenv/packages/uberenv-axom/package.py, scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml
* Updates mvapich2 version for toss3 clang builds from 2.2 to 2.3
* Updates blt submodule.
=> Updates mvapich2 version for toss3 clang host-configs

src/axom/core/Array.hpp, src/axom/core/Macros.hpp, src/axom/core/StackArray.hpp, src/axom/core/Types.cpp, src/axom/core/memory_management.hpp, src/axom/core/numerics/LU.hpp, src/axom/core/numerics/Matrix.hpp, src/axom/core/tests/core_array.cpp, src/axom/core/tests/core_memory_management.cpp, src/axom/core/tests/core_stack_array.cpp, src/axom/mint/tests/mint_execution_forall_traversals.cpp, src/axom/mint/tests/mint_execution_node_traversals.cpp, src/axom/mint/tests/mint_mesh_unstructured_mesh.cpp, src/axom/primal/geometry/Plane.hpp, src/axom/quest/CMakeLists.txt, src/axom/sidre/CMakeLists.txt, src/axom/sidre/core/Array.hpp, src/axom/sidre/core/Buffer.cpp, src/axom/sidre/core/Buffer.hpp, src/axom/sidre/core/Group.cpp, src/axom/sidre/core/Group.hpp, src/axom/sidre/core/View.cpp, src/axom/sidre/core/View.hpp, src/axom/sidre/tests/sidre_buffer.cpp, src/axom/sidre/tests/sidre_buffer_unit.cpp, src/axom/sidre/tests/sidre_group.cpp, src/axom/sidre/tests/sidre_opaque.cpp, src/axom/sidre/tests/sidre_view.cpp, src/thirdparty/CMakeLists.txt, src/thirdparty/tests/raja_smoke.cpp
Here is my first pass at adding Umpire support to sidre. This PR allows the specification of an allocator to all of the Allocate methods in `Buffer`, `View` and `Group` and gives each `Group` a default allocator.
=> Feature/corbett/umpire sidre GitHub

scripts/uberenv/packages/raja/package.py, scripts/uberenv/packages/umpire/package.py, scripts/uberenv/spack_configs/darwin/compilers.yaml
* Resolves #46 
* Resolves #47
=> Some updates for uberenv TPL setup on macos

host-configs/rzuseqlac-bgqos_0-clang@4.0.0_gfortran.cmake, host-configs/rzuseqlac-bgqos_0-clang@4.0.0_xlf.cmake
- This PR updates the bgq host-configs after a recent conduit upgrade
- Resolves #92
=> Updates bgq host-configs after conduit upgrade

src/axom/slic/tests/slic_macros.cpp
Fixes slic test which failed due to extra string outputted during ctest
=> Fix SLIC test

.gitignore, src/cmake/AxomConfig.cmake
This PR fixes two minor issues:
* Resolves #55  
(credit: @MarkoSterbentz -- I pulled this out of Marko's open MIR PR #54) 
* Resolves #109
=> Fixes some open issues

RELEASE-NOTES.md, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.0_nvcc_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@upstream_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@coral.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@4.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@6.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@6.1.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@7.3.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.0.cmake, scripts/uberenv/packages/conduit/package.py, scripts/uberenv/packages/raja/package.py, scripts/uberenv/packages/umpire/package.py, src/axom/core/memory_management.hpp, src/axom/core/tests/core_memory_management.cpp, src/axom/sidre/tests/sidre_buffer.cpp, src/axom/sidre/tests/sidre_view.cpp
- This PR updates the following TPLs:
* RAJA is updated to v0.11.0
* Umpire is updated to v2.1.0, and
* Conduit is updated to v0.5.1
The host configs for `rzgenie` and `rzansel` are updated accordingly.
=> TPL Updates

scripts/llnl_scripts/llnl_lc_build_tools.py
This hopefully fixes reporting I need to run it through the system to check it.
=> Fix repoting

host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@upstream_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@nvcc.cmake, scripts/llnl_scripts/llnl_lc_build_tools.py, scripts/uberenv/packages/mfem/package.py, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/compilers.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/packages.yaml, scripts/uberenv/specs.json
- Per user request
- Resolves #190
=> Adds XL+nvcc host-config on LLNL's blueos_p9 platform

src/examples/using-with-cmake/FindAxom.cmake
Error in the CMake example pointed out by a user...
=> Fix CMake example

src/axom/sidre/examples/CMakeLists.txt, src/axom/sidre/examples/sidre_array.cpp, src/axom/sidre/examples/sidre_external_array.cpp
Adds some simple Sidre examples in response to a user request.
Resolves #188
=> Simple Sidre Examples

src/axom/sidre/examples/sidre_array.cpp, src/axom/sidre/examples/sidre_external_array.cpp
Forgot to push the documentation updates in this branch before merging.
=> Add comments to external array sidre example

RELEASE-NOTES.md, src/axom/primal/CMakeLists.txt, src/axom/primal/geometry/BoundingBox.hpp, src/axom/primal/operators/detail/intersect_bounding_box_impl.hpp, src/axom/primal/operators/intersect.hpp, src/axom/primal/tests/CMakeLists.txt, src/axom/primal/tests/primal_bounding_box_intersect.cpp, src/axom/spin/BVH.hpp, src/axom/spin/internal/linear_bvh/BVH_impl.hpp, src/axom/spin/internal/linear_bvh/QueryAccessor.hpp, src/axom/spin/internal/linear_bvh/TraversalPredicates.hpp, src/axom/spin/tests/spin_bvh.cpp
This PR adds a `findBoundingBoxes` query for BVH.
=> Bounding Box Query for BVH

host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@upstream_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@coral.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@nvcc.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@upstream_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-gcc@7.3.1.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@coral.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@nvcc.cmake, scripts/uberenv/packages/axom/package.py, scripts/uberenv/packages/raja/package.py, scripts/uberenv/packages/umpire/package.py
Fixing the issue shown in #234 ... host-configs coming eventually.
=> Add arch to raja and umpire, fix cuda path in axom

host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@upstream_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@coral.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@nvcc.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@4.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@6.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@6.1.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@7.3.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.0.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@upstream_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-gcc@7.3.1.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@coral.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@nvcc.cmake, scripts/uberenv/devtools.json, scripts/uberenv/packages/axom/package.py, scripts/uberenv/packages/conduit/package.py, scripts/uberenv/packages/py-shroud/package.py, scripts/uberenv/packages/raja/package.py, scripts/uberenv/packages/umpire/package.py, scripts/uberenv/project.json, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/devtools/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/devtools/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/packages.yaml, scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml, scripts/uberenv/specs.json
This is for all the various changes to make our internal spack packages pass the spack CI tests.
=> Changes from spack CI tests

scripts/uberenv/packages/axom/package.py
Caught in testing with Serac...
=> Fix spack install

RELEASE-NOTES.md, src/axom/core/Macros.hpp, src/axom/core/execution/execution_space.hpp, src/axom/core/execution/internal/cuda_exec.hpp, src/axom/core/execution/internal/omp_exec.hpp, src/axom/core/execution/internal/seq_exec.hpp, src/axom/core/tests/core_execution_space.cpp, src/axom/primal/examples/CMakeLists.txt, src/axom/primal/geometry/BoundingBox.hpp, src/axom/primal/geometry/NumericArray.hpp, src/axom/primal/geometry/Point.hpp, src/axom/primal/geometry/Triangle.hpp, src/axom/primal/geometry/Vector.hpp, src/axom/primal/operators/compute_bounding_box.hpp, src/axom/primal/tests/CMakeLists.txt, src/axom/quest/MeshTester.cpp, src/axom/quest/MeshTester.hpp, src/tools/mesh_tester.cpp
This PR adds a RAJA implementation of the triangle - triangle intersection algorithm in `mesh_tester.cpp` that uses a Bounding Volume Hierarchy spatial index.
Also, a ` AXOM_SUPPRESS_HD_WARN` macro was added to suppress host device warnings.
=> Triangle Intersection Algorithm using BVH

scripts/llnl_scripts/llnl_lc_build_tools.py
small change to reprint the error at the bottom after permission output.
=> Clarify when script fails

src/axom/config.hpp.in, src/axom/core/examples/core_numerics.cpp, src/axom/core/utilities/About.cpp
I missed some config header defines.
=> Add config header for lua/inlet

RELEASE-NOTES.md, src/axom/inlet/Inlet.hpp, src/axom/inlet/LuaReader.cpp, src/axom/inlet/LuaReader.hpp, src/axom/inlet/SchemaCreator.hpp, src/axom/inlet/tests/inlet_Inlet.cpp, src/axom/inlet/tests/inlet_LuaReader.cpp
This PR consists of the the last work that Aesha did.
* Makes SchemaCreator's functions pure virtual and adds missing functions
* Adds ability to access Inlet's held Reader class
* Adds ability to access Sol's Lua state held by LuaReader
=> Inlet cleanup

src/axom/inlet/DocWriter.hpp, src/axom/inlet/Verifiable.hpp
=> Quiet warnings about non-virtual destructor

scripts/uberenv/packages/axom/package.py, scripts/uberenv/packages/axomdevtools/package.py, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/devtools/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/devtools/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/packages.yaml, scripts/uberenv/spack_configs/docker/ubuntu18/packages.yaml, scripts/uberenv/spack_configs/toss_3_x86_64_ib/devtools/packages.yaml, scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml
=> move to llvm package for clang-format

.github/workflows/docker_build_tpls.yml
=> Rename workflow in hopes that one in a branch will be recognized

.readthedocs.yml
- This PR updates the python version for RTD.
=> Update RTD python version to 3.7

host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@9.0.0_upstream_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_coral.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_nvcc.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@9.0.0_upstream_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-gcc@7.3.1.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_coral.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_nvcc.cmake, scripts/uberenv/packages/axom/package.py
Thanks to @davidbeckingsale for pointing out the fix.
Rzmanta host-configs coming soon then it will be okay to merge.
=> Fix Sidre failures on blueos

azure-pipelines.yml, host-configs/docker/docker-linux-ubuntu16.04-ivybridge-gcc@8.1.0.cmake, host-configs/docker/docker-linux-ubuntu18.04-x86_64-clang@10.0.0.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@9.0.0_upstream_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_coral.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_nvcc.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@9.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1_no_fortran.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.4.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@9.0.0_upstream_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-gcc@7.3.1.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_coral.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_nvcc.cmake, scripts/uberenv/packages/conduit/package.py, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/packages.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/packages.yaml, scripts/uberenv/spack_configs/docker/ubuntu16/packages.yaml, scripts/uberenv/spack_configs/docker/ubuntu18/packages.yaml, scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml
- This PR is a TPL update
- Updates axom to use conduit 0.6.0 (no code changes needed)
- Changes host-configs to point to new TPL installations
=> update TPLs with conduit 0.6.0

src/axom/spin/tests/CMakeLists.txt
Didn't realize this was zero-based indexed...
=> Support single gpu systems

src/tools/CMakeLists.txt
NVCC is really picky about duplicate dependencies.  Not sure why this gets triggered by random PRs.
=> Remove duplicate dependencies

.gitlab-ci.yml, .gitlab/build_lassen.yml, .gitlab/build_quartz.yml, scripts/llnl_scripts/build_devtools.py, scripts/llnl_scripts/build_src.py, scripts/llnl_scripts/build_tpls.py, scripts/llnl_scripts/llnl_lc_build_tools.py
- This PR is related to CI support that can be deployed on an LC gitlab mirror. 
- Add gitlab-ci.yml to allow automated CI.
=> Setup gitlab CI

README.md
- This PR changes the RTD links in the README file to hopefully reach project-wide detente on this topic.
=> Change links to docs to (hopefully) reach project-wide detent

scripts/llnl_scripts/llnl_lc_build_tools.py
=> Add back spec that got lost somehow

RELEASE-NOTES.md, src/thirdparty/CMakeLists.txt, src/thirdparty/fmt/args.h, src/thirdparty/fmt/chrono.h, src/thirdparty/fmt/color.h, src/thirdparty/fmt/compile.h, src/thirdparty/fmt/core.h, src/thirdparty/fmt/format-inl.h, src/thirdparty/fmt/format.h, src/thirdparty/fmt/locale.h, src/thirdparty/fmt/os.h, src/thirdparty/fmt/ostream.h, src/thirdparty/fmt/printf.h, src/thirdparty/fmt/ranges.h
https://github.com/fmtlib/fmt/pull/2190
Updates fmt to newest master branch.  This includes the alternate fix for the compiler bug we ran into with nvcc+xlc from the author.
=> Update fmt after getting a better fix from author

.gitlab-ci.yml, .gitlab/build_lassen.yml, .gitlab/build_ruby.yml
The gitlab ci that runs after you merge to develop or main has been broken.  This fixes at least the following problem:
```
You do not have the initial commit yet
From https://github.com/spack/spack
* branch            764c17053041a65f684ce565a2598d705b04a16b -> FETCH_HEAD
fatal: Unable to create '/usr/WS2/white238/gitlabbuilds/axom_tpls/170/blueos_3_ppc64le_ib_p9/2021_04_13_11_53_02/spack/.git/index.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```
=> Attempt to fix the full build jobs

scripts/spack/packages/axom/package.py
Noticed small oversights in the last update.  Testing them now but they don't have actual changes in our host-configs so I am not going to rebuild the tpls.
=> Small spack package fixes

RELEASE, src/cmake/AxomVersion.cmake
- This PR is a part of v0.5.0 release
- Update release number in ``RELEASE`` and ``AxomVersion.cmake``
- Missed changes in the rc-v0.5.0 branch and #555
=> Update release numbers to 0.5.0

src/axom/mint/mesh/CurvilinearMesh.hpp, src/axom/mint/mesh/RectilinearMesh.hpp, src/axom/sidre/core/Group.hpp, src/axom/slam/BitSet.hpp, src/axom/slam/policies/SubsettingPolicies.hpp
- Fixes msvc build after changes to dependencies in #578
=> Marks several static members with AXOM_EXPORT after changes in #578

host-configs/docker/docker-linux-ubuntu16.04-ivybridge-gcc@8.1.0.cmake, host-configs/docker/docker-linux-ubuntu18.04-x86_64-clang@10.0.0.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@9.0.0_upstream_xlf.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1_coral.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1_nvcc.cmake, host-configs/ruby-toss_3_x86_64_ib-clang@10.0.0.cmake, host-configs/ruby-toss_3_x86_64_ib-clang@9.0.0.cmake, host-configs/ruby-toss_3_x86_64_ib-gcc@8.1_no_fortran.cmake, host-configs/ruby-toss_3_x86_64_ib-intel@18.0.2.cmake, host-configs/ruby-toss_3_x86_64_ib-intel@19.0.4.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@9.0.0_upstream_xlf.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@7.3.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_coral.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1_nvcc.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@9.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1_no_fortran.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.4.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@8.0.1_nvcc_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-clang@9.0.0_upstream_xlf.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-gcc@7.3.1.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_coral.cmake, host-configs/rzmanta-blueos_3_ppc64le_ib-xl@16.1.1_nvcc.cmake, scripts/spack/packages/axom/package.py
=> Small typo in Spack package

scripts/spack/packages/axom/package.py
This PR returns us to a working state after a couple changes on the Spack side:
* Restores some necessary compiler checks that were mistakenly removed from a block of code in our spack package
* Returns the `~shared` variant to the conduit `depends_on` line and adds the comment that this can be removed when the new concretizer is enabled and that it should not be pushed back to spack proper
This PR really doesn't have a change from what was working before, so I opted to not rebuild all the TPLs again. I tested it on toss3 and blueos.
=> Fix compiler checks that were mistakenly removed

azure-pipelines.yml, scripts/azure-pipelines/linux-check.sh, src/axom/core/Map.hpp
Some people actually want it to check the style.  So picky.
=> Turn on clangformat in style checker

scripts/spack/packages/axom/package.py
Fixes #616 
Running it through the tpl builds locally to make sure it doesn't blow up
=> fix implicit link on xl

RELEASE-NOTES.md, src/axom/CMakeLists.txt, src/axom/core/CMakeLists.txt, src/axom/core/tests/CMakeLists.txt, src/axom/core/tests/core_serial_main.cpp, src/axom/core/tests/utils_system.hpp, src/axom/core/utilities/System.cpp, src/axom/core/utilities/System.hpp
I needed these two functions in Serac and they have a pretty good general purpose.
=> User and Host name utility functions

.gitlab/build_ruby.yml
=> Handle SLURM update

src/axom/quest/CMakeLists.txt, src/axom/spin/tests/CMakeLists.txt
- clarify test dependency variable
- guard against test requiring mint
- add error check for spin in quest
=> Verify component dependencies

src/tools/CMakeLists.txt
=> Guards `data_collection_util` against primal being off

src/axom/inlet/Container.cpp, src/axom/inlet/Function.hpp
closes #617
opened #653 to make sure this is reviewed in a more broader sense down the road.
=> Cleans-up Inlet warning

src/axom/core/tests/utils_about.hpp
=> Guard AXOM_VERSION_EXTRA

src/axom/primal/geometry/Polyhedron.hpp
=> Initialize array in Polyhedron before use

RELEASE-NOTES.md, src/axom/inlet/InletVector.hpp, src/axom/inlet/LuaReader.cpp, src/axom/inlet/examples/mfem_coefficient.cpp, src/axom/inlet/examples/nested_structs.cpp
=> Add convenience constructor to InletVector and make its single-arg ctors explicit

RELEASE-NOTES.md, src/axom/core/Array.hpp, src/axom/core/ArrayBase.hpp, src/axom/core/tests/core_array.hpp
=> Fix for Array assignment operators

RELEASE-NOTES.md, src/axom/inlet/Container.cpp, src/axom/inlet/Field.cpp, src/axom/inlet/Field.hpp, src/axom/inlet/tests/inlet_errors.cpp
=> More helpful error messages for Inlet range/valid value failures

scripts/spack/packages/axom/package.py, scripts/spack/packages/axom/scr_examples_gtest.patch, src/CMakeLists.txt, src/axom/inlet/CMakeLists.txt, src/axom/klee/CMakeLists.txt, src/axom/sidre/examples/spio/CMakeLists.txt
Not rebuilding as they have no changes to our TPLs due to forced versions on our end.
=> Small noop changes to Spack package

.github/workflows/docker_build_tpls.yml, azure-pipelines.yml, host-configs/docker/docker-linux-ubuntu20.04-x86_64-gcc@11.1.0.cmake, scripts/azure-pipelines/linux-build_and_test.sh, scripts/docker/dockerfile_gcc-11, scripts/spack/configs/docker/ubuntu20/compilers.yaml, scripts/spack/configs/docker/ubuntu20/packages.yaml, src/thirdparty/axom/sol.hpp
This adds a new gcc-11 docker image build and azure test.
=> Add gcc-11 docker

RELEASE-NOTES.md, src/axom/core/ArrayView.hpp, src/axom/quest/Delaunay.hpp
- This (small) PR is a bugfix for some issues I encountered on LLNL's blueos platform in an axom configuration without RAJA or Umpire
=> Bugfix for XL configuration without RAJA or Umpire

.gitlab/build_corona.yml, RELEASE-NOTES.md, src/axom/config.hpp.in, src/thirdparty/CMakeLists.txt, src/thirdparty/axom/fmt/args.h, src/thirdparty/axom/fmt/chrono.h, src/thirdparty/axom/fmt/color.h, src/thirdparty/axom/fmt/compile.h, src/thirdparty/axom/fmt/core.h, src/thirdparty/axom/fmt/format-inl.h, src/thirdparty/axom/fmt/format.h, src/thirdparty/axom/fmt/locale.h, src/thirdparty/axom/fmt/os.h, src/thirdparty/axom/fmt/ostream.h, src/thirdparty/axom/fmt/printf.h, src/thirdparty/axom/fmt/ranges.h
=> Guard compiler defines in fmt

.gitlab/build_corona.yml
Turns back on the Corona source job
=> turn back on corona job

src/docs/sphinx/dev_guide/updating_tpls.rst, src/docs/sphinx/quickstart_guide/config_build.rst
Documenting the various build scripts and their inputs.
https://axom.readthedocs.io/en/task-white238-document_all_the_builds/docs/sphinx/dev_guide/updating_tpls.html#build-scripts-and-their-configuration-files
=> Document all the build things

src/axom/sidre/core/MFEMSidreDataCollection.cpp
- add the correct tree structure when writing data to help visit display our data
=> add tree pattern when writing MFEMSidreDataCollection

scripts/make_local_branch_from_fork_pr.sh
Update BLT to newest develop and adds a symlink to rich's fork pr script
=> update blt and add symlink to local branch from pr script

.gitlab/build_lassen.yml, .gitlab/build_rzansel.yml, .uberenv_config.json, host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.1.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.2_cuda.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@8.3.1.1.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@8.3.1.2_cuda.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1.1.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1.2_cuda.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.2_cuda.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@8.3.1.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@8.3.1.2_cuda.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1.2_cuda.cmake, scripts/spack/configs/blueos_3_ppc64le_ib_p9/compilers.yaml, scripts/spack/configs/blueos_3_ppc64le_ib_p9/packages.yaml, scripts/spack/configs/config.yaml, scripts/spack/packages/axom/package.py, scripts/spack/packages/c2c/package.py, scripts/spack/packages/mfem/package.py, scripts/spack/specs.json
This includes several bug fixes on the Spack side and moves us forward to the newest Spack develop.  This includes the new multi-build system support.
This upgrades our compiler versions and simplifies a lot of the compiler specs.  We should re-evaluate after the compiler survey to make sure we didn't miss any specs. But this does bring us closer to what our customers are using.
=> Update BlueOS compilers

.gitlab/build_tioga.yml
Not sure if this is going to fix our problem but it was recommended by Gyllenhaal.
=> Advised fix for Tioga CI problems

RELEASE-NOTES.md, src/axom/core/Array.hpp
- This PR is a documentation fix
- Fix small documentation errors that Rich pointed out and I accidentally omitted from a previous PR.
=> Small documentation fixes accidentally omitted from an earlier PR.

src/axom/core/CMakeLists.txt, src/axom/quest/DistributedClosestPoint.hpp, src/axom/quest/detail/PointFinder.hpp, src/axom/quest/examples/quest_distributed_distance_query_example.cpp, src/axom/spin/BVH.hpp
- It allows the code to configure/build/test when using RAJA but not Umpire
- Discovered when working on #982
=> Fixes build and tests when using RAJA without Umpire

src/axom/inlet/docs/sphinx/quick_start.rst
- This PR is a documentation improvement.
- Fixes a broken URL to a GitHub source file.
=> Fix URL in documentation

src/axom/inlet/Container.cpp, src/axom/inlet/Field.cpp, src/axom/inlet/JSONSchemaWriter.cpp
Small thing that I have wanted to do for a while.
=> Inlet: Convert to new range based for loop

src/axom/core/utilities/BitUtilities.hpp
Fixes #798 
Related Serac issues/PRs:
https://github.com/LLNL/serac/issues/936
https://github.com/LLNL/serac/pull/937
=> Guard intrinsic headers against nvcc

RELEASE-NOTES.md, host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.1.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.2_cuda.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@8.3.1.1.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-gcc@8.3.1.2_cuda.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1.1.cmake, host-configs/lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1.2_cuda.cmake, host-configs/quartz-toss_4_x86_64_ib-clang@14.0.6.cmake, host-configs/quartz-toss_4_x86_64_ib-gcc@10.3.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.2_cuda.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@8.3.1.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-gcc@8.3.1.2_cuda.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1.1.cmake, host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl@16.1.1.2_cuda.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-clang@9.0.0.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.1.0_nofortran.cmake, host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.3.1.cmake, host-configs/rzgenie-toss_3_x86_64_ib-intel@19.0.4.cmake, host-configs/rzvernal-toss_4_x86_64_ib_cray-clang@14.0.0_hip.cmake, host-configs/tioga-toss_4_x86_64_ib_cray-clang@14.0.0_hip.cmake, scripts/spack/configs/toss_4_x86_64_ib_cray/spack.yaml, scripts/spack/packages/c2c/package.py, src/axom/quest/tests/quest_intersection_shaper.cpp, src/thirdparty/tests/mfem_smoke.cpp
- It updates our c2c dependency to c2c@1.8.0
- Resolves #1042 
- Fixes #980 
- Fixes #979
=> Update to c2c@1.8.0

host-configs/rzwhippet-toss_4_x86_64_ib-clang@14.0.6.cmake, host-configs/rzwhippet-toss_4_x86_64_ib-gcc@10.3.1.cmake
- This PR adds host-configs for rzwhippet -- a toss4 CTS-2 machine at LLNL
=> Adds host-configs for an LLNL CTS-2 toss4 machine

RELEASE-NOTES.md
Kenny noticed this after we fixed things last night. It was not worth starting over but the pattern should be corrected.
Also moves us to the main branch of radiuss shared configs.
=> fix release notes version links

.gitlab-ci.yml
We are currently abusing the space of the Gitlab server. This should solve this.
=> limit artifact lifetime

scripts/spack/packages/axom/package.py, scripts/spack/packages/axomdevtools/package.py, src/axom/config.hpp.in, src/axom/inlet/tests/CMakeLists.txt, src/axom/inlet/tests/inlet_jsonschema_writer.cpp, src/cmake/thirdparty/SetupAxomThirdParty.cmake
- This PR is a build system/TPL change
- Fixes #501 
- Adds `jsonschema` to axom's devtools
=> Add jsonschema to devtools

src/axom/primal/tests/primal_clip.cpp
This PR adds test case from #1206.
Closes #1206.
=> Add missing hex-tet test case

.gitlab/build_tioga.yml
=> Utilize Tioga CI queue

.uberenv_config.json, scripts/spack/configs/blueos_3_ppc64le_ib_p9/spack.yaml, scripts/spack/packages/axom/package.py
I built this successfully on all platforms but there is no change in libraries so I am not updating host-configs.
=> The Great Spack Package Merge of 2024

src/axom/core/execution/internal/seq_exec.hpp, src/axom/core/tests/core_execution_space.hpp, src/axom/mint/execution/internal/structured_exec.hpp
=> Remove use of deprecated RAJA::loop_*

scripts/llnl_scripts/llnl_lc_build_tools.py
This will hopefully help us track down what is causing the hang on Tioga
=> Use `tee` instead of reading log files to the screen in Build scripts

scripts/llnl_scripts/llnl_lc_build_tools.py
I'd say this was an elaborate April Fool's Joke but it's just sad.
`tee` does not forward the error code of the previous command like I assumed and clearly didn't check. My bad.
```
$ ./error.sh; echo $?
~~~~~~~~ test about to error
1
$ ./error.sh | tee output; echo $?
~~~~~~~~ test about to error
0
```
There are some very specific to bash ways of handling this, which we can't rely on, or I can jump through some pipe'ing hoops in Python. I'll do the later later.
=> Revert usage of `tee`

.gitlab/build_tioga.yml
LC says this will be down all week.
=> temporarily turn off pci queue on tioga

RELEASE-NOTES.md, src/axom/primal/operators/closest_point.hpp, src/axom/primal/tests/primal_closest_point.cpp
- Adds closest_point operator for Segment at the request of myself
=> Add closest_point operator for Segment

.gitlab-ci.yml, scripts/docker/dockerfile_clang-10, scripts/docker/dockerfile_gcc-11, scripts/docker/dockerfile_gcc-9_cuda-11
At some point we stopped deleting the correct directories in our containers.
=> Delete correct Spack stage directories in docker image creation

.gitlab/build_tioga.yml, .uberenv_config.json, scripts/spack/configs/blueos_3_ppc64le_ib_p9/spack.yaml, scripts/spack/configs/docker/ubuntu20/spack.yaml, scripts/spack/configs/toss_4_x86_64_ib/spack.yaml, scripts/spack/configs/toss_4_x86_64_ib_cray/spack.yaml, scripts/spack/packages/axom/package.py
=> merge changes from spack

src/axom/primal/geometry/BezierCurve.hpp, src/axom/primal/operators/detail/intersect_impl.hpp
=> Silence warnings about shadow declarations

src/docs/sphinx/dev_guide/updating_tpls.rst
- This PR involves documentation of the TPL build/update process in the Axom Dev Guide.
- It clarifies some points and corrects some script names, directory names, etc.
The relevant section of generated docs for this PR is here: https://axom.readthedocs.io/en/task-rhornung67-fix-devdocs/docs/sphinx/dev_guide/updating_tpls.html
=> TPL build instructions

src/axom/sidre/examples/sidre_stressgroups.cpp
- This PR sets up a branch from a PR on a fork so that GitLab CI will run and it can be merged.
The original PR is https://github.com/LLNL/axom/pull/1371
Please review and approve this one.
=> Pr from fork/1371

src/docs/sphinx/dev_guide/continuous_integration.rst, src/docs/sphinx/dev_guide/dev_summary.rst, src/docs/sphinx/dev_guide/github.rst, src/docs/sphinx/dev_guide/gpu_porting.rst, src/docs/sphinx/dev_guide/pull_requests.rst, src/docs/sphinx/dev_guide/release.rst, src/docs/sphinx/dev_guide/updating_tpls.rst
- This PR cleans up some minor typos and nits in the Dev Guide.
@BradWhitlock pointed out a small issue, which I addressed. That fix is small but would still leave @white238 as the record holder for the smallest PR change in Axom. So, I decided to do a little house cleaning...
=> Fix some typos and minor issues in Dev Guide

.github/actions/apply-style/Dockerfile, .github/actions/apply-style/entrypoint.sh, .github/workflows/apply-style.yml
This can't be used or tested until it is in the default branch. This was tested in Serac.
=> Add ability to style a PR by commenting '/style'

RELEASE-NOTES.md, src/thirdparty/axom/CLI11.hpp
These minor follow-ups to https://github.com/LLNL/axom/pull/1401 were suggested in a recent team meeting.
1. Mention the change in the release notes
2. Add comment to note our changes, so we'd see it when upgrading CLI11.
=> Add comment and release note item regarding recent CLI11 changes.

src/axom/quest/MeshViewUtil.hpp, src/axom/spin/BVH.hpp
Just a small change to silence warnings.
=> Silence warnings about shadow parameters

src/axom/primal/operators/detail/clip_impl.hpp, src/axom/slam/policies/IndirectionPolicies.hpp, src/axom/slam/tests/slam_map_BivariateMap.cpp, src/axom/slic/tests/slic_macros.cpp, src/axom/slic/tests/slic_macros_parallel.cpp
Just a few minor changes to silence complaints from the ~app developers~ compilers.
=> Silence a few compiler warnings

src/axom/multimat/multimat.cpp, src/axom/primal/geometry/KnotVector.hpp, src/axom/slam/DynamicConstantRelation.hpp
Silence warnings about unused variables and shadow parameters.
=> Silence warnings

RELEASE-NOTES.md
An entry in the release notes is added for the changes merged in #1494
=> Release notes added for loadExternalData merge

.uberenv_config.json, scripts/spack/configs/blueos_3_ppc64le_ib_p9/spack.yaml, scripts/spack/configs/toss_4_x86_64_ib/spack.yaml, scripts/spack/configs/toss_4_x86_64_ib_cray/spack.yaml, scripts/spack/packages/axom/package.py, scripts/spack/packages/axomdevtools/package.py, scripts/spack/packages/c2c/package.py, scripts/spack/packages/cray-mpich/package.py
Shouldn't be merged until this PR is approved and merged in case they have requests:
https://github.com/spack/spack/pull/49183
=> Changes from Spack repo

src/axom/lumberjack/CMakeLists.txt
This PR is a bug fix that adds a missing file to CMakeLists
=> added missing file in CMakeLists

src/docs/sphinx/dev_guide/updating_tpls.rst
This PR:
- Amends some of the directions on updating tpls.
- Update radiuss-spack-configs submodule to a main commit, since v2025.03.0 changes have been merged.
ReadTheDocs documentation can be found here: https://axom.readthedocs.io/en/docs-han12-rtd_tpl_update/docs/sphinx/dev_guide/updating_tpls.html
Resolves #1533
=> Amend directions for updating tpls

RELEASE-NOTES.md, src/axom/quest/MeshTester.cpp, src/axom/quest/MeshTester.hpp, src/axom/sina/CMakeLists.txt, src/axom/slam/Map.hpp, src/axom/slam/examples/UnstructMeshField.cpp, src/tools/CMakeLists.txt, src/tools/mesh_converter.cpp, src/tools/mesh_tester.cpp
- It adds a new axom tool to convert from volumetric ProE tet meshes to boundary surface STL triangle meshes
- It resolves #1543 
```
> ./bin/mesh_converter -i ../data/quest/cup.proe     -o cup.stl  --caliper report --edge-histogram 
[INFO] Axom Version: [v0.11.0-f08fde044] 
[INFO] Reading pro-e file: '../data/quest/cup.proe' ... 
[INFO] Input mesh has 171 vertices and 574 tets 
[INFO] Edge Length Histogram:
2^5: 28 edges
2^6: 1,478 edges
2^7: 1,938 edges
[INFO] Edge Length Ranges:
2^5: [25.44050869827115, 31.99387414879156]
2^6: [32.17354229146461, 63.871627757374185]
2^7: [64.0865830280402, 125.58879159874492]
[INFO] Bounding box of mesh: { min:(-159.526,-158.568,-236.63); max:(159.526,159.059,0); range:<319.052,317.627,236.63> } 
[INFO] After welding, tet mesh …
```
=> Adds a tool to extract boundary meshes from ProE tet meshes

src/docs/sphinx/dev_guide/release.rst
- This PR contains developer guide changes in an attempt to make the release process clearer.
Resolves: https://github.com/LLNL/axom/issues/1561
@gunney1 please suggest changes for improvement.
=> Attempt to make release process clearer

RELEASE-NOTES.md, src/axom/primal/geometry/BoundingBox.hpp, src/axom/primal/tests/primal_boundingbox.cpp, src/axom/sidre/examples/sidre_mcarray.cpp, src/axom/sina/CMakeLists.txt, src/axom/sina/examples/CMakeLists.txt, src/axom/sina/examples/sina_fortran.f, src/axom/sina/interface/sina_fortran_interface.f.in
- It fixes Sina's fortran module generation and inclusion 
- With this fix, we can once again use `ninja` w/ Axom
- Misc: Also resolves https://github.com/LLNL/axom/issues/1602
Thanks @white238 for helping me work through the Sina config fixes
=> Fixes sina's Fortran module generation

src/axom/quest/MarchingCubes.hpp
Just a documentation comment I missed before.
=> Minor documentation update.

.gitlab-ci.yml, .gitlab/build_tioga.yml, .gitlab/build_tuolumne.yml, host-configs/tuolumne-toss_4_x86_64_ib_cray-cce@19.0.0_hip.cmake, host-configs/tuolumne-toss_4_x86_64_ib_cray-rocmcc@6.2.1_hip.cmake, host-configs/tuolumne-toss_4_x86_64_ib_cray-rocmcc@6.3.1_hip.cmake
This PR:
- Adds a Gitlab CI job on tuolumne
- Add host-configs for tuolumne 
- Updates uberenv
=> Gitlab CI - Add tuolumne

src/axom/bump/clipping/ClipField.hpp, src/axom/core/tests/core_device_hash.hpp, src/axom/core/tests/core_flatmap_for_all.hpp, src/axom/mint/tests/StructuredMesh_helpers.hpp, src/axom/mir/ElviraAlgorithm.hpp, src/axom/quest/Delaunay.hpp, src/axom/quest/Discretize.cpp, src/axom/quest/detail/PointFinder.hpp, src/axom/quest/examples/quest_distributed_distance_query_example.cpp, src/axom/quest/examples/quest_shape_in_memory.cpp
This PR resolves #1670, an issue about reported C++20 warnings with gcc. The PR also fixes some other warnings, including one in Equi-Z MIR where the fix should result in slightly less work.
=> Fix some C++20 warnings.
